bluealloy/revm

Cargo.lock, crates/revm_precompiles/Cargo.toml, crates/revm_precompiles/src/secp256k1.rs
Bumps k256 to latest version, so that revm_precompiles can be used with the k256 from ethers-rs/foundry
=> chore: bump k256

bins/revme/src/debugger/ctrl/ctrl.rs, bins/revme/src/statetest/trace.rs, crates/revm/src/evm_impl.rs, crates/revm/src/inspector.rs
An attempt at fixing #45 
- Adds parameters to `create_end` and `call_end`
- Calls `create_end` and `call_end` in the correct places
Putting this in draft to get comments - is this the right direction and/or does this break anything?
Closes #45
=> Inspector fixup

crates/revm_precompiles/src/secp256k1.rs
k256 ecrecover currently is unwrapping and if the signature is invalid this will panic. because the error of `recoverable::Signature::try_from` is the same as `k256::ecdsa::Error` I decide to propagate back the error that then in handled in the `ec_recover_run` function.
=> propagate the back the error parsing k256 ecrecover

crates/revm/src/lib.rs
Needed to interact with `transact_ref` and `inspect_ref`
=> fix: export `Filth`

crates/revm/src/lib.rs, crates/revm/src/machine/memory.rs, crates/revm/src/machine/stack.rs
Parts of the `Machine` API is unusable without these exports (which is important for inspectors)
=> fix: export missing machine structs

crates/revm/src/db/in_memory_db.rs
This allows CacheDB to be used in a read-only fashion
Also slightly improves some docs
=> feat: implement `DatabaseRef` for `CacheDB`

crates/revm/src/evm_impl.rs, crates/revm/src/inspector.rs
Improves inspector ergonomics by providing a default implementation for all the functions. For example, if you want to create an `OverrideSpecInspector` you currently have to stub all of the other functions.
Also correctly calls `step` and `step_end` for inspectors.
I noticed that `Inspector::initialize` is not used anywhere - is it supposed to?
=> refactor: improve inspector ergonomics

crates/revm/src/evm_impl.rs
We need to call the `end` functions on the inspectors in case we return early, since some inspectors might have internal state that should change on every call (e.g. the Foundry tracer).
- When `create` returns early, `create_end` is also called
- When `call` returns early, `call_end` is also called
=> feat: call insp end functions on early return

crates/revm_precompiles/Cargo.toml
=> chore: do not pin k256 patch version

Cargo.lock
per suggestion in https://github.com/bluealloy/revm/issues/77#issuecomment-1069134023, was my mistake forgot to bump cargo lock in #81
=> bump k256 to 0.10.4

crates/revm/src/evm_impl.rs, crates/revm/src/inspector.rs
In Foundry we need to collect logs even if the call reverts, so we had an `extract_log` function that basically was a peeking version of `log` in REVM but it also meant that we did double work most of the time. This just adds a log hook for inspectors
=> feat: `Inspector::log`

crates/revm/src/evm_impl.rs, crates/revm/src/instructions/host.rs, crates/revm/src/models.rs, crates/revm/src/subroutine.rs
- Prevents overflows in `SubRoutine::transfer` for the recipient
- Allows inspectors to see what kind of call is being made - some inspectors in Foundry manage state that depend on this info
=> Various fixes

crates/revm/src/models.rs
Hey @rakita 👋
I guess this is a question and PR at the same time. 
If I understand `AccountInfo` correctly, the `code` being `None` doesn't mean that the account doesn't have any code, but that you should load it from a `Database`. Is that right? If so, maybe you want to merge this PR that documents it.
=> Update AccountInfo#code documentation

bins/revme/src/debugger/ctrl/history.rs, crates/revm_precompiles/src/lib.rs
Plus use [captured identifiers from rust 1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings),
Tool-aided by [comby-rust](https://github.com/huitseeker/comby-rust)
=> chore: refactor to exact option combinators

bins/revme/src/statetest/runner.rs, bins/revme/src/statetest/trace.rs, crates/revm/src/instructions/control.rs, crates/revm/src/instructions/opcode.rs, crates/revm/src/instructions/stack.rs, crates/revm/src/interpreter.rs, crates/revm/src/interpreter/contract.rs
@onbjerg can you run this? I guess it should be a little bit faster than the previous code, but not by a lot.
=> Rework analysis

crates/revm/src/evm_impl.rs, crates/revm/src/instructions/system.rs
\+ empty constant keccak taken from [here](https://docs.rs/keccak-hash/latest/src/keccak_hash/lib.rs.html#18-21)
\- bytes.copy before keccak (not sure if it would get optimized away anyway...)
\- access_list.clone
=> empty keccak constant and remove access_list.clone

Cargo.lock, crates/revm/Cargo.toml, crates/revm/src/lib.rs
access to this is useful to replicate `Evm::inspect_ref` with a custom `Database`, other than `RefDBWrapper`
I guess alternatively this could be achieved by making `RefDBWrapper` generic but would require breaking changes.
=> chore: export evm_inner

crates/revm/src/specification.rs
this allows checks like 
`if env.cfg.spec_id >= SpecId::LONDON { }`
=> feat: add ord derives to specid

Cargo.lock, bins/revme/src/statetest/merkle_trie.rs, bins/revme/src/statetest/runner.rs, crates/revm/Cargo.toml, crates/revm/src/db/in_memory_db.rs
As discovered here https://github.com/foundry-rs/foundry/issues/1894
deleting storage or account entries does not play nice with fork mode which basically does:
```rust
if !db.contains(acc) {
// fetch from remote 
}
```
So deleting accounts/slots (when empty) would result in the fork's account/slot being served and not 0 or the empty account.
* on `CacheDb::commit` don't delete `AccountInfo` or storage entries in the CacheDb's maps 
* also bumps to v1.6.0
=> don't delete account and storage entries on commit

bins/revm-test/src/bin/analysis.rs, bins/revm-test/src/bin/snailtracer.rs, bins/revme/src/statetest/runner.rs, crates/revm/src/evm.rs, crates/revm/src/evm_impl.rs, crates/revm/src/models.rs, crates/revmjs/src/lib.rs
Following the discussion in #167 ; now the revm/evm `transact`/`inspect` methods are returning an `ExecutionResult` struct, which includes the `gas_refunded` value.
=> revm/evm: Return `ExecutionResult`, which includes `gas_refunded`

crates/revm/src/db/in_memory_db.rs
So this PR does 2 things in `revm::CachDB`:
1. It updates the `insert_account_storage` so that it doesn't override the underlying account info
2. It adds a new method `replace_account_storage` to completely replace the account storage
For (1), I don't actually know whether it was intentional to override the account info with the default (empty) value. I don't quite see when this would be useful.
For (2), it would be useful for implementing the `StateOverride` that's in [geth](https://geth.ethereum.org/docs/rpc/ns-eth#3-object---state-override-set), where there is an option to completely override the storage.
I added tests for both methods.
=> revm: Update account storage methods in CacheDB

bins/revme/src/lib.rs, bins/revme/src/statetest/mod.rs
I found these modules useful for loading and running state tests, so I'm wondering if the `revme` crate could expose them or if the modules could be moved to a separate crate ("test-utils", or something like that).
I'm currently using a fork of revm with these changes but this creates issues when I'm also using parts of foundry (that also depends on revm) as a dependency. 
I realize the crate is currently described as binary crate so marking this as a draft.
=> Expose Ethereum test utilities in revme crate 

.github/workflows/ethereum-tests.yml, Cargo.toml
```console
➜  revm git:(ethtests-profile) git revert 7ecc92095c14566a264df790cf9f8792a3341b22    
[ethtests-profile 3d77606] Revert "Revert "refactor(revm): use u64 for gas refund counter (#180)" (#187)"
4 files changed, 11 insertions(+), 11 deletions(-)
➜  revm git:(ethtests-profile) ✗ cargo run --profile ethtests -p revme -- statetest ethtests/GeneralStateTests
Finished ethtests [optimized + debuginfo] target(s) in 0.30s
Running `target/ethtests/revme statetest ethtests/GeneralStateTests`
Start running tests on: "ethtests/GeneralStateTests"
█████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 626/2607
thread '<unnamed>' panicked at …
```
=> chore(ci): use ethtests profile for CI tests

crates/revm/src/interpreter/bytecode.rs
Needed for https://github.com/foundry-rs/foundry/pull/2954
=> feat: expose hash on `BytecodeLocked`

Cargo.lock, crates/revm/src/evm.rs, crates/revm/src/specification.rs, crates/revm_precompiles/Cargo.toml, crates/revm_precompiles/src/lib.rs
Small optimization: we dont need to recreate HashMap with precompiles every time.
=> Cache precompile HashMap

crates/revm/src/lib.rs
`revm_precompiles` is already a dependency, for convenience, reexport `revm_precompiles` as `precompiles` within `revm`
=> reexport revm_precompiles as precompiles

crates/revm/src/db/in_memory_db.rs
The `Database(Ref) impl for `EmptyDb` never returns an error.
use `Infallible` as error type to indicate that `<EmptyDb as Database(Ref)::...` will never return an error
=> use Infallible for memory db's error type

crates/revm_precompiles/src/lib.rs
Some derives to PrecompileSpecId (mirros `revm::SpecId`)
manual debug impl for `Precompile`
=> chore: add some derives for precompiles

bins/revme/src/debugger/ctrl/ctrl.rs, bins/revme/src/statetest/runner.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/evm_impl.rs
make Database::basic consistent in DatabaseRef::basic.
Reported here: https://github.com/bluealloy/revm/issues/200
=> fix: make DatabaseRef::basic consistent with Database

bins/revm-test/Cargo.toml, bins/revme/Cargo.toml, crates/revm/Cargo.toml, crates/revm/src/evm_impl.rs, crates/revm/src/models.rs, crates/revm_precompiles/Cargo.toml, crates/revmjs/Cargo.toml
Allow to configure if created bytecode is going to by analysed, checked or saved as raw code. By default it will be analysed, only time when this becomes relevant is when you want to switch between forks as analysis takes into account what spec is currently using and it is different from spec to spec. 
In future we will probably add spec friendly analysis with only jump table and without gas blocks.
One more small change is around making cfg perf bytecode limit as `Option` if not set consensus value would be used.
=> Cfg choose create analysis, option on bytecode size limit

crates/revm/src/gas/calc.rs, crates/revm/src/instructions/host.rs, crates/revm/src/instructions/system.rs
Minor cleanup on gas calculation by removing U256 and using native u64.
When testing on snailtracer i got very small to no signification improvement with this change, I am assuming that compiler did optimization with U256 as we use `as_usize_or_fail` every time.
=> Do gas calculation using u64 and not U256

CHANGELOG.md, Cargo.lock, bins/revm-test/Cargo.toml, bins/revme/Cargo.toml, crates/revm/CHANGELOG.md, crates/revm/Cargo.toml, crates/revm_precompiles/CHANGELOG.md, crates/revm_precompiles/Cargo.toml, crates/revmjs/Cargo.toml
=> revm bump v2.0.0, precompile bump v1.1.1

crates/revm/src/interpreter/memory.rs
add another delegate function to `Memory` that allows shrinking the allocated 4 * 1024 bytes down to what's actually used.
this is likely the cause for the memory hog in foundry's tracer impl
cc @shekhirin
=> feat: add Memory::shrink_to_fit

crates/revm/src/journaled_state.rs
provide a way to access the `original_value` and find out if the `present_value` is changed
=> chore: expose original value on storageslot

bins/revme/src/statetest/trace.rs, crates/revm/src/inspector.rs, crates/revm/src/lib.rs
Gas counting became a bit harder with the introduction of gas blocks composed during analysis. So `GasInspector` was introduced to make it easier to count remaining gas after each executed step.
Approach was adopted from https://github.com/bluealloy/revm/blob/1e25c99b544863d15610e9af8e623dd173397b48/bins/revme/src/statetest/trace.rs#L10-L17
=> feat(revm, revme): gas inspector

crates/revm/src/db/in_memory_db.rs, crates/revm/src/evm_impl.rs, crates/revm/src/instructions/opcode.rs, crates/revm_precompiles/src/lib.rs
Making `OpCode` easier to convert into `u8` using `u8()` method by not taking ownership and adding some derive traits to the `OpCode` struct
=> Borrow self and add derive traits for OpCode

crates/revm/Cargo.toml, crates/revm/src/evm_impl.rs, crates/revm/src/models.rs
Fixes #236.
This PR should be merged after #237, as it also amends the `dev` feature flag.
=> feat: allow block gas limit to be toggled off

crates/revm/src/db/web3db.rs
Currently this check ensures the passed in value is greater than self.block_number. I think is likely a bug as I've seen transactions in the wild which succeed on geth but revert when using this revm code due to the sanity check.
I think ensuring the passed in value is less than self.block_number makes more sense as that excludes block numbers for blocks ahead of the self.block_number which may not exist yet.
=> fix sanity check

crates/revm/src/instructions/system.rs
Fixes this issue: https://github.com/bluealloy/revm/issues/255 "Tx unexpectedly reverts with "out of gas" reason"
=> Bugfix: if returndatacopy is len 0 return after initial cost

bins/revme/src/statetest/models/spec.rs, bins/revme/src/statetest/runner.rs, crates/revm/src/evm.rs, crates/revm/src/instructions/opcode.rs, crates/revm/src/specification.rs
`HighGasPrice` test is handled correctly but it does not match the exception in eth/tests. 
Added spec for `Merge+3540+3670` and disabled it, as we don't have support for it.
=> chore(eth/test): Added OEF spec for tests. Skip HighGasPrice

CHANGELOG.md, Cargo.lock, crates/revm/CHANGELOG.md, crates/revm/Cargo.toml
bump release noted and revm version.
real release is going to be in `release/v17` branch
=> Bump v17 tag, revm v2.2.0

crates/revm/src/lib.rs
I am evaluating the migration from SputnikVM to REVM for a project of my company. 
Anyway, I am currently unable to migrate some of our unit tests because the Account storage is defined as `Map<U256, StorageSlot>` but the `StorageSlot` is not visible outside of this crate. This PR would fix the issue by exporting it.
=> Export StorageSlot

crates/revm/src/evm_impl.rs, crates/revm/src/instructions/host.rs
In `create_inner`, `let b = Bytes::new();` was always returned, without ever being touched. The create calls should return the deployed contract bytecode.
This might relate to https://github.com/bluealloy/revm/issues/269 ?
=> revm: Return `bytes` in Create calls

crates/revm/Cargo.toml, crates/revm/src/db.rs, crates/revm/src/evm_impl.rs, crates/revm/src/models.rs
Depends on/incorporates #256
Ethereumjs has the ability to disable balance checks. When this toggle is on and an account does not have sufficient balance to complete a transaction, the transaction will still be completed and the balance set to `0` (zero).
=> feat: allow disabling of balance checks

Cargo.lock, crates/interpreter/Cargo.toml, crates/interpreter/src/bits.rs, crates/interpreter/src/instructions/i256.rs, crates/interpreter/src/lib.rs
Adds `arbitrary` and `proptest/arbitrary` to `B160` `B256` and `I256` to the `revm_interpreter` branch
=> Add `arbitrary` and `proptest/arbitrary` to `B160` `B256` and `I256`

Cargo.lock, crates/interpreter/Cargo.toml, crates/interpreter/src/bits.rs
Also bumps `proptest-derive` since it was wrongly set to a previous version
=> chore(interpreter): enable `proptest` with `arbitrary` feature

crates/revm/Cargo.toml, crates/revm/src/lib.rs
Closes #327.
Marks the `with-serde` feature as deprecated, pointing out that it has been renamed to `serde.`
=> `revm`: mark `with-serde` feature as deprecated

crates/primitives/src/lib.rs
Issue: #344 
`EVM::transact` returns `ResultAndState` which contains `type State = HashMap<B160, Account>;`
State is internal to `revm` and requires `hashbrown` to form the type in user-called code.
Likewise, `Account` contains:
```
pub storage: HashMap<U256, StorageSlot>,
```
By exposing `HashMap` in primitives it provides user the ability to use this type independently and insulates them from changes to the type.
=> expose hashbrown::HashMap in primitives

crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
The EVM allows you to call the `revert` opcode with an error message, which needs to be returned as the return value.
Additionally, I added the logs that are collected up to the point `revert` was called. This allows debugging tools built on top of `revm` without adding additional cost - as we're just bubbling up the data.
=> improvement: add logs & return value to revert

crates/interpreter/src/instructions/host.rs
When using the "no_gas_measuring" feature, I encountered various underflow panics which seem to stem from calls to the "erase_cost" method which should not be called in this case. 
This PR should fix that by wrapping those calls in an `if crate::USE_GAS` block analogous to other parts of the code.
=> fix: underflow panic when using "no_gas_measuring" feature

crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/control.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/instructions/memory.rs, crates/interpreter/src/instructions/system.rs, crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
=> feat: Different OutOfGas Error types

crates/revm/src/evm_impl.rs
The prelimary balance (LackOfFundForGasLimit) check revm does is different to Geth
revm checks: `effective_price * gas + value >= caller_balance` 
https://github.com/bluealloy/revm/blob/2e4e800b23b817a2be19f10313600f3d5dfacdf1/crates/revm/src/evm_impl.rs#L115
geth checks: `gas_fee_cap * gas + value >= caller_balance`. 
https://github.com/ethereum/go-ethereum/blob/3a79a99f804c4bd2002fe52768c965c4be8106ea/core/state_transition.go#L221
This change should align the revm check with Geth.
=> Use gas price in place of effective gas price for initial balance check

crates/primitives/src/db/components/block_hash.rs, crates/primitives/src/db/components/state.rs
Improves #360 & #361 by removing necessity for `std` feature
=> improvement: use alloc & core for Arc impl

crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
=> chore: rename Then to Than

README.md, bins/revme/src/statetest/models/spec.rs, bins/revme/src/statetest/runner.rs, crates/interpreter/src/gas/calc.rs, crates/interpreter/src/gas/constants.rs, crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/opcode.rs, crates/interpreter/src/instructions/stack.rs, crates/interpreter/src/interpreter.rs, crates/primitives/src/bytecode.rs, crates/primitives/src/bytecode/jump_table.rs, crates/primitives/src/env.rs, crates/primitives/src/lib.rs, crates/primitives/src/log.rs, crates/primitives/src/precompile.rs, crates/primitives/src/result.rs, crates/primitives/src/specification.rs, crates/primitives/src/utilities.rs, crates/revm/src/evm.rs, crates/revm/src/evm_impl.rs, crates/revm/src/inspector/gas.rs, crates/revm/src/journaled_state.rs, crates/revm/src/lib.rs
=> feat(Shanghai): All EIPs: push0, warm coinbase, limit/measure initcode

Cargo.lock, crates/primitives/Cargo.toml, crates/primitives/src/bits.rs
REVM 3 does not use `primitive_types` anymore. Numerical types compatibility is already provided by `ruint` `primitive_types` feature. This PR adds type conversion between the hashes types (i.e. `B160` and `B256`) and their counterparts in `primitive_types`.
=> Add B160/B256 From primitive_types traits

crates/primitives/src/db/components.rs
In #363 I added it for `DatabaseComponents` and not for `DatabaseComponentError` after incorporating suggestions
=> improvement: derive Debug for DatabaseComponentError

crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
Implements missing nonce checks. 
Using a feature flag to disable the nonce checks was discussed in telegram but I noticed that the `nonce` parameter in the `TxEnv` struct was optional so I've put the check behind that. If this isn't what the Optional nonce was for then I can put it behind a feature flag, just let me know :D.
Matched to Geth: https://github.com/ethereum/go-ethereum/blob/fe01a2f63b8591d8226742726d8d6aaad4cd981e/core/state_transition.go#L240
=> impl NonceTooHigh/ NonceTooLow checks

crates/primitives/src/bits.rs
converting hash types to u256 is _incredibly_ annoying.
ethereum-types solved this via a BigendianHash trait
https://github.com/paritytech/parity-common/blob/27b17c0d5d32ebf384dd4b535d9045598904519d/ethereum-types/src/hash.rs#L18
however, I really would like to have From impls instead, so you don't have to do.
`U256::from_be_bytes(b256.0)` or `U256::from_be_bytes(b256.to_fixed_bytes())`
=> feat: add b256<->u256 from impls

crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs, crates/revm/src/inspector/gas.rs
=> feat: Add check for chainID

crates/precompile/src/lib.rs
this adds back a conversion from revm 2.0 but flips it to `from(primitive::SpecId) -> precompile::SpecId`
=> chore: add primitive SpecId to precompile SpecId conversion

crates/revm/src/evm_impl.rs, crates/revm/src/inspector.rs, crates/revm/src/inspector/customprinter.rs
adds back the addresses to the selfdestruct hook.
=> feat: add contract+target to selfdestruct hook

crates/interpreter/src/instruction_result.rs, crates/primitives/src/result.rs
From [EIP 3860](https://eips.ethereum.org/EIPS/eip-3860#rules):
> If length of initcode to CREATE or CREATE2 instructions exceeds MAX_INITCODE_SIZE, instruction execution exceptionally aborts (as if it runs out of gas).
=> fix(interpreter): halt on `CreateInitcodeSizeLimit`

crates/revm/src/db/in_memory_db.rs
If the account already existed, its state would get reset to `Touched` after any change.
This is not ideal for accounts which had their storage cleared.
Preserve existing account state if any.
=> fix(db): preserve existing account state

crates/primitives/src/lib.rs
Isn't this supposed to be the last 20 bytes of the hash of the public key?
I might be wrong tho.
=> Comment Fix

crates/revm/src/db/ethersdb.rs
Changing `Option<u64>` to `Option<BlockId>` will allow us to pass more flexible parameters like `BlockId::Number(BlockNumber::Latest)` instead of always `BlockNumber::Number`.
=> Improve EthersDB::new

crates/interpreter/src/instructions/opcode.rs
Foundry needs this particular function & macro to gather information about bytecode on certain parts of the `evm` crate. This adds back a few constants/structs that are strictly necessary to use the function in the same place it was before.
The structure of the project has changed a bit after this was removed, so happy to move stuff around!
=> [Interpreter]: Add back `spec_gas_opcode`

.github/workflows/ci.yml, bins/revme/Cargo.toml, crates/interpreter/src/host.rs, crates/interpreter/src/host/dummy_host.rs, crates/precompile/src/lib.rs, crates/precompile/src/secp256k1.rs, crates/revm/src/evm_impl.rs
Make k256 compile.
closes: #449
=> fix: k256 compile error

CHANGELOG.md, Cargo.lock, bins/revm-test/Cargo.toml, bins/revme/Cargo.toml, crates/interpreter/CHANGELOG.md, crates/interpreter/Cargo.toml, crates/precompile/CHANGELOG.md, crates/precompile/Cargo.toml, crates/primitives/CHANGELOG.md, crates/primitives/Cargo.toml, crates/revm/Cargo.toml
=> Release v22, revm v3.1.1

crates/revm/src/journaled_state.rs
The contract account might have been touched before the creation.
e.g. The contract address is deterministic and it was touched prior to creation.
This causes a bug during the revert of the journal state here and the account is marked untouched.
https://github.com/bluealloy/revm/blob/fcbd2d93a0c31d5cfbfdbc8d5e7c6a49142ba90d/crates/revm/src/journaled_state.rs#L283
https://etherscan.io/tx/0xa50b1bd15b43783fbdd69d39c57cd30b339b4583274595f404ab0ae2b24300e6
Check if the account was already touched on contract creation before pushing the touched journal entry.
Technically, this bug is impossible before Constantinople/Petersburg hard fork and introduction of `CREATE2` since there is no way to know the contract address beforehand.
=> fix: touched account on creation

crates/revm/src/journaled_state.rs
When the selfdestruct's recepient is the account that's being destroyed, the balance is lost as shown in the code below.
https://github.com/bluealloy/revm/blob/c594d1cf17d7f828d0ba2233acb682b859a7f9a6/crates/revm/src/journaled_state.rs#L380-L384
The revert of selfdestruct journal entry doesn't handle this edge case.
Fix the revert of the selfdestruct journaled entry to handle this case. Do not subtract the value from the target balance if the balance was lost.
https://goerli.etherscan.io/tx/0x904391de6af08cd62e80392dc14249f7cc24e53d45b763139ee8b7acb1e56c3e
=> fix: revert of selfdestruct with lost balance

crates/primitives/src/state.rs
Improved code readability by correcting typos in the commenting for the ```is_not_existing``` member of the ```Account``` struct.
=> Fix typo in primitives/src/state.rs

Cargo.lock, crates/primitives/Cargo.toml, crates/primitives/src/state.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/evm_impl.rs, crates/revm/src/journaled_state.rs
Added `AccountStatus` inside Journal state that is `bitflags`struct, it makes account smaller and makes setting flag more straightforward.
Simplified a little account creating, I will do another PR on that part that will remove some unnecessary access to hashmap.
=> feat: Introduce account status as bitflag inside JournalState

crates/primitives/src/state.rs, crates/revm/src/evm_impl.rs, crates/revm/src/inspector.rs, crates/revm/src/inspector/customprinter.rs, crates/revm/src/inspector/gas.rs, crates/revm/src/inspector/tracer_eip3155.rs
Move all inspector call from `call_inner` and `create_inner` to one place inside `Host` trait
=> chore: Bundle inspector crate/call calls

crates/interpreter/src/host.rs, crates/interpreter/src/host/dummy_host.rs, crates/interpreter/src/interpreter.rs, crates/revm/src/evm_impl.rs, crates/revm/src/inspector.rs, crates/revm/src/inspector/customprinter.rs, crates/revm/src/inspector/gas.rs, crates/revm/src/inspector/tracer_eip3155.rs
Remove `is_static` from inspector as this field can be found in the interpreter.
move run of interpreter from `call_inner` and `create_inner` to standalone function.
=> chore: refactor interpreter run and remove inspector static flag

crates/revm/src/db/in_memory_db.rs
add a few cachdb docs
also move the Cachdb impls under the struct def
=> docs: add some CacheDB docs

bins/revm-test/Cargo.toml, bins/revm-test/src/bin/analysis.rs, bins/revm-test/src/bin/transfer.rs, crates/interpreter/src/gas/calc.rs, crates/primitives/src/constants.rs, crates/primitives/src/env.rs, crates/primitives/src/lib.rs, crates/primitives/src/result.rs, crates/primitives/src/utilities.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/evm_impl.rs, crates/revm/src/journaled_state.rs
There is a lot of refactor of initial EVM call
Added a bench for the simple transfer of value transaction, it got slightly faster from 700ns to 500ns but that is like ~5-10min saved for 2trilion of eth transactions, so it does not have a big impact.
Most of changes are internal, only external change is that previously only touched accounts (touch means something is done on them) would be returned but now all account from the journal state is returned.
=> feat: separate initial checks

crates/revm/src/inspector/tracer_eip3155.rs
The output from the eip-3155 tracer returns `gasUser` rather than `gasUsed` ([spec](https://eips.ethereum.org/EIPS/eip-3155))
current:
```
"{\"output\":\"b\\\"\\\"\",\"gasUser\":\"0xd772\"}"
```
spec:
```
"{\"output\":\"b\\\"\\\"\",\"gasUsed\":\"0xd772\"}"
```
=> fix: typo in eip-3155 output

crates/interpreter/src/instructions/host.rs, crates/revm/src/evm_impl.rs
Set initcode limit from config, it is `2* env.cfg.limit_contract_code_size`
=> feat: Add initcode limit to be double of bytecode limit

crates/interpreter/src/instructions/opcode.rs
this mirrors geth's naming 
https://github.com/ethereum/go-ethereum/blob/73697529994e14996b7740730481e926d5ec3e40/core/vm/opcodes.go#L261-L261
=> fix: replace SHA3 with KECCAK256 opcode name

Cargo.lock, bins/revme/src/statetest/models/spec.rs, crates/interpreter/src/instructions.rs, crates/interpreter/src/instructions/memory.rs, crates/interpreter/src/instructions/opcode.rs, crates/interpreter/src/interpreter/memory.rs, crates/primitives/src/specification.rs
Started working on this. Still needs work. 
Will Close #523
=> feat(cancun): EIP-5656: MCOPY - Memory copying instruction

bins/revme/src/statetest/merkle_trie.rs, crates/primitives/src/bits.rs, crates/revm/src/evm_impl.rs, crates/revm/src/journaled_state.rs
Fix clippy and fmt on newest rust compiler
=> chore: clippy and fmt

crates/revm/src/inspector/tracer_eip3155.rs
The EIP-3155 tracer omits display of CREATE opcodes. This arises from use of
the default implementation of the `fn create()` method of the `Inspector` trait.
Add a custom implementation for the `create` method that mirrors the default, but includes
a log.
```rs
self.print_log_line(data.journaled_state.depth());
```
This results in the the inclusion of the CREATE opcode in the trace.
Transaction with index 185 in block 17190873 is an example. The 84th opcode should be
CREATE, but this is omitted. However, CREATE has been executed as the subsequent
opcodes proceed as expected, including an increase
in call depth, correct gas accounting and a cleared stack.
REVM trace, erroneously showing an increase in context depth following a PUSH1.
```json …
```
=> fix(revm): include CREATE/CREATE2 in EIP3155 inspector

crates/revm/src/inspector/tracer_eip3155.rs
Additional RETURN when leaving the subcontext of a CREATE opcode.
The additional RETURN does not disrupt the logic of the subsequent opcodes and so appears
to be confined to the logging apparatus.
Skip the `create_end()` component of the tracer.
```rs
self.skip = true;
```
This results in the omission of the extraneous RETURN from the trace.
To reproduce, the CREATE opcode needs to be logged. See:
- #562.
Transaction with index 185 in block 17190873 is an example.
This is a visual summary showing what the transaction does (created by filtering/parsing the 3155 trace)
The tranaction creates 5 contracts as follows. The issue is on the return from the CREATE context,
as noted with asterisks
```
Function 0x8467be0d
Deploy contract (CREATE)
Contract (CALL) using code and storage at created …
```
=> fix(revm): extra return in EIP3155 inspector

crates/revm/src/inspector/tracer_eip3155.rs
EIP-3155 tracer output section included debug (`?`) artefacts
- Use non-debug newline-delineated JSON representation.
- Include 0x-prefixed hex encoding for `output` field.
Before:
```sh
{"pc":379,"op":253,"gas":"0x66048","gasCost":"0x0","memSize":1024,"stack":["0xda218207","0x88","0x80","0x1c0","0x200","0x7a250d5630b4cf539739df2c5dacb4c659f2488d","0x0","0x240","0x0","0x2a0","0x631","0x80","0x240","0x200","0x7a250d5630b4cf539739df2c5dacb4c659f2488d","0x0","0x3","0x0","0x0","0x0","0x64","0x300"],"depth":1,"opName":"REVERT"}
"{\"output\":\"b\\\"\\\\x08\\\\xc3y\\\\xa0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0 \\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\ …
```
=> fix(revm): EIP-3155 tracer tx output without debug artefact

crates/interpreter/src/instructions/memory.rs
`Memory::copy` argument order is `dst, src, len`, while it is being called with `src, dst, len`.
=> fix(interpreter): mcopy call order

crates/revm/src/journaled_state.rs
Journaled values (Value that we revert to) should have been the previous value and not the new value
Introduced in initial EIP here: https://github.com/bluealloy/revm/pull/546
found when running eth tests. Tests will be added in ci in next commit.
@tynes fyi
=> fix(transient_storage): set previous value in journal

.github/workflows/ethereum-tests.yml, Cargo.lock, crates/interpreter/src/instructions/memory.rs
`memory_resize` resize macro was not correctly used, inputs of it are `offset` and `length` but in code we had `src` and `resized` value of `max(src,dst)+len` that was not correct.
Added eth test for MCOPY and TransientStorage to ci. Found this problem while running those tests.
Bug was introduced in initial impl: https://github.com/bluealloy/revm/pull/528
@0xJepsen @DaniPopes fyi
=> fix(mcopy): memory expansion and add eth tests to ci

crates/interpreter/src/gas.rs
Super minor, but given the amount of times this gets called during execution it makes sense to optimize cpu cycles.
This removes the unnecessary `overflow` var and the branch in `if overflow || ` by using `saturating_add`. This seems fine since `all_used_gas` is not updated unless under the limit
=> remove unneccesary var and if branch

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/changes.rs, crates/revm/src/db/states/transition_state.rs
Pre-allocate `Vec` with capacity where applicable. In some places, the pre-allocation is pessimistic and assumes that _all_ accounts have been changed (appropriate comments were added).
=> perf: pre-allocate inner bundle state

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/transition_state.rs
`TransitionState::with_capacity` method name is misleading since `with_capacity` is usually used for pre-allocating memory.
Change method name to `TransitionState::single`
=> chore: `TransitionState::with_capacity` -> `TransitionState::single`

crates/primitives/src/db.rs, crates/primitives/src/state.rs, crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/plain_account.rs, crates/revm/src/db/states/transition_account.rs, crates/revm/src/journaled_state.rs
Rename `original` storage slot to `previous_or_original_value`
Check if storage is changed, remove it if it is the same.
Added tests for bundle revert
=> chore: Revert test, not change storage check , renaming of original slot value

crates/revm/src/evm_impl.rs
The caller is already loaded inside `journaled_state` but if `env.tx.caller` gets changed this would panic on unwrap as it is happening inside the foundry.
So we are now loading an account is a safe way to mitigate this. This will call `Database` to fetch account
=> chore: Load caller in finalization fn

crates/primitives/src/state.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/inspector.rs, crates/revm/src/lib.rs
Some items, like `to_precompile_id`, aren't exported at the crate level, even if their visibility is `pub`.
=> chore: export some `unreachable_pub` items

crates/revm/src/evm_impl.rs
If the Inspector shortcircuits the call of `call/create`, functions for call end `call_end/create_end` were not called, these calls were expected by the foundry and it broke a few things.
=> fix(inspector): call call_end/create_end when inspector shortcircuits calls

crates/revm/src/db/states/state.rs
Minor stylistic suggestion to use `get_or_insert` instead.
=> chore: get or insert bundle state

crates/interpreter/src/instructions/host.rs, crates/primitives/src/constants.rs, crates/revm/src/db/states/state.rs, crates/revm/src/db/states/state_builder.rs
Allow setting block hash overrides inside `StateBuilder` and cache last `256` block hashes.
=> feat(state): Block hash cache and overrides

crates/revm/src/db/states/cache_account.rs, crates/revm/src/db/states/state.rs
Preloaded bundle was added to the builder but was not used inside state.
Note that when the account is loaded both account info and storage are transferred from the bundle to the cache. So we don't have a fetch of storage for the preloaded bundle. While the contract is behaving the same as the account.
=> feat(state): Use preloaded bundle inside state

crates/primitives/src/env.rs
For future proofing updates make it non_exhaustive.
There is `Default` implementation to help with struct creating.
=> chore: mark CfgEnv as non_exhaustive

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/state.rs
Adds a test checking that the account and storage changes that were changed within a block and returned to its previous value are collapsed.
=> test(state): bundle reverts collapse

crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/reverts.rs
On revert check if account info was changed or not.
Notices here: https://github.com/bluealloy/revm/pull/627/files/94c98a615fd35189c4b20a7ca82b44c2bf885dc9#diff-549cde144deee3e0083097545a0eff627800d0ea38bcd720f69477d3136a4a2bR664
Where info transition from Loaded to DestroyedChanged would result the same info, but we would save redundant `RevertTo` of previous account.
=> bug(state): remove redundant info revert on destruct

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/changes.rs, crates/revm/src/db/states/reverts.rs
Returns more information for storage. If storage previous values are known we would have `RevertToSlot::Some` while if the first selfdestruct happened we wouldn't know the previous value inside revm and would have `RevertToSlot::Destroyed` and need to check with whipped database storage if there is one, if not ZERO should be used in revert.
Change inside reth to accompany this: https://github.com/paradigmxyz/reth/commit/2c62da3c8bc35fe6de499baa0b4e76b2c42af576
=> fix(state): return RevertToSlot struct with more info

crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs
Split off from #582
And macros style changes.
Improves readability. MSRV for this feature is 1.65 but I see it's already present in `revm`.
=> chore(interpreter): use `let else`

crates/interpreter/src/interpreter/contract.rs, crates/revm/src/evm_impl.rs
Caches the bytecode on `Contract` to only call `hash_slow` once during `Contract`'s creation.
Should speed up the coverage interpreter in foundry. cc @rakita
=> feat(`interpreter`): add hash to bytecode

crates/revm/src/db/states/bundle_state.rs
Check if storage revert is empty before adding it to the storage set.
=> fix(state): check if storage revert is empty

bins/revme/src/statetest/runner.rs, crates/revm/src/evm.rs, crates/revm/src/evm_impl.rs, documentation/src/crates/revm/evm.md
Hi! I tried to give a shot to https://github.com/bluealloy/revm/issues/432 in this PR. I hope to have understood and addressed the problem indicated by the issue.
=> Refactor: Split transaction pre verification to separate function

crates/revm/src/db/states/bundle_account.rs
TODO was right, it was invalid.
The storage that we should have used was the present storage of the bundle account. As this is transition to `DestroyedAgain` updated_storage would always be empty.
=> fix(state): Revert from DestroyedChanged to DestroyedAgain

crates/interpreter/src/instructions/bitwise.rs, crates/interpreter/src/instructions/i256.rs
Split off from #582
Summary:
- `i256_sign`:
- is split into the two possible variants as before (with the const bool), so we can use it with an immutable reference, avoiding copies in `i256_cmp` (see `slt`, `sgt` impls). `i256_sign_compl` gets optimized away like `i256_sign::<true>` before
- by sorting  `Sign`  variants we can leverage derived `Eq, Ord` impls, which are can be further optimized by the compiler. Also, by using `-1, 0, 1` it will be the exact same `cmp::Ordering` and the `signum` function result, which helps in the sign function (where we transmute `num != 0` directly to `Sign`)
- `i256_div`: if condition generates better code than a fully exhaustive match (branchless vs multiple branches). I don't know why, I would assume the two to be identical ... godbolt: …
=> perf(interpreter): improve i256 instructions

crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/state.rs
Previously this was not the case and updating storage every time was a bug.
If both this and other bundle are presents. We iterate over `other` reverts to find if it has wipe flag, if it is true, we take the bundle state of `this` and expand revert with this state (If there are slots missing).
We nullify `other` wipe flag if `this` wipe flag is present. 
And replace the state if `other` wipe flag is present, else we just extend `this` plain state.
=> feat(state): Make Bundle extend wipe aware

crates/revm/src/db/states/bundle_state.rs
Filter out the empty bytecode from returned output of bundle state.
=> chore: filter out empty bytecode from bundle

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/state.rs
Add a flag to `State::merge_transitions` that allows merging transitions to `BundleState` without reverts.
=> feat(state): add a flag allowing transition merge without reverts

crates/revm/src/db/states/bundle_account.rs
Introduced with removal of this line: https://github.com/bluealloy/revm/commit/aee1d1c657673a48f5293a68a7023ee2fa513956#diff-c5993d59b61489bc36107b91d05b568e09d8213c9a03087d68343847461d39c5L235
We should have set the destroyed account to `None`
=> fix(state): Regresion, remove present info on selfdestruct

crates/revm/src/db/states/account_status.rs, crates/revm/src/db/states/bundle_state.rs
Retail destroyed account status when extending bundle state.
This handles extended account status in a more precise way.
=> fix(state): retain destroyed account status on bundle extend

Cargo.lock, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/bytecode.rs, crates/primitives/src/lib.rs, crates/revm/Cargo.toml
Removed to_binary, which was used only in a debug display.
Replaced once_cell with lazy_static. The no-std build of once_cell did not support the Sync version of OnceCell, that was needed when creating static variables. On the other hand, lazy_static is the complete solution for lazyly initialized (Sync) static variables, and is no-std.
With this changes, revm builds on a no-std platform.
=> Removed the last dependencies breaking no-std build.

crates/primitives/src/bytecode.rs
The method was outdated and unused so it should be removed
=> chore: remove unused new_raw_with_hash

crates/revm/src/db/states/bundle_state.rs
This PR is for closing issue https://github.com/bluealloy/revm/issues/644
Add `BundleBuilder` and a set of member methods to collect initialization information for `BundleState` struct.
The builder enables chaining of method calls.
Add 2 more test cases.
=> BundleBuilder for BundleState initialization

crates/revm/Cargo.toml, crates/revm/src/db/states.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/changes.rs, crates/revm/src/db/states/reverts.rs, crates/revm/src/db/states/state.rs
The original function `detach_lower_part_reverts ` didn't make sense to return `Self` as the returned Bundle state had just reverts. So remove it and make explicit function that handles return of the reverts.
Additionally added structures to the long storage types that we had inside `PlainStateRevert` and `PlainStateChangeset` this increased the readability of types.
This addresses few comments from this PR: https://github.com/bluealloy/revm/pull/663
=> feat(state): take N reverts from BundleState, struct refactor

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/cache_account.rs, crates/revm/src/db/states/reverts.rs, crates/revm/src/db/states/state.rs
`apply_block_substate_and_create_reverts` is renamed to `apply_transitions_and_create_reverts` to better reflect what is going on
=> chore: nits and renamings

crates/revm/src/db/states/state.rs, crates/revm/src/db/states/state_builder.rs
Make the State database more generic and introduce `StateDBBox` as an alternative to the current type.
=> chore(state): Make Database more generic.

bins/revme/src/statetest/runner.rs, crates/revm/src/db/states/state.rs, crates/revm/src/db/states/state_builder.rs
In general output state and creating of revert is better to be something to be enabled, and not disabled.
=> feat(StateBuilder): switch builder option from without_bundle to with_bundle

crates/interpreter/src/gas.rs, crates/primitives/src/db.rs, crates/revm/src/evm.rs, crates/revm/src/evm_impl.rs, crates/revm/src/inspector/noop.rs
There is no point in having a separate type for `dyn Trait` when there is one for `impl Trait` already.
=> chore: deprecate `RefDBWrapper`

examples/fork_ref_transact.rs
fix example compile error
```shell
> cargo run -p revm --features ethersdb --example fork_ref_transact
error[E0277]: the trait bound `ToUintError<revm::revm_primitives::ruint::Uint<256, 4>>: std::error::Error` is not satisfied
--> crates/revm/../../examples/fork_ref_transact.rs:83:42
|
83 |     evm.env.tx.value = rU256::try_from(0)?;
|                                          ^ the trait `std::error::Error` is not implemented for `ToUintError<revm::revm_primitives::ruint::Uint<256, 4>>`
|
= help: the following other types implement trait `FromResidual<R>`:
<Result<T, F> as FromResidual<Yeet<E>>>
<Result<T, F> as FromResidual<Result<Infallible, E>>>
= note: required for `anyhow::Error` to implement `From<ToUintError<revm::revm_primitives::ruint::Uint<256, 4>>>`
= note: required for …
```
=> fix example compile error

crates/revm/src/db.rs, crates/revm/src/db/states.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/state.rs, crates/revm/src/db/states/state_builder.rs, crates/revm/src/lib.rs
Added `OriginalValueKnown` to replace a bool when taking the state.
Added a few `with_database..` options for `StateBuilder`.
State now implements `fn builder` so we can use `State::builder()... .build()` pattern  and remove `StateBuilder` mentions
=> feat(state): Nits, builder option and OriginalValueKnown flags

crates/interpreter/src/gas/calc.rs
this makes it easier to call with different byte types
=> chore: accept byte slice as input

bins/revme/src/statetest/runner.rs, crates/interpreter/src/instructions/host_env.rs, crates/primitives/src/env.rs
Closes #671. Let me know if I am missing something from this issue!
=> `CfgEnv.chain_id` should be `u64`

bins/revme/src/statetest/runner.rs, crates/revm/src/db/states/state_builder.rs
Follow-up to #687, see https://github.com/bluealloy/revm/pull/687#discussion_r1316523492
=> chore: make `impl Default for StateBuilder` generic

crates/interpreter/src/gas.rs, crates/primitives/src/db.rs, crates/revm/src/db/emptydb.rs, crates/revm/src/db/ethersdb.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/db/states/state.rs
And some code cleanup and docs
=> chore: implement `Default` for other databases

.github/workflows/ethereum-tests.yml
In debug mode the tests are checking for additional things like unsigned int arithmetic overflows. In release mode they are checking for things like proper stack utilization (ex. in release mode the tests are running with the default thread stack limit).
=> Run the Ethereum tests both in debug and release mode

crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/changes.rs
If we prune `Reverts` the wiped flag would be lost so we should return it inside `StorageChangeSet`
=> feat: return wiped inside storage changeset

bins/revme/src/statetest/runner.rs, crates/interpreter/src/instructions/host.rs, crates/revm/src/evm_impl.rs
These functions are used for keeping the stack memory clean on the host recursive code paths. EVM supports up to 1024 levels of recursion, so if one is not careful with the stack memory allocations, the stack memory can blow up.
Benchmarks show dramatic stack memory improvements when ont inlining these functions. A recursive bomb uses around 1.1MB of stack when these functions are not inlined. If inlined the recursive bombs blow up the stack.
Fixes #589
=> Never inline the prepare functions

documentation/src/SUMMARY.md, documentation/src/crates/interpreter.md, documentation/src/crates/precompile.md, documentation/src/crates/revm/evm_impl.md, documentation/src/crates/revm/host_trait.md, documentation/src/crates/revm/journaled_state.md, documentation/src/introduction.md
Was reading the docs seeing what can be improved (and what's out of date) and spotted a bunch of smol things to improve.
The idea here is to slowly start improving the `revm` docs bit by bit until it becomes an amazing resource not only to learn about how to use `revm`, but to learn about the EVM and related EIP themselves and level up in the meanwhile. I'll probably also be submitting code docs as well over time.
As always, feel free to nit on this 😄
=> chore(docs): minor improvements, create separate page for `Host` trait

crates/revm/src/db/states/state.rs
These docs were added after encountering a panic in reth: https://github.com/paradigmxyz/reth/pull/4561
=> docs: add warning on panic conditions in take_bundle

.github/workflows/ci.yml, Cargo.lock, crates/revm/Cargo.toml, crates/revm/src/db.rs, crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/cache.rs, crates/revm/src/db/states/changes.rs, crates/revm/src/db/states/reverts.rs, crates/revm/src/db/states/state.rs, crates/revm/src/db/states/transition_state.rs
Remove state sorting, it can be a footgun if other formats for keys are used, and it is easy to sort if needed outside of revm.
As we removed rayon we can make state `no_std`.
Added `cargo check --target riscv32imac-unknown-none-elf --no-default-features` to test for no_std compatibility in CI.
=> feat: Remove state sorting, no_std ci,remove rayon

crates/primitives/src/bits.rs
error: lint `clippy::incorrect_clone_impl_on_copy_type` has been renamed to `clippy::non_canonical_clone_impl`
=> chore: clippy incorrect_clone_impl_on_copy_type

crates/primitives/src/result.rs
having non-exhaustive on an error forces this clippy error:
```
126 | pub enum EVMError<DBError> {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^
= note: the matched value is of type `EVMError<T>`
= note: `EVMError<T>` is marked as non-exhaustive, so a wildcard `_` is necessary to match exhaustively
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
|
192 ~             EVMError::Database(err) => err.into(),
193 ~             _ => todo!(),
|
```
this forces a wildcard handling which can introduce bugs if a new evmerror variant is added
=> chore: rm nonexhaustive for error

crates/revm/src/evm.rs, crates/revm/src/lib.rs
ref https://github.com/paradigmxyz/reth/issues/4671
Hive tests discovered that the cancun precompile was not being set even though the input `SpecId` was `SpecId::CANCUN`. It was instead being mapped to `revm_precompile::SpecId::BERLIN`.
This maps `CANCUN` to `CANCUN`, causing the hive tests to pass.
=> fix: use CANCUN precompile id for CANCUN SpecId

crates/interpreter/src/instructions/control.rs
Bug was introduced a few commits before on refactor and at would override `InstructionReturn` even if it was an exception.
=> fix: dont override instruction result

bins/revme/src/statetest/runner.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/lib.rs, crates/primitives/src/constants.rs, crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
Added failing condition to `Env`, now we pass all tests related to blobs
=> fix(eip4844): Pass eth tests, additional conditions added.

crates/primitives/src/env.rs, crates/primitives/src/result.rs
Closes #594 
I added some docs to the `InvalidTransaction` enum.
I just excluded 3 variants because their meaning are obvious:
- `NonceTooHigh`
- `NonceTooLow`
- `InvalidChainId`
I also renamed the first variant: `PriorityFeeGreaterThanMaxFee` that previously was `GasMaxFeeGreaterThanPriorityFee `.
I think it's better named like this as that error arises when the `priority_fee` is actually greater than the `max_fee` and not the contrary.
Let me know WDYT!
=> Document when InvalidTransaction errors are thrown

crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
should close #685 
I have used enum name as header since env names such as `BlockEnv`, `CfgEnv` & `Env` are already used as type, let me know if prefer EnvError over this and I can quickly make that change.
=> chore: error type for block header

crates/revm/src/evm_impl.rs, crates/revm/src/journaled_state.rs
Closes #524. Reading the [EIP](https://eips.ethereum.org/EIPS/eip-6780), when the contract is not created in the same tx, `SELFDESTRUCT` simply becomes a transfer, while keeping the gas cost of the opcode. As such, I tried to modify only the `JournaledState` to reflect that.
=>   EIP-6780: SELFDESTRUCT only in same transaction

Cargo.lock, crates/interpreter/Cargo.toml, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/env.rs, crates/primitives/src/lib.rs, crates/revm/Cargo.toml
=> feat: add "kzg" as a separate feature

crates/primitives/src/env.rs
Fixes the `disable_balance_check` option by setting the sender balance to the balance to be spent.
=> fix: balance check disabled

crates/interpreter/src/gas/calc.rs, crates/revm/src/evm_impl.rs, crates/revm/src/journaled_state.rs, documentation/src/crates/revm/journaled_state.md
[EIP-2919](https://eips.ethereum.org/EIPS/eip-2929) does not make any reference to "hot". It only says "warm".
There's no need to introduce another term to refer to the same concept.
There are other references on the Internet, such as [EVM codes](https://www.evm.codes/about#accesssets), which also use only the "warm" terminology.
=> refactor: say "warm" instead of "hot"

.github/workflows/book.yml, .github/workflows/ci.yml, .github/workflows/ethereum-tests.yml
The goal is to ensure that only a single job or workflow using the same concurrency group will run at a time.
E.g. if someone force pushes, CI won't run twice. The first workflow run will be stopped.
=> ci: concurrency for github actions

Cargo.lock, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml
Bump to unofficial c-kzg lib.
c-kzg 0.1.1 is based on fbef59a3f9e8fa998bdb5069d212daf83d586aa5 commit from [ethereum/c-kzg-4844](https://github.com/ethereum/c-kzg-4844) repo.
It does not support `minimal-spec` feature.
=> chore: bump c-kzg to create lib

CHANGELOG.md, Cargo.lock, bins/revme/Cargo.toml, crates/interpreter/CHANGELOG.md, crates/interpreter/Cargo.toml, crates/precompile/CHANGELOG.md, crates/precompile/Cargo.toml, crates/primitives/CHANGELOG.md, crates/primitives/Cargo.toml, crates/revm/CHANGELOG.md, crates/revm/Cargo.toml
Preparation for v25 tag, and `revm` v3.4.0 release.
=> release: tag v25, revm v3.4.0

crates/primitives/src/env.rs, crates/primitives/src/utilities.rs
This uses `u128` for `calc_blob_gasprice` and `fake_exponential`. This solves an issue where an `excess_blob_gas` value of `161087488` in hive tests should produce a value over 128 bits, but did not because of the following cast:
https://github.com/bluealloy/revm/blob/ef2f21b6e2b507c18b7edcdd005c5aaddb63df0f/crates/primitives/src/utilities.rs#L82
=> fix: use u128 for calc_blob_gasprice

crates/revm/src/db/states/cache_account.rs, crates/revm/src/db/states/state.rs
Thought this would be good to add after debugging https://github.com/paradigmxyz/reth/pull/4840. This documents the same assumptions in `CacheAccount::increment_balance`, but in `State::increment_balances` as well. A `debug_assert` is added in `increment_balance`, to cause it to panic if the assumption is violated in tests.
=> docs: document non-zero amounts in State::increment_balances

crates/primitives/src/precompile.rs
Implements the `std::error::Error` and `core::fmt::Display` traits for the `PrecompileError` enum.
=> chore(primitives): Precompile Error Display + Error Trait Implementations

crates/primitives/src/utilities.rs, crates/revm/src/evm_impl.rs, documentation/src/crates/primitives/utils.md
Since `create` and `create2_address` are used internally and external implementations can just use the methods directly on the re-exported `Address` type, this PR removes the utility methods and inlines the upstream alloy creation function calls.
=> fix(primitives): Use Upstream Alloy Create Implementations

crates/primitives/src/state.rs
Cleans up state types and references with some added documentation.
=> chore(primitives): State Cleanup

crates/primitives/src/lib.rs, crates/primitives/src/result.rs
Addresses #740 
Implements `std::error::Error + std::fmt::Display` for `InvalidTransaction` and `InvalidHeader`. If there are others that should be implemented, happy to do in this pr cc @DaniPopes
=> fix(primitives): Error Primitive Display + Error Implementations

crates/primitives/src/db/components/state.rs
Removes a dead `exists` method on the `StateRef` trait and adds spacing for easier legibility.
=> chore(primitives): Remove Dead StateRef Method

crates/primitives/src/env.rs
Cleans up and improves the doc comments on the `OptimismFields` object to give more context to end users.
=> chore(primitives): OptimismFields Docs Cleanup

crates/revm/src/db/ethersdb.rs, crates/revm/src/lib.rs
Provides a concrete implementation for the `DatabaseRef` trait instead of the `Database` trait. Implementation for the Database trait is simply a wrapper.
=> feat(revm): implement DatabaseRef trait for EthersDB

README.md
Addresses: #768 
Edited README.md to add the clang requirement.
=> docs: clang requirement

Cargo.lock, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/utilities.rs
Refactor modexp input parsing and use aurora modexp lib.
Blocked on https://github.com/aurora-is-near/aurora-engine/issues/844
=> feat(precompile): use Aurora modexp lib.

crates/interpreter/src/interpreter/shared_memory.rs
make memory limit field private and reorder impl order, adds current len to debug impl
=> chore: make memory-limit private

crates/primitives/src/db.rs, crates/primitives/src/db/components.rs, crates/revm/src/db/emptydb.rs, crates/revm/src/db/ethersdb.rs, crates/revm/src/db/in_memory_db.rs
Close https://github.com/bluealloy/revm/issues/540
=> fix: rename `DatabaseRef` trait functions to `*_ref`

crates/primitives/src/db.rs, crates/primitives/src/db/components/block_hash.rs, crates/primitives/src/db/components/state.rs, crates/revm/src/evm_impl.rs
Ref traits with `&self` can have all of `&, &mut, Box, Rc, Arc`
Traits with `&mut self` can only have `&mut, Box`
=> feat: add more `auto_impl`s to revm traits

crates/interpreter/src/interpreter/shared_memory.rs, crates/revm/src/evm_impl.rs
- `current_len` is redundant -> replaced with `last_checkpoint` with minor performance boost
- some renaming and refactoring done, the code is a little cleaner (imo)
- added a couple of tests
=> chore(SharedMemory): small internal refactoring

documentation/src/introduction.md
The command posted at the front page of the [documentation](https://bluealloy.github.io/revm/introduction.html)
currently is not executable as is, it contains trailing spaces at the first line, which causes script to fail:
```
$ cargo run --profile ethtests -p revme -- \                                           
statetest \
../ethtests/GeneralStateTests/ \
../ethtests/LegacyTests/Constantinople/GeneralStateTests/ \
bins/revme/tests/EIPTests/StateTests/stEIP5656-MCOPY/ \
bins/revme/tests/EIPTests/StateTests/stEIP1153-transientStorage/
Finished ethtests [optimized + debuginfo] target(s) in 0.13s
Running `target/ethtests/revme ' '`
error: The subcommand ' ' wasn't recognized
USAGE:
revme help <subcommands>...
For more information try --help
statetest: command not found
```
After this minor …
=> docs(fix): cleaned example command for running tests

crates/precompile/src/lib.rs, crates/revm/src/handler.rs
Reversing some changes so we can support the older rust compiler, there was a request for this as llvm bump broke downstream project.
From chat: `This has nothing to do with Rust specifically, but with the RISC-V LLVM backend used: There seems to be a bug in LLVM, introduced somewhere between 1.69 and 1.70, that generates invalid riscv32 instructions.`
For note: `rust 1.70` added `llvm 16.0.2` while `rust 1.73` added `llvm 17.0.2`.
=> chore: for now support 1.69 rust compiler

crates/primitives/src/state.rs
since the code can be None, we commonly need to check if the code hash is indeed the empty hash.
this adds a new function that does this check.
=> feat: add is_empty_code_hash fn

crates/revm/src/db/states/state.rs, crates/revm/src/db/states/state_builder.rs
There is no good reason to put `BundleState` in an `Option`. In the case of a missing pre-loaded bundle, the default can be used instead.
=> chore(state): make bundle state non-optional

crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs, crates/revm/src/handler.rs, crates/revm/src/handler/mainnet.rs, crates/revm/src/handler/optimism.rs
Contains several fixes for the Optimism state transition code.
After hooking up the OP execution changes to `op-reth` and performing a sync test on the Base Goerli network, a few bugs were found.
1. The Optimism EL has a critical invariant that _deposit transactions may never fail_. This implies that even upon a total failure of the state transition, for any reason, the `mint` value should be persisted to the sender account's balance to prevent loss of funds, and the sender's nonce should be bumped as well.
1. **Solution**: Pull out the default implementation of the `transact` function in the `Transact` trait, and define a catch-all failure handler that persists the `mint` value to and bumps the nonce of the caller account before returning a special `Halt` variant.
1. When a deposit …
=> fix(op): Base Goerli `op-reth` sync patches

crates/interpreter/src/instructions/stack.rs, crates/interpreter/src/interpreter/stack.rs
Performance is the exact same. The current implementation is a hand-rolled version of this PR's.
=> refactor: rewrite `Stack::push_slice` to allow arbitrary lengths

crates/revm/src/db/states/cache.rs
Simplify the control flow in `CacheState::apply_evm_state`. Extract account update to a separate `CacheState::apply_account_state` function.
=> chore(state): simplify control flow in `CacheState::apply_evm_state`

crates/primitives/src/state.rs, crates/revm/src/db/states/account_status.rs, crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/cache_account.rs, crates/revm/src/db/states/state.rs
- Move the complexity of account status transitions from `CacheAccount` to `AccountStatus`.
- Write additional docs for `AccountStatus` transitions.
- Deduplicate `AccountStatus` transitions in `CacheAccount::account_info_change` and `CacheAccount::change` since they were equivalent.
=> chore(state): move account status transitions to `AccountStatus`

crates/interpreter/src/interpreter/stack.rs
- `get_unchecked{,_mut}` is *always* UB if out of bounds. This is easy to overlook because it works correctly, but it's still UB. Use pointers instead.
- `Stack::push_slice` (#812) did not handle more than one word (32 bytes) correctly. Added simple unit tests to verify correct behavior. No performance changes.
=> fix(interpreter): stack UB and `push_slice` impl

crates/revm/src/db/emptydb.rs, crates/revm/src/db/states/state.rs
As the discussion in https://github.com/foundry-rs/foundry/issues/6235 , currently, `blockhash(number)` returns `number`, but I think we should use `keccak256` for `blockhash`.
The main reason is:
>`blockhash`, even though it's a 256-bit value, can be represented by a much smaller number of bits  from a security point of view.
>For example, if a contract has a bug that the upper bits of the `blockhash` value are missing in inline-assembly or something, the bug would not be detected in tests.
This PR used it as we have done so before https://github.com/bluealloy/revm/pull/691 .
@DaniPopes This is a minor change and mds1 agreed that so I've sent this PR to facilitate it before I get your reply. :)
=> chore: use keccak256 for blockhash

crates/precompile/src/lib.rs, crates/revm/src/evm_impl.rs
smol change:
make fn addresses return an Iterator
add `into_addresses`
merge two `impl Precompiles` blocks
=> chore: change addresses to iterator and add into_addresses

crates/precompile/src/lib.rs
Make `PrecompileWithAddress` fields public so they can be accessible and add `From` impl for (address,precompile) tuple.
=> chore(precompiles): Make PrecompileWithAddress field public, from impl

crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/primitives/src/utilities.rs, crates/revm/src/db/states/changes.rs, crates/revm/src/db/states/state.rs, crates/revm/src/inspector.rs, crates/revm/src/journaled_state.rs
Solved rust doc warnings since the issue was open since september.
One part I was uncertain was
_/// Takes `blob_excess_gas` saves it inside env
/// and calculates `blob_fee` with [`BlobGasAndFee`]._
Because there's no mention of BlobGasAndFee in the code. I assumed it to be BlobExcessGasAndPrice that is what is used in the code below it
=> chore: Fix rustdoc warnings

crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/revm/src/evm_impl.rs
Instead of returning the fee for a transaction, the LackOfFundForMaxFee error currently returns gas_limit. This PR fixes that.
=> Fix error message for LackOfFundForMaxFee

Cargo.lock, bins/revme/src/cmd/statetest/runner.rs, crates/precompile/Cargo.toml, crates/precompile/src/secp256k1.rs, crates/revm/src/inspector/eip3155.rs
Bumping k256 lib and changing requirement that sig needs normalization of S point. Discussion from here: https://github.com/RustCrypto/elliptic-curves/issues/988#issuecomment-1815319945
=> bump k256 and use normalize_s

crates/primitives/src/precompile.rs, crates/primitives/src/specification.rs
* remove unnecessary function/trait implementations
* fix docs errors
=> refactor(primitives): don't duplicate the SpecId::enabled() logic

crates/interpreter/src/instructions/opcode.rs, crates/precompile/src/lib.rs, crates/primitives/src/specification.rs, crates/revm/src/evm_impl.rs
Adds the `Canyon` hardfork behind the `optimism` feature flag, and adds a macro to define the `SpecId` enum to separate the ordering of hardforks between L1 and `optimism`.
The `Canyon` hardfork does not implement any EVM changes, though it does implicitly enable `Shanghai`.
More information about `Canyon` can be found in the upstream tracking issue: https://github.com/ethereum-optimism/optimism/issues/7452
=> feat: `Canyon` hardfork behind `optimism` feature flag

crates/interpreter/src/interpreter/stack.rs, crates/revm/src/inspector/eip3155.rs
Ensure stack always has STACK_LIMIT capacity
removes Clone
ref #876
=> fix: safer stack

Cargo.lock, crates/revm/src/db/states/state.rs
relax generic; remove trait bound
not required for struct def, as only the impl requires `Database`
=> chore: relax state generic

README.md
=> chore(docs): Updated Benchmark Docs

.github/workflows/ci.yml, Cargo.toml, crates/interpreter/Cargo.toml, crates/interpreter/src/interpreter/shared_memory.rs, crates/interpreter/src/lib.rs, crates/precompile/Cargo.toml, crates/precompile/src/blake2.rs, crates/precompile/src/hash.rs, crates/precompile/src/identity.rs, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs, crates/primitives/Cargo.toml, crates/primitives/src/db/components/block_hash.rs, crates/primitives/src/db/components/state.rs, crates/primitives/src/lib.rs, crates/revm/Cargo.toml, crates/revm/src/evm_context.rs, crates/revm/src/journaled_state.rs, crates/revm/src/lib.rs
Breaks up the github `ci.yml` workflows to mirror [alloy](https://github.com/alloy-rs/core/blob/0c21fcc48eab0b52c20d3e98c739bac862aad8ff/.github/workflows/ci.yml).
Adds warnings to all crates for `rustdoc::all`. Fixes #742
=> fix(ci): Workflow Touchups

crates/revm/Cargo.toml, crates/revm/src/evm_context.rs, crates/revm/src/lib.rs, crates/revm/src/test_utils.rs
Adds tests to the `EvmContext` and introduces testing utilities behind a `test-utils` feature flag.
=> feat(revm): Evm Context Tests and test-utils Feature

crates/interpreter/src/instruction_result.rs
Improved from: https://github.com/foundry-rs/foundry/blob/388e181c50c9313ca8cfe2c4f413397100dd1ce7/crates/evm/core/src/utils.rs#L104
=> feat: add some conversions to InstructionResult

README.md
Updates the readme bench docs to point to the benchmarks in the `revm` package.
=> chore(docs): README Benchmark Doc Updates

crates/revm/src/db/states/bundle_state.rs
=> feat(revm): implement prepend_state for BundleState

crates/primitives/src/env.rs, crates/primitives/src/state.rs
This is a small optimization for AccountInfo.is_empty() with regards to the short-circuiting of bool operators in Rust.
=> perf(primitives): optimize AccountInfo.is_empty()

crates/interpreter/Cargo.toml
- enable the `optional_beneficiary_reward` feature automatically when the `dev` feature is enabled.
This modification seemed reasonable, being in line with how the `dev` features of the `primitives` and `revm` crates are defined.
=> chore(interpreter): conditionally enable `optional_beneficiary_reward`

crates/interpreter/src/gas.rs
`shared_memory_resize!` was the only macro I've found that calls the `record_memory()` function.
=> docs(interpreter): fix the name of the macro referenced by record_memory()

crates/revm/src/optimism.rs
replaces &Bytes with &[u8] which makes this function callable with any deref slice type
=> chore: relax Bytes requirement and use slice instead

Cargo.lock, crates/primitives/src/kzg/trusted_setup_points.rs
fixes `cargo c --no-default-features --features c-kzg`
=> fix: make revm-primitives no-std with c-kzg feature

crates/revm/src/db/ethersdb.rs
Instead of panicking whenever there's an error fetching the account data, return None. This behavior is similar to the EmptyDB and helpful in unit tests when using the mock provider. The tradeoff here is that any RPC client connection issues can surface as EVM execution revert errors but these can be easily mitigated earlier on in the middleware setup process. If the client connection is established, the behavior is essentially the same for callers.
=> feat(ethersdb): basic_ref return none  instead of panic

crates/primitives/src/env.rs
The optimization comes from the fact that the respective variables are only created if they're, actually, going to be used after that (instead of being untouched due to an early return).
=> refactor(primitives): improve readability of Env.validate_tx()

crates/interpreter/src/instruction_result.rs
While any of the 2 could've been used to achieve consistency, `{ }` has been chosen because, as far as I've read, it doesn't lead to any memory being allocated (being just a code block), while `( )`, representing the "unit type", does occupy some memory.
The latter isn't as important in the context of a test function, of course, but given that this would be the better option (over `( )`), in general, don't see why it wouldn't also be used throughout the test functions (to maintain the consistency with the production codebase functions).
Curious about your take on this, @rakita
=> refactor(interpreter): consistency in all_results_are_covered()

.github/workflows/cachegrind.yml
Always pass action as GITHUB_TOKEN is giving only read access from forked repositories: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#changing-the-permissions-in-a-forked-repository
=> ci(cachegrind): pass action always

crates/interpreter/src/instruction_result.rs, crates/primitives/src/result.rs, crates/revm/src/handler/optimism.rs
The new names are more suggestive of what the enums represent, in my opinion.
=> refactor(interpreter): improve enum naming

crates/interpreter/Cargo.toml, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml, crates/revm/Cargo.toml
Adds a feature to each crate, `asm-keccak`, which enables the same feature from alloy-primitives.
This can show performance improvements for keccak on some machines:
https://github.com/alloy-rs/core/pull/466
=> feat: add asm-keccak feature

crates/interpreter/src/inner_models.rs, crates/revm/src/evm_context.rs
Calculating keccak on CREATE opcode is unnecessary as it is only needed on CREATE2. `init_code_hash` is needed only for foundry so setting `B256::ZERO` can work.
=> fix: dont calculate initcode keccak on CREATE

.github/workflows/release-plz.yml
We recently started using this to automate our semantic versioning after it was recommended by the nior-lang team. It has been a large quality of life improvement and improves stability. When done manually, semantic versioning is error prone and these errors can lead to problems in down-stream dependancies. If configured this will run on every PR into main and detect semantic versioning changes, it will then open a PR with a release tag, changelog, and auto incremented semver (under the hood this is done with [cargo-semver-checks](https://github.com/obi1kenobi/cargo-semver-checks)). 
This is incomplete as only the repository administrator can configure the github token as well as the cargo registry token.
=> added release-plz config

crates/revm/src/builder.rs
The trait is not needed, so we can remove it.
=> refactor(EvmBuilder): Remove unnecessary BuilderStage trait

crates/primitives/src/result.rs, crates/revm/src/optimism/handler_register.rs
In #967 there is described a temporary solution for a panic in optimism handler code.
So far, it is a simple extension for the `EVMError` enum, containing error explanation as a String.
All related panics are replaced with the code returning this error.
This is my first quick issue here, looking forward for feedback.
=> feat: Convert optimism panic into graceful error

crates/revm/src/optimism/handler_register.rs
This PR adds this missing `deduct_caller` function that charges the L2 transaction sender the estimated L1 batch submission fee to the Optimism handler.
=> fix: missing `deduct_caller` in optimism handler

crates/revm/src/context.rs
CfgEnv no longer has the specId. this is now in the journaledstate
This adds a getter to the EmvContext, though it's not obvious to me where the SpecId in the journaledState is properly set, in the new functions this is always, latest.
if the EvmContext has access to the spec id then it's not clear why it gets it as argument:
https://github.com/bluealloy/revm/blob/main/crates/revm/src/context.rs#L214-L214
so I'm not 100% about this getter, but it's definitely useful the get access to the evm's specid during inspection.
=> chore: add getter for specId

crates/interpreter/src/instruction_result.rs, crates/interpreter/src/interpreter.rs
The `InterpreterResult` wraps an `InstructionResult`
This also exposes the `is_{error,success}` functions on the `InterpreterResult`
moves struct defs around and makes calls const.
=> chore: expose InstructionResult getters in Interpreter result

crates/revm/src/inspector.rs, crates/revm/src/inspector/customprinter.rs, crates/revm/src/inspector/eip3155.rs, crates/revm/src/inspector/gas.rs, crates/revm/src/inspector/handler_register.rs
Added `Rc<RefCell<>>` to call/create inspector handler so we can share inputs stack.
This functionality was removed with a call loop as the input is discarded after the frame is created and not available in *_end Inspector function, this removal became a problem for downstream libraries that use Inspector.
=> feat(inspector): Share call/create inputs in Inspector call_end/create_end

bins/revme/src/cmd/statetest/runner.rs, crates/interpreter/src/gas/calc.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/host/call_helpers.rs, crates/interpreter/src/instructions/macros.rs
Split calls to separate functions.
Calls are now very rigid and it is hard to add custom calls to create a new frame. This is first step towards introducing Generics on calls (not sure on the final form that would encompass both creates and calls)
=> chore(Interpreter): Split calls to separate functions

crates/interpreter/src/interpreter.rs
From comment here: https://github.com/bluealloy/revm/pull/1002/files#r1461978421
Introduced yesterday
=> fix(Interpreter): is_revert should call is_revert

crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs
Delete an account from bundle state only if the original value is None, if we delete non original value we will lose this information.
Original account `None` means that account din't exist.
On revert if we want to revert on non existing account this means that it is not existing, so we revert on non existing account.
=> fix(State): Preserve original values on delete revert

crates/interpreter/src/instructions/opcode.rs, crates/precompile/src/lib.rs, crates/primitives/src/specification.rs, crates/revm/src/handler/mainnet/pre_execution.rs, crates/revm/src/optimism/handler_register.rs, crates/revm/src/optimism/l1block.rs, examples/generate_block_traces.rs
Adds definitions and support for the upcoming Ecotone hardfork on Optimism.
The `Ecotone` hardfork is activated alongside `Cancun`, with few execution layer modifications of our own. The rollup will now be using 4844 DA, which involves some changes to the L1 fee calculation.
1. `Ecotone` L1 fee specifications: https://github.com/ethereum-optimism/specs/blob/main/specs/exec-engine.md#ecotone-l1-cost-fee-changes-eip-4844-da
2. `Ecotone` L1 fee reference implementation: https://github.com/ethereum-optimism/op-geth/blob/a4e85ec465e2de3f962d757d8f9b561b5461f861/core/types/rollup_cost.go
=> feat(op): Ecotone hardfork

crates/interpreter/src/interpreter/analysis.rs
If someone wants a `Bytes` of the original bytecode they have to copy it with `Bytes::copy_from_slice`, but we store it already as `Bytes` so we can use `Bytes::slice` to avoid copying it.
E.g: https://github.com/foundry-rs/foundry/blob/f11da382d69ee7df32c56290101f6ef5e0cf9317/crates/evm/coverage/src/inspector.rs#L17
=> feat: add `BytecodeLocked::original_bytecode`

bins/revme/src/cmd/statetest/runner.rs, crates/revm/src/builder.rs, crates/revm/src/evm.rs, crates/revm/src/inspector/customprinter.rs
Small renamings, `spec_id` to `with_spec_id` and other for HandlerCfg
=> chore(EvmBuilder): rename builder functions to HandlerCfg

crates/interpreter/src/host.rs, crates/interpreter/src/host/dummy.rs, crates/primitives/src/env.rs, crates/primitives/src/env/handler_cfg.rs, crates/revm/src/builder.rs, crates/revm/src/evm.rs, crates/revm/src/handler.rs
* `Env::boxed` added
* `with_env,_tx,_block` added to builder
*  `tx(), block(), env()` added to `Evm` with their mutable counterparts
=> tweeks: helper functions around Env

Cargo.lock, crates/precompile/Cargo.toml, crates/precompile/src/kzg_point_evaluation.rs, crates/primitives/Cargo.toml, crates/primitives/src/kzg.rs, crates/revm/Cargo.toml
This bumps `c-kzg-4844` and enables blst's `portable` feature. The fact that we have to add `blst` as an optional dependency to do this is a mistake on my part, since we should have introduced `portable` as a feature in `c-kzg-4844` directly. Added TODOs for that
=> chore: bump c-kzg and enable blst portable feature

crates/revm/src/optimism.rs, crates/revm/src/optimism/handler_register.rs
=> fix(op): skip validation on deposit tx

bins/revme/src/cmd/statetest/models/mod.rs, bins/revme/src/cmd/statetest/runner.rs, bins/revme/src/main.rs, crates/revm/src/lib.rs
=> tests(revme): statetests new format and return error

crates/precompile/src/kzg_point_evaluation.rs, crates/revm/src/builder.rs, crates/revm/src/context.rs, crates/revm/src/evm.rs, crates/revm/src/inspector/handler_register.rs, crates/revm/src/lib.rs
Added `ContextWithHandlerCfg`, `EvmBuilder::with_context_with_handler_cfg` and `Evm::into_context_with_handler_cfg`
=> chore(revm): Add helpers to Build Revm with Context

crates/revm/src/builder.rs, crates/revm/src/handler.rs
Docs said `append handle register` so I just did a quick rename
=> fix: typo on internal append_handle_register methods

crates/precompile/src/blake2.rs, crates/precompile/src/hash.rs, crates/precompile/src/identity.rs, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/utilities.rs, crates/revm/src/context.rs
... and some other minor refactors.
In secp256k1 both backends expect a 64-byte signature and the recovery ID in two separate arguments, therefor there is no point in packing them into a 65-byte array only to unpack them right after.
=> refactor(precompile): make use of padding utilities, simplify secp256k1

crates/precompile/src/bn128.rs
Reduce stack and heap allocations, factor out some common code to separate functions/closures.
=> perf/refactor(precompile): simplify bn128 precompile implementations

crates/precompile/src/bn128.rs, crates/precompile/src/modexp.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/utilities.rs
Return `Cow<[u8 (; LEN)]>` in padding functions when padding is not needed due to input being long enough.
~~First commits are https://github.com/bluealloy/revm/pull/1073 and https://github.com/bluealloy/revm/pull/1074.~~
~~Actual changes in the last commit.~~
=> perf(precompile): don't allocate if padding is not needed

crates/revm/src/db/states/bundle_state.rs
Updates the documentation for `OriginalValuesKnown`, since the `No` variant references something called `CheckOriginalValues`, which is not in the codebase as far as I can tell.
A comment about `should_collect_reverts`, also non existing, is removed.
=> feat: improve OriginalValuesKnown docs

crates/interpreter/src/instructions/macros.rs, crates/precompile/src/blake2.rs, crates/precompile/src/bn128.rs, crates/precompile/src/hash.rs, crates/precompile/src/identity.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/modexp.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/utilities.rs, crates/primitives/src/precompile.rs, crates/revm/src/context.rs
Closes https://github.com/bluealloy/revm/issues/1072.
=> perf(precompile): use `Bytes` in precompile functions

crates/primitives/src/env/handler_cfg.rs
If `optimism_default_handler` is enabled by default `is_optimism` flag will be true
=> fix: Set is_optimism to true if default config

crates/primitives/src/env/handler_cfg.rs, crates/revm/src/builder.rs
Fixes compilation when `optimism_default_handler` is enabled.
There is still an issue this PR doesn't fix: the flag `optimism_default_handler` doesn't seem to be passed down to `revm-primitives` when enabled in `revm`. As it requires some refactoring in the Cargo.tomls/imports, I think it's better if I let you handle that.
=> fix: optimism compilation

crates/revm/src/db/states/cache_account.rs
Avoid cloning full plain account inside cache account. Previously, the plain account was cloned with storage which can get expensive.
=> perf(state): avoid cloning full account

.github/workflows/ci.yml, crates/interpreter/Cargo.toml, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml, crates/primitives/src/env/handler_cfg.rs, crates/revm/Cargo.toml, crates/revm/src/builder.rs
Follow up to this PR: https://github.com/bluealloy/revm/pull/1091
=> fix: rename and pass optimism-default-handler to revm-primitives

bins/revme/Cargo.toml, crates/revm/Cargo.toml, crates/revm/src/db/in_memory_db.rs, crates/revm/src/inspector.rs
`serde_json` is not necessarily wanted when enabling `serde` impls.
Technically a breaking change.
=> feat: split off serde_json dependency to its own feature

Cargo.lock, crates/interpreter/Cargo.toml, crates/precompile/Cargo.toml, crates/precompile/src/kzg_point_evaluation.rs, crates/primitives/Cargo.toml, crates/primitives/src/kzg.rs, crates/revm/Cargo.toml
This uses the new `portable` feature, enabled by default, for c-kzg. Also bumps c-kzg version. Removes the need to do:
```rust
// TODO: remove when we have `portable` feature in `c-kzg`
use blst as _;
```
and
```toml
c-kzg = ["dep:c-kzg", "revm-primitives/c-kzg", "dep:blst", "blst?/portable"]
```
=> feat: bump c-kzg, add portable feature, make it default

crates/interpreter/src/interpreter.rs
`self.instruction_result = InstructionResult::Continue;` was set always before running the interpreter loop to override the `InstructionResult::CallOrCreate` but it would void the Fatal result that was set in outcome insert.
So moving override to outcome insert fixes it.
=> fix(db): Set instruction result at outcome insert

crates/revm/src/db/ethersdb.rs, crates/revm/src/lib.rs
related with https://github.com/bluealloy/revm/issues/1056
actually removing the way we use futures::executor::block_on with tokio async 
we're using now Handle::block_on instead of (futures::executor::block_on) so we can have futures executed in same context of tokio runtime and we can then avoid deadlocks
@rakita do you suggest me i allow unused crates to fix clippy error ?
=> fix EthersDB deadlock

crates/interpreter/src/host.rs, crates/interpreter/src/host/dummy.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/lib.rs, crates/revm/src/context.rs, crates/revm/src/evm.rs, crates/revm/src/journaled_state.rs
=> fix: replace tuple in sstore return with struct

crates/revm/src/db/ethersdb.rs
This reverts commit 0055d58ba6c60f5bcc623009dce4040c03aefb4f.
=> Revert "fix EthersDB deadlock (#1089)"

crates/revm/Cargo.toml
This PR fixes name of feature used by one of the examples. It looks like this feature is now renamed: 
https://github.com/bluealloy/revm/blob/2d4fb0605585477add6478b9495022816a7d965c/crates/revm/src/inspector.rs#L10
=> Fix feature name for generate_block_traces example

crates/revm/src/optimism/l1block.rs
After `Cancun` activation, the `L1Block` contract is no longer guaranteed to be loaded into the catch when `try_fetch` is called due to EIP-4788. Adds a condition that after `Cancun` activation, the `L1Block` contract should be loaded into the accounts cache at the start of `try_fetch`.
=> fix: Ensure `L1Block` is in the cache

crates/revm/src/builder.rs
Added a method to make it possible to add a _specific_ handler, for example a handler other than optimism or mainnet, to the evm builder.
=> feat: add with_handler method to EvmBuilder

crates/revm/src/context.rs
Add `clone` method to `ContextWithHandlerCfg`.
Pullrequest created for: #1126
So instead of
```rust
let cfg = ContextWithHandlerCfg::new(self.ctx_with_handler.context.clone(), self.ctx_with_handler.cfg.clone());
Evm::builder().with_context_with_handler_cfg(cfg).build();
```
Now:
```rust
Evm::builder().with_context_with_handler_cfg(self.ctx_with_handler.clone()).build();
```
=> Add `clone` method to `ContextWithHandlerCfg`

crates/revm/src/lib.rs, crates/revm/src/optimism/handler_register.rs
Seems some versions of rust need this. 
```
error[E0599]: no method named `to_string` found for reference `&'static str` in the current scope
--> /Users/yjhmelody/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-6.1.0/src/optimism/handler_register.rs:187:68
|
187 |                 "[OPTIMISM] Failed to load enveloped transaction.".to_string(),
|                                                                    ^^^^^^^^^ method not found in `&str`
|
= help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
|
3   + use crate::std::string::ToString;
|
error[E0599]: no method named `to_string` found for reference `&'static str` in the current scope
--> …
```
=> fix: add ToString for no_std add exports some types in no_std

crates/primitives/src/env/handler_cfg.rs
make it easier to access spec id
=> chore: add helper function for spec id

crates/revm/src/evm.rs
Old
```rust
evm.context.evm.db.clone();
evm.context.evm.db.insert_account_info(...);
```
New
```rust
evm.db().clone();
evm.db_mut().insert_account_info(...);
```
=> Add `db` and `db_mut` to evm

Cargo.lock, crates/revm/Cargo.toml, crates/revm/src/db/ethersdb.rs
This PR removes the improper initialization of the runtime.
Explanation:
- Initializing a runtime when creating the struct doesn't make sense.
Users may create an `EthersDB` in a sync context but later use it in an async environment and vice versa. In this case, two runtimes will conflict. In addition, the current code, by default, creates a multithreaded runtime, which could be unexpected for users. For example, users may want to run many instances in parallel with separate cores pinned but the runtime created could interfere with this design.
Therefore, reasonable behavior is always checking if we are in an `async` environment by `Handle::try_current.` If we are in  `async`, we will pick the runtime created by users. Or else, we simply create a `current_thread` runtime to get things …
=> Check runtime dynamically

README.md
Hi, we are using revm in an open source simulation library we built, this PR just adds an entry and link in the used by section
=> Add VERBS to used by list

Cargo.lock, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/precompile.rs, crates/revm/src/context.rs
closes: #798 
Box is over the trait that has a `call` function. Trait is sync/send so it can be stored inside OnceBox.
And DynClone is added so precompiles can be cloned.
=> feat: Add boxed precompile trait

crates/interpreter/src/instructions/opcode.rs, crates/primitives/src/env/handler_cfg.rs, crates/primitives/src/specification.rs, crates/revm/src/handler.rs
Ideally this would also return `&'static` but since `InstructionTable` is generic over `H`, `&'static InstructionTable<H>` requires `H: 'static`, for which I haven't yet found a work-around.
=> perf(interpreter): evaluate instruction table constructor at compile time

crates/interpreter/src/instructions/control.rs
JUMP and JUMPI are identical except for the condition check.
=> chore(interpreter): factor out jump logic

crates/interpreter/src/instructions/bitwise.rs
`op2 == 0` is already computed in `value_sign`.
=> chore(interpreter): use already-computed sign in SAR

crates/revm/src/context.rs, crates/revm/src/evm.rs, crates/revm/src/journaled_state.rs
closes https://github.com/bluealloy/revm/issues/1156
=> feat: add more JournaledState methods to EvmContext

bins/revme/src/cmd/statetest/runner.rs, crates/interpreter/src/instructions/i256.rs, crates/interpreter/src/interpreter.rs, crates/primitives/src/result.rs, crates/revm/src/builder.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/frame.rs, crates/revm/src/handler/mainnet/execution.rs, crates/revm/src/handler/mainnet/post_execution.rs, crates/revm/src/inspector/handler_register.rs
Increases minimum Rust version to 1.75
=> feat: use `impl` instead of `dyn` in `GetInspector`

crates/revm/src/journaled_state.rs
finalize is called via the output handler and is supposed to reset the journaledstate.
this ensures the transient storage is also cleared, restoring the initial state of JournaledState
=> fix: reset tstorage on finalize

crates/revm/src/inspector/gas.rs
A bug was introduced in the last gas cost calculation in [this commit](https://github.com/bluealloy/revm/commit/8418558b808f87a251ae1d97a80b985d0039988e#diff-bc5de00072f218e23e10d28db011fdb048e16fac459147e7c9a1a1bdce56c621L55). This PR fixes it.
=> fix: gas cost calculation

crates/interpreter/src/instructions/opcode.rs, crates/revm/src/builder.rs
Adds an `insert` helper method on the instruction table, and adds a test for creating and using a custom instruction
=> feat: add insert method on instruction table

crates/precompile/src/bn128.rs, crates/precompile/src/utilities.rs
Useful for precompiles that return `bool` padded to 32 bytes.
=> feat(precompile): add a bool to bytes32 helper function

crates/interpreter/src/instructions/opcode.rs
Currently the only way to instantiate an OpCode at compile time is by using unsafe or matching on the Option returned by `new` (unwrap is not stable). This PR adds the same `u8` opcode constants to the `OpCode` struct as well.
=> feat(interpreter): OpCode struct constants

crates/revm/src/builder.rs, crates/revm/src/context.rs, crates/revm/src/context/context_precompiles.rs, crates/revm/src/context/evm_context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/evm.rs, crates/revm/src/handler/handle_types/pre_execution.rs, crates/revm/src/handler/mainnet/execution.rs, crates/revm/src/handler/mainnet/post_execution.rs, crates/revm/src/handler/mainnet/pre_execution.rs, crates/revm/src/handler/mainnet/validation.rs, crates/revm/src/lib.rs, crates/revm/src/optimism/handler_register.rs, crates/revm/src/test_utils.rs, examples/db_by_ref.rs
Making context precompiles take full context (External and Evm) would make a problem in Inspector
On main we have moved Precompiles from EvmContext and Inspector would not have access to it, this would break foundry and other tracers.
This PR make Context precompile access only EvmContext and makes no changes to Inspector.
EvmContext is now:
```
pub struct EvmContext<DB: Database> {
pub inner: InnerEvmContext<DB>,
/// Precompiles that are available for evm.
pub precompiles: ContextPrecompiles<DB>,
}
```
and it implemented `Deref` and `DerefMut` on `inner`
=> feat: Restrict ContextPrecompiles only to EvmContext

CHANGELOG.md, Cargo.lock, bins/revm-test/Cargo.toml, bins/revme/Cargo.toml, crates/interpreter/CHANGELOG.md, crates/interpreter/Cargo.toml, crates/revm/CHANGELOG.md, crates/revm/Cargo.toml
revm v7.0.0 got yanked and replaced with v7.1.0
PR that got included is https://github.com/bluealloy/revm/pull/1174
one more small PR got through in Interpreter, not related to this situation.
=> chore: tag v32 revm v7.1.0

documentation/src/crates/interpreter/memory.md
Add docs about memory and opcodes that change it.
=> doc: add memory section

crates/primitives/src/kzg/trusted_setup_points.rs, crates/primitives/src/precompile.rs, crates/primitives/src/result.rs
Make error messages consistent with Reth (starting lowercase, no full stops).
=> chore: improve error implementations

crates/primitives/src/lib.rs
Also caught by `-Zcheck-cfg`:
```rust
warning: unexpected `cfg` condition name: `std`
--> crates/primitives/src/lib.rs:34:14
|
34 |     if #[cfg(std)] {
|              ^^^ help: found config with similar value: `feature = "std"`
|
= help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `unix`, `windows`
= help: consider using a …
```
=> fix: use std hashmap with "std" feature

crates/interpreter/Cargo.toml, crates/primitives/Cargo.toml, crates/primitives/src/env.rs, crates/revm/Cargo.toml
For Hardhat we need the ability to disable nonce checks. This PR follows the existing pattern for similar features and adds it to the `dev` feature flag.
=> feat: optional nonce check

.gitignore
Cargo fmt has had some issues recently, this should prevent accidentally committing the bug reports
=> chore: add rustc-ice-*.txt to gitignore

crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/lib.rs, crates/precompile/src/lib.rs, crates/precompile/src/secp256k1.rs
Aiming to help add custom instructions and precompiles
=> chore: expose functionality for custom EVMs

crates/interpreter/src/instructions/opcode.rs, crates/revm/src/builder.rs
This adds a test which serves as an example for adding custom instructions which require some context. This also adds `convert_boxed` and `insert_boxed` which should make it easier to do this using the revm builder.
=> feat: add convert_boxed and insert_boxed for InstructionTable

crates/interpreter/src/gas.rs, crates/interpreter/src/instructions/arithmetic.rs, crates/interpreter/src/instructions/bitwise.rs, crates/interpreter/src/instructions/control.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/host/call_helpers.rs, crates/interpreter/src/instructions/host_env.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/instructions/memory.rs, crates/interpreter/src/instructions/stack.rs, crates/interpreter/src/instructions/system.rs
Extends https://github.com/bluealloy/revm/pull/1201
=> feat(interpreter): export utility macros

crates/revm/src/db/ethersdb.rs
As title, this prevents etherdb halting down the whole program by blindly `unwrap`.
=> Change unwrap to ? to propagate errors

Cargo.lock, crates/precompile/Cargo.toml, crates/precompile/benches/bench.rs, crates/precompile/src/bn128.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/lib.rs, crates/precompile/src/secp256k1.rs
Benchmarks runtime of a precompile instance, and prints out the gas used by the precompile call. This also exposes some methods and constants required for the precompile benchmarks
=> feat: add benchmarks for ecpairing, kzg, ecrecover precompiles

crates/interpreter/Cargo.toml, crates/precompile/src/modexp.rs, crates/primitives/Cargo.toml, crates/primitives/src/env.rs, crates/revm/Cargo.toml
This reverts commit fe841be0ed2b01c3a1e34c7d45c0c8cf65808db2.
PR: https://github.com/bluealloy/revm/pull/1195
=> Revert "feat: optional nonce check (#1195)"

crates/precompile/src/blake2.rs, crates/precompile/src/bn128.rs, crates/precompile/src/hash.rs, crates/precompile/src/identity.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs
small change that makes precompiles `mod` public for all precompiles
=> feat: make all precompiles public

crates/interpreter/src/instructions/arithmetic.rs
Sign-extending the last bit does nothing. See also [the implementation in `evmone`](https://github.com/ethereum/evmone/blob/7bd7596c2754229f37344e10cdd49d638391f90f/lib/evmone/instructions.hpp#L231C20-L231C64).
=> perf(interpreter): don't run signextend with 31 too

crates/interpreter/src/gas.rs, crates/revm/src/handler/mainnet/execution.rs, crates/revm/src/handler/mainnet/post_execution.rs, crates/revm/src/optimism/handler_register.rs
Removes a load and a comparison in the very hot `record_cost` function (see diff below) by using `overflowing_sub` instead of `saturating_add` + `< limit`.
Reduces `snailtracer` instructions from `2,768,629,456` to `2,661,673,460` (-3.86%).
I've also renamed `Gas::spend` to `Gas::spent` (with a deprecation warning).
=> perf(interpreter): keep track of remaining gas rather than spent

Cargo.lock
I'm not sure why dependabot doesn't do most of these. I needed to run this to fetch the latest `ruint`.
=> chore(deps): run `cargo update`

crates/interpreter/src/interpreter.rs, crates/revm/benches/bench.rs, crates/revm/src/context/evm_context.rs, crates/revm/src/context/inner_evm_context.rs
I don't see a reason for this to be boxed, it's 184 bytes big when the interpreter is 256 already, bringing it to 432 doesn't change much.
This doesn't affect the size of frames as they themselves are boxed.
=> chore(interpreter): unbox contract field

Cargo.lock, crates/precompile/Cargo.toml, crates/precompile/benches/bench.rs
This PR fixes the precompile benchmarks. When I tried running them I got this error:
```
error[E0425]: cannot find function `thread_rng` in crate `rand`
--> crates/precompile/benches/bench.rs:56:48
|
56  |     let secret_key = SecretKey::new(&mut rand::thread_rng());
|                                                ^^^^^^^^^^ not found in `rand`
|
note: found an item that was configured out
--> /Users/jtraglia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rand-0.8.5/src/lib.rs:105:30
|
105 | pub use crate::rngs::thread::thread_rng;
|                              ^^^^^^^^^^
```
=> fix: use correct rand package for thread_rng

crates/revm/src/inspector/gas.rs
After changing calls into loop, remaining gas calculation became simpler and this fixes the bug of incorrect remaining gas after returning from the CALL/CREATE opcodes.
Bug noticed here: https://github.com/paradigmxyz/reth/issues/6969
and here: https://github.com/paradigmxyz/evm-inspectors/pull/38#discussion_r1490933691
=> fix(GasInspector): calculate correct remaining gas after call return

crates/precompile/src/bn128.rs
This is pretty minor, but `MUL_INPUT_LEN` was 128 when it only needed to be 96. So there was some unnecessary padding. I don't expect any performance difference from this, just fixing to be more correct. As part of this, I added comments explaining the size and splitting the value into each component.
=> fix: use correct bn128 mul input length

crates/precompile/src/bn128.rs
This PR removes the intermediate call to `into_u256()` which appears to be unnecessary. I noticed that `ecmul` does it like this, and I think it's cleaner this way:
https://github.com/bluealloy/revm/blob/c3107ec3acf79119016acac203b1c2437005a90e/crates/precompile/src/bn128.rs#L157-L171
Also, rename `out` to `output` in `run_mul` for consistency.
=> nit: remove unnecessary call to into_u256() for bn128 add

crates/precompile/src/bn128.rs
The tests in the bn128 module have been commented out for a while. They only test Byzantium, but I think they would still be useful to have. This PR will do the following:
* Define `*_GAS_COST` constants for add and multiply.
* Update `run_add` and `run_mul` to take `gas_cost` and return `PrecompileResult`.
* Uncomment & fix the tests.
=> fix: update/enable bn128 tests

bins/revme/src/cmd/statetest/runner.rs, crates/revm/src/inspector/eip3155.rs, examples/db_by_ref.rs, examples/generate_block_traces.rs
This adds the option to include the memory of each step in the EIP3155 trace.
If the option "include_memory" is true, the tracer will add an additional "memory: "0x..." field to each trace event. The EIP3155 seems to be ambiguous about the (optional) memory field. In the Output section it describes it as a "Array of Hex-Strings", however in the Test Cases it is only a Hex-String, not an Array. This PR implements the Hex-String version.
I think this would be a breaking change, as the TracerEIP3155 signature now has an additional "include_memory" flag. I've written the commit message accordingly.
Also note that this is my first contact with Rust, feel free to modify things that are not best practice :) The unit tests still ran through and I've manually tested the memory output. Also, the …
=> feat: TracerEip3155 optionally traces memory

crates/interpreter/src/instructions/arithmetic.rs, crates/interpreter/src/instructions/i256.rs
This PR contains some minor nit fixes. Most notably, it moves the divisor zero-value check into the arithmetic function so that it behaves the same as `i256_div`, which will handle it by returning zero. Additionally:
* In `i256_div`, remove unnecessary `first_sign == Sign::Minus` check before `MIN_NEGATIVE_VALUE` check.
* In `i256_mod`, remove comment about "overflow checks" which aren't being done.
* In the tests, define constants for common values: one, two, three, etc.
* Add some new arithmetic tests and update old asserts to use new constants.
=> nit: move div by zero check from smod to i256_mod

crates/revm/src/inspector/eip3155.rs, crates/revm/src/inspector/handler_register.rs, documentation/src/crates/interpreter/instructions.md, documentation/src/crates/revm.md, examples/generate_block_traces.rs
Run multiple tx with a same TracerEip3155 will cause the gas_remaining incorrect.
=> fix(TracerEip3155): clear Inspector data after transaction.

bins/revme/src/cmd/statetest/runner.rs, crates/interpreter/src/gas/calc.rs, crates/interpreter/src/instructions/i256.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/interpreter/shared_memory.rs, crates/primitives/src/bytecode.rs, crates/revm/src/evm.rs, crates/revm/src/frame.rs, crates/revm/src/handler.rs
@DaniPopes [pointed out](https://github.com/bluealloy/revm/pull/1248#discussion_r1545338071) that we could use the `uint` macro to simplify the i256 tests. I didn't know this was possible; I like this a lot better. This is the primary change of the PR. There are also several small fixes which don't deserve their own PR.
* Fix some typos.
* Replace `50u64` with `50` for consistency.
* Rename `I256_MAX` to `MAX_POSITIVE_VALUE` for consistency.
* Add note to `next_multiple_of_32` about `usize::MAX` not being a multiple of 32.
* Add some punctation in doc (`///`) comments and/or comments.
=> nit: use uint macro & fix various small things

bins/revm-test/src/bin/analysis.rs, crates/interpreter/src/instructions/bitwise.rs
This PR does the following:
* Add tests for shift operations (`shl`, `shr`, `sar`) from [EIP-145](https://eips.ethereum.org/EIPS/eip-145).
* Replace instance `U256::from_limbs` with `uint!{}` macro, for readability.
* Ever so slightly optimize `sar` short-circuit check. This can be 255.
* Add some comments, one about how `.unwrap()` is safe.
In the tests, is this the best way to execute an EVM instruction?
Also, I can remove the test comments if it's too much. I just copy/pasted the values into the structs.
=> feat: add tests for shift instructions

crates/interpreter/src/host.rs, crates/interpreter/src/instructions/arithmetic.rs, crates/interpreter/src/instructions/bitwise.rs, crates/interpreter/src/instructions/control.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/host/call_helpers.rs, crates/interpreter/src/instructions/host_env.rs, crates/interpreter/src/instructions/memory.rs, crates/interpreter/src/instructions/opcode.rs, crates/interpreter/src/instructions/stack.rs, crates/interpreter/src/instructions/system.rs, crates/interpreter/src/interpreter.rs, crates/revm/src/inspector/handler_register.rs
This allows running the interpreter with `&mut dyn Host`.
Useful to have in contexts where generics are not possible (e.g. dynamic callbacks / FFI, etc.) or testing/benchmarking code.
This was only limited by the type system requiring the maybe-sized (`+ ?Sized`) bound on the `Host` generics.
=> feat(interpreter): test Host object-safety, allow `dyn Host` in instructions

crates/revm/src/context/inner_evm_context.rs, crates/revm/src/evm.rs, crates/revm/src/handler/mainnet/execution.rs, crates/revm/src/handler/mainnet/post_execution.rs
=> chore: add and use EvmContext::take_error

Cargo.lock, crates/revm/Cargo.toml, crates/revm/src/db.rs, crates/revm/src/db/alloydb.rs
Adds an alloy-powered `Database` implementation, which uses the alloy providers to fetch account info. This is the direct alloy equivalent for `EthersDB`.
This is blocked on:
=> feat(`db`): Introduce `alloydb`

.github/workflows/cachegrind.yml
Repo got removed: https://github.com/ATiltedTree/setup-rust
Switching to better option.
=> chore(ci): use more stable rust toolchain plugin

crates/interpreter/src/instructions/control.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/memory.rs, crates/interpreter/src/instructions/system.rs, crates/interpreter/src/interpreter/stack.rs, crates/revm/src/evm.rs
Avoids a branch and a load/store of the stack length in `*LOAD` opcodes.
This is usually optimized out, but the code ends up being less than optimal as the optimizer does not recognize that we're writing into the same slot / it can't make that assumption for some reason.
I also removed slice bound checks in CALLDATALOAD as they were not optimized out, see inline comments.
Snailtracer:
- before: 1'326'516'806
- after: 1'315'075'774 (-0.86%)
=> perf(interpreter): use `pop_top!` where possible

crates/interpreter/src/instructions/opcode.rs
Port the opcode `modifies_memory` macro from https://github.com/foundry-rs/foundry/blob/1281421e04144a8de0341f9cad9b623a012a74bf/crates/evm/core/src/opcodes.rs#L5-L25
Fixes #1263
=> Add the modifies_memory macro

Cargo.lock, crates/primitives/Cargo.toml
This allows forwarding of the `rand` flag to `alloy_primitives` to enable random APIs on the primitive types
=> feat: pass rand feature to alloy_primitives

bins/revme/src/cmd/statetest.rs, bins/revme/src/cmd/statetest/runner.rs
And other minor improvements for debugging purposes.
`--keep-going` will not abort execution at the first failure and instead count all the errors.
=> feat(revme): add --keep-going to statetest command

documentation/src/crates/revm/inspector.md
The feature you actually need to enable for `revm::inspectors::TracerEip3155` is `serde-json` and `std`, not `serde`.
https://github.com/bluealloy/revm/blob/1edfeb6893a4b053170886a026eb5742c5561fa6/crates/revm/src/inspector.rs#L25-L26
=> docs(inspectors): change `serde` to `serde-json` for `TracerEip3155`

crates/interpreter/Cargo.toml, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml, crates/primitives/src/lib.rs, crates/revm/Cargo.toml
This allows re-exporting of `hashbrown`, even if the `std` feature flag is enabled.
=> feat: add flag to force hashbrown usage

Cargo.lock, crates/interpreter/Cargo.toml, crates/interpreter/src/function_stack.rs, crates/interpreter/src/gas.rs, crates/interpreter/src/interpreter.rs, crates/interpreter/src/interpreter/contract.rs, crates/interpreter/src/interpreter/serde.rs, crates/interpreter/src/interpreter_action.rs, crates/interpreter/src/interpreter_action/call_outcome.rs, crates/interpreter/src/interpreter_action/create_outcome.rs, crates/interpreter/src/interpreter_action/eof_create_inputs.rs, crates/interpreter/src/interpreter_action/eof_create_outcome.rs, crates/revm/src/frame.rs, crates/revm/src/journaled_state.rs
This commit make all structs under `FrameOrResult` serializable, which is useful when trying to save execution state inside an inspector during transaction execution.
The modified structs include:
* revm: `FrameOrResult`, `FrameResult`, `Frame`, `FrameData`, `CallFrame`, `CreateFrame`, `JournalCheckpoint`
* interpreter: `BytecodeLocked`, `Contract`, `Gas`, `CreateOutcome`, `CallOutcome`, `Interpreter`
=> feat(revm): make `FrameOrResult` serializable

bins/revme/src/cmd/statetest/runner.rs
This allows statetest to be run on files that don't have a .json extension if test path is a single file path.
Fixes #1247
=> Drops check for .json when testing a single file

crates/interpreter/src/instructions/arithmetic.rs, crates/interpreter/src/opcode.rs
Wrapping doesn't make sense here, these should match the actual opcode name as defined in the yellow paper.
=> chore(interpreter): rename wrapping_* opcodes

crates/interpreter/src/instructions/system.rs, crates/primitives/src/bytecode.rs
CODESIZE and CODECOPY are disabled in EOF, so the EOF branch on the bytecode is not reachable.
codesize assembly diff:
=> perf(interpreter): remove EOF branch in CODE{SIZE,COPY}

crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/instructions/control.rs, crates/interpreter/src/instructions/data.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/instructions/stack.rs, crates/interpreter/src/instructions/system.rs
=> chore(interpreter): rename some macros

crates/interpreter/src/interpreter/analysis.rs, crates/interpreter/src/opcode.rs, crates/interpreter/src/opcode/eof_printer.rs, crates/primitives/src/bytecode/eof/types_section.rs, crates/revm/src/inspector/eip3155.rs
Based on https://github.com/bluealloy/revm/pull/1302
=> refactor: shrink OpCodeInfo and add more methods

crates/interpreter/src/interpreter.rs, crates/primitives/src/bytecode.rs, crates/primitives/src/bytecode/legacy.rs
We can return a reference to `Bytes` instead of cloning it.
Because this change has not been released yet, I also renamed it for consistency to just `fn bytes`.
=> chore: don't clone bytes in `Bytecode::bytes`

crates/interpreter/src/instructions/macros.rs, crates/revm/src/builder.rs
There is a duplicate `MemoryLimitOOG`, when it should be `MemoryOOG`.
Looks like this was never correct https://github.com/bluealloy/revm/commit/9b663bbccba6be2ba70dabb5479f994514d0f8c4
=> fix: return the correct error in resize_memory

Cargo.toml, crates/interpreter/src/interpreter/stack.rs, crates/interpreter/src/interpreter_action/call_inputs.rs
It was introduced by making `n` dynamic instead of constant
=> perf: remove bounds check in DUP, SWAP/EXCHANGE

Cargo.lock, crates/revm/Cargo.toml, examples/uniswap_v2_usdc_swap.rs
Related to https://github.com/bluealloy/revm/issues/1084 . This example  shows common use cases not covered by other examples.
=> Add uniswap V2 WETH-USDC swap example

Cargo.lock, crates/interpreter/Cargo.toml, crates/interpreter/src/opcode.rs
Add `FromStr` to `OpCode` as the inverse of `fn as_str`. I put it under a default feature because we need `phf` for the map, but the dependency might not be desired if this feature is not used.
=> feat: parse opcodes from strings

crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/opcode.rs, crates/primitives/src/constants.rs
Implements the changes for `BLOCKHASH` as outlined in [EIP-2935], and adds EIP-2935 constants.
This requires an external processing step to fill the contract's storage with data. See https://github.com/paradigmxyz/reth/pull/7818
Additionally, since `BLOCKHASH` now does an `SLOAD` internally, I pulled the `sload` logic into a reusable `sload!` macro.
[EIP-2935]:  https://eips.ethereum.org/EIPS/eip-2935
=> feat: implement EIP-2935

bins/revme/src/cmd/statetest/runner.rs, crates/interpreter/src/instructions/i256.rs, crates/interpreter/src/instructions/macros.rs, crates/revm/src/db/states/transition_account.rs, crates/revm/src/inspector/eip3155.rs
`cmp ..., 0; jne` * 3 -> `mov; or; or; je`
The compiler already does this for the saturated but maybe because it has an early return it didn't do it for this as well
=> perf(interpreter): branch less in as_usize_or_fail

bins/revme/src/cmd/statetest/runner.rs, crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/revm/src/db/states/transition_account.rs, crates/revm/src/inspector/eip3155.rs
`TooManyBlobs` enum does not have a blob count being processed in the tx and max blob count.
For example in anvil, ideally we'd like to show the error with these details here  - https://github.com/foundry-rs/foundry/blob/8766dc3e1f7a860bc75b4ebfc675dde3d02581fb/crates/anvil/src/eth/error.rs#L287
Change enum to `TooManyBlobs(usize, usize)`.
=> add blob_count and max_blobs to `TooManyBlobs` err enum

crates/revm/src/builder.rs, crates/revm/src/context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/evm.rs, crates/revm/src/handler.rs, crates/revm/src/handler/handle_types/execution.rs, crates/revm/src/handler/mainnet.rs, crates/revm/src/handler/mainnet/execution.rs, crates/revm/src/handler/register.rs, crates/revm/src/inspector/handler_register.rs
Allows for substituting the default interpreter execution.
=> feat: add a hook to optionally execute individual frames

crates/interpreter/Cargo.toml, crates/interpreter/src/lib.rs, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/lib.rs, crates/revm/Cargo.toml, crates/revm/src/journaled_state.rs, crates/revm/src/lib.rs
shuffling some lints
Ref to: https://github.com/bluealloy/revm/pull/892
=> chore: refactor lints

bins/revme/src/cmd/evmrunner.rs
=> feat: add trace option in `revme evm`

crates/precompile/src/lib.rs
Ref https://github.com/bluealloy/revm/issues/1268
This PR updates the precompiles spec for the Prague hardfork: the only new precompiles are BLS12-381-related from the [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) (see [hardfork EIP](https://eips.ethereum.org/EIPS/eip-7600)).
The implementation will be added in the next PR.
=> feat(precompile): add Prague hardfork specification

.github/workflows/ethereum-tests.yml, Cargo.lock, bins/revme/Cargo.toml, bins/revme/src/cmd/evmrunner.rs, crates/precompile/Cargo.toml, crates/precompile/src/bls12_381/g1.rs, crates/precompile/src/bls12_381/g1_add.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g1_mul.rs, crates/precompile/src/bls12_381/g2.rs, crates/precompile/src/bls12_381/g2_add.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/g2_mul.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/map_fp_to_g1.rs, crates/precompile/src/bls12_381/mod.rs, crates/precompile/src/bls12_381/msm.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bls12_381/utils.rs, crates/precompile/src/lib.rs, crates/revm/Cargo.toml
Ref https://github.com/bluealloy/revm/issues/1268
This PR implements the precompiles from [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537).
The [implementation](https://github.com/paradigmxyz/alphanet/blob/main/crates/precompile/src/bls12_381.rs) is from [Alphanet](https://github.com/paradigmxyz/alphanet). The only difference is that I organized all precompiles into separate files and put them under one `bls12_381` module.
=> feat(precompile): BLS12-381

README.md
@rakita I tried to make the description short, but concise. There is definitely a lot of confusion on what Trin/The Portal Network is trying to provide. I can share a few tweets people have made if you want :smile: 
Maybe I should have included the mission of Portal is to provide full json-rpc access distributed with archival geth level access and of course as light as possible? not sure.
Anyways I hope the description I wrote it good, let me know if anything comes up.
=> chore: add Trin to used by list

crates/revm/src/handler/mainnet/pre_execution.rs
Preload blockhash storage address so it does not panic on access in JournalState.
Behavior in EIP is undefined, and we would prefer if preloading stays.
fixing https://github.com/bluealloy/revm/issues/1388 panic
=> fix(eip2935): Preload blockhash storage address

crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/instructions/contract/call_helpers.rs
=> chore: Remove Host constrain from calc_call_gas

crates/interpreter/src/instructions/macros.rs
=> chore: pop_address should use crate scope

crates/primitives/src/specification.rs
Closes https://github.com/bluealloy/revm/issues/1399
=> fix(primitives): specify the optimism cfg on spec_to_generic

crates/interpreter/src/gas/calc.rs, crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/opcode.rs, crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/revm/src/handler/mainnet/validation.rs
ref to: https://github.com/ipsilon/eof/pull/76
=> feat(EOF): remove TXCREATE

crates/interpreter/src/instructions/control.rs, crates/interpreter/src/interpreter.rs, crates/primitives/src/bytecode/eof/types_section.rs
Adding stack checks for CALLF/JUMPF:
https://github.com/ipsilon/eof/blob/main/spec/eof.md
`if 1024 < len(stack) + types[idx].max_stack_height - types[idx].inputs, execution results in an exceptional halt`
=> feat(EOF): Add CALLF/JUMPF stack checks

crates/interpreter/src/opcode.rs
previously added here https://github.com/bluealloy/revm/pull/1270
got lost for some reason
=> feat: add Opcode::modifies_memory back

crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs
Don't pay for SLOAD.
Ref https://github.com/ethereum/EIPs/pull/8564
=> feat: adjust gas-costs for EIP-2935 BLOCKHASH

crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/opcode.rs, crates/primitives/src/constants.rs, crates/revm/src/handler/mainnet/pre_execution.rs
This reverts to commit 3e089f35ed2a98278ddbae8f5dd816ccc373fa31.
Ref to: https://notes.ethereum.org/@rudolf/2935-gas-cost
Option2 is chosen so these changes need to be removed.
=> Revert "feat: implement EIP-2935 (#1354)"

crates/interpreter/src/instructions/host.rs, crates/interpreter/src/opcode.rs, crates/primitives/src/constants.rs, crates/revm/src/handler/mainnet/pre_execution.rs
This reverts commit f07c0ef1c27d7a7a6b160849f4f2c88dcd843cfe.
=> Revert "Revert "feat: implement EIP-2935 (#1354)" (#1424)"

crates/interpreter/src/instructions/host.rs, crates/revm/src/context.rs
move code to the `Context::block_hash` and dont warm load storage if it is more than 256 blocks.
=> fix: blockchash for devnet-0 

crates/interpreter/src/interpreter/shared_memory.rs
I hit this panic while doing intensive tests with foundry
```
Message:  attempt to add with overflow
Location: /home/george/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-4.0.0/src/interpreter/shared_memory.rs:98
This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⋮ 7 frames hidden ⋮                               
8: core::panicking::panic::h44790a89027c670f
at <unknown source file>:<unknown line>
9: revm_interpreter::instructions::control::revert::h42b8d8e64679ada4
at <unknown source file>:<unknown line>
10: revm::inspector::handler_register::inspector_instruction::{{closure}}::h1d34c1afe43f7f83
at <unknown source file>:<unknown line>
11: …
```
=> fix(interpreter): avoid overflow when checking if mem limit reached

crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_msm.rs
This applies the same fix we use for the G2 MSM infinity points, for the G1 MSM operation.
=> fix(precompile): ignore infinity points in G1 MSM

crates/interpreter/src/instructions/bitwise.rs
Hey guys, this is my first contribution here, so nice to meet you. I was working on this [issue 1251](https://github.com/bluealloy/revm/issues/1251) 
Motivation:
Investigate the performance of the BYTE, SHL, SHR and SAR OPCODEs and try to improvement 
Solution:
The improvements I've tried to apply in the resulting assembly were:
- reduced branching
- optimized memory access
- fewer instructions
I'm going to attach the before and after assembly for the opcode functions.
[Before](https://github.com/bluealloy/revm/files/15299221/byte-before.log)
[After](https://github.com/bluealloy/revm/files/15299220/byte-after.log)
[Before](https://github.com/bluealloy/revm/files/15299203/sar-before.log)
[After](https://github.com/bluealloy/revm/files/15299202/sar-after.log) …
=> chore(interpreter): optimisation for BYTE, SHL, SHR and SAR

crates/revm/src/optimism/handler_register.rs
Since the db may be a remote db, it could happen a network error under the db error. 
And when remote db error happen, the application level maybe need to retry it. So it's better to keep db error original rather than be a custom string.
Or just return another db error with extra error info?
=> feat: load account should return db error

crates/precompile/src/bls12_381/utils.rs
After closing https://github.com/bluealloy/revm/pull/1445, I decided to add docs to make sure the fact that we do not perform any Fr canonical checks is well-reasoned. This is actually specified in the EIP, so I decided to link it and annotate the code with the relevant part of the spec.
=> chore: add docs for BLS scalar input decoding

Cargo.lock, crates/revm/src/context.rs
As per https://github.com/ethereum/EIPs/pull/8577
Change explanation: https://github.com/bluealloy/revm/pull/1450#discussion_r1613301693
=> feat(revm): revert EIP-2935 BLOCKHASH opcode changes

Cargo.lock, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/precompile/src/secp256r1.rs, crates/primitives/src/specification.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/optimism.rs, crates/revm/src/optimism/handler_register.rs
* Upstream the RIP-7212: `secp256r1::P256VERIFY` precompile from the [alphanet implementation](https://github.com/paradigmxyz/alphanet/blob/a7f66d66cc59033fe8b5364cbc3a98825384d549/crates/precompile/src/secp256r1.rs)
* Add new Optimism Fjord hardfork spec before Prague
* Add the `P256Verify` to the chain precompiles post-fjord via the Optimism handle register
Note: Introduces new optional dependency on the `p256` crate
=> feat(optimism): Add secp256r1 precompile for Fjord

crates/interpreter/src/instructions/host.rs, crates/revm/src/db/states/state.rs
wrong block number used.
Introduced in https://github.com/bluealloy/revm/pull/1427/files in EF interop
Bug found here: https://github.com/holiman/goevmlab/issues/151
ty @holiman
=> fix(Interpreter): wrong block number used

crates/revm/benches/bench.rs
When trying to run the benchmarks it crashes due to a benchmarking group name conflict. 
This is because of a recent change to the Bytecode struct which removed the "Checked" type. The `bench_transact` function in `bench.rs` uses the group id 'transact/raw' for both benchmark steps. I removed the 'checked' bytecode benchmark which causes the conflict.
=> remove 'checked' bytecode bench causing benchmarks to crash due to conflict

crates/interpreter/src/instructions/host.rs, crates/primitives/src/result.rs, crates/primitives/src/state.rs, crates/revm/src/db/states.rs, crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/cache.rs, crates/revm/src/db/states/plain_account.rs, crates/revm/src/db/states/state.rs, crates/revm/src/journaled_state.rs
Rename type so it does not collide with revm::db::State
=> chore(primitives): rename State/Storage to EvmState/EvmStorage

crates/interpreter/src/instructions/contract.rs
From spec:
https://github.com/ipsilon/eof/blob/main/spec/eof.md
```
RETURNCONTRACT (0xee) instruction
loads uint8 immediate deploy_container_index
```
=> fix(EOF): returncontract immediate is one byte

crates/revm/src/inspector.rs, crates/revm/src/inspector/handler_register.rs
Implements TODO and adds integrates EOF handles in inspector
=> feat(EOF): Add EOF to inspector handle register

crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/instructions/system.rs
pop or pop_ret with 5 items was not used inside codebase. Either way it is a bug.
Added TODO comment for EOF returndataload, it should pad the output and not fail. This is recent behaviour change: https://github.com/ipsilon/eof/pull/90
=> fix(stack): pop with five items was not correct

crates/interpreter/src/interpreter.rs
Otherwise it's unusable because gas limit cannot be set after initialization.
=> chore(interpreter): use max gas limit in `impl Default for Interpreter`

crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/instructions/contract/call_helpers.rs, crates/interpreter/src/interpreter.rs, crates/interpreter/src/interpreter_action/eof_create_inputs.rs, crates/interpreter/src/interpreter_action/eof_create_outcome.rs, crates/primitives/src/bytecode/eof.rs, crates/primitives/src/bytecode/eof/header.rs, crates/primitives/src/result.rs, crates/revm/src/context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/evm.rs, crates/revm/src/frame.rs, crates/revm/src/handler/mainnet/execution.rs
=> feat(EOF): EIP-7698 eof creation transaction

crates/primitives/src/kzg/env_settings.rs
These are implemented on `KzgSettings` now so they can be derived
=> chore: derive PartialEq and Hash on EnvKzgSettings

crates/primitives/src/state.rs, crates/revm/src/journaled_state.rs
This PR modifies the logic of how `JournaledState` manages reverts for `AccountLoaded` and `StorageChange` journal entries. 
When reverting, instead of removing `Account` and `StorageSlot` entries from `State` we mark the entries as cold. As such if they are later loaded they will already be in journaled state mitigating the requirement to load them again from the database. When they are requested again they will be marked as warm. 
This is beneficial when finalizing the `JournaledState` object as it will include all accounts and storage slots which have been loaded during a transactions execution, regardless of whether they were reverted. This is a requirement for generating stateless witnesses. Currently the `PrestateTracer` does not include accounts and storage slots which have been …
=> Persist reverted account and storage slot lookups in `JournaledState`

crates/precompile/src/bls12_381/g1.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/pairing.rs
I was reviewing the new precompiles and noticed some stuff. This PR does the following:
* Fix a few typos.
* Replace g2 with g1 in `extract_g1_input`.
* Remove unnecessary type hint for `input_fps`.
* Rephrase comment about filtering points at infinity in the MSMs.
* I found the part about returning bytes a little confusing.
* We had to do the same thing in ckzg by the way 😢
These look great though. Didn't spot any real issues.
=> Fix some nits in bls12_381 precompiles

crates/precompile/benches/bench.rs
Adds the ecAdd precompile to the precompile benches
=> feat: add ecAdd to precompile bench

crates/revm/src/optimism/l1block.rs
Specifies the type of `1e12` as `u64` in the `l1block.rs` module, rather than a float literal, removing the need for `UintTryFrom<{float}>`. Certain environments, like the OP Stack's fault proof VMs, do not support floating point arithmetic.
=> fix(op): Remove `UintTryFrom<{float}>` dep in `l1block` module

Cargo.lock, crates/precompile/benches/bench.rs, crates/precompile/src/blake2.rs, crates/precompile/src/bls12_381.rs, crates/precompile/src/bls12_381/g1_add.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g1_mul.rs, crates/precompile/src/bls12_381/g2_add.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/g2_mul.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/map_fp_to_g1.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bn128.rs, crates/precompile/src/hash.rs, crates/precompile/src/identity.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/secp256r1.rs, crates/primitives/src/precompile.rs, crates/primitives/src/result.rs, crates/revm/src/builder.rs, crates/revm/src/context/evm_context.rs, documentation/src/crates/interpreter/interpreter_action.md
Support for : https://github.com/bluealloy/revm/issues/1435 https://github.com/bluealloy/revm/issues/1283
Additional PR will be made that would trigger `Fatal` error
=> feat(precompiles): fatal error for precompiles

crates/interpreter/src/host.rs, crates/interpreter/src/host/dummy.rs, crates/interpreter/src/instructions/host.rs, crates/primitives/src/bytecode.rs, crates/primitives/src/bytecode/eof.rs, crates/revm/src/context.rs, crates/revm/src/context/inner_evm_context.rs
Implement next lines of EOF spec: 
* When executed from a legacy contract, if the target account of EXTCODECOPY is an EOF contract, then it will copy up to 2 bytes from EF00, as if that would be the code.
* When executed from a legacy contract, if the target account of EXTCODEHASH is an EOF contract, then it will return 0x9dbf3648db8210552e9c4f75c6a1c3057c0ca432043bd648be15fe7be05646f5 (the hash of EF00, as if that would be the code).
* When executed from a legacy contract, if the target account of EXTCODESIZE is an EOF contract, then it will return 2.
https://github.com/ipsilon/eof/blob/main/spec/eof.md
closes https://github.com/bluealloy/revm/issues/1483
=> feat(EOF): EXTCODECOPY,EXTCODESIZE,EXTCODEHASH eof support

crates/interpreter/src/gas/constants.rs
https://github.com/ipsilon/eof/pull/80 change is here
=> fix(EOF): retf gas was changes

crates/interpreter/src/instructions/contract.rs
Added few TODOs and fixed the propagation of static call flag
=> fix(EOF): extstaticcall make static

crates/interpreter/src/instructions/data.rs
Added missing gas for copy operation of datacopy
=> fix(EOF): add DATACOPY copy gas

crates/interpreter/src/interpreter.rs
return value got changed from legacy calls.
```
0 if the call was successful.
1 if the call has reverted (also can be pushed earlier in a light failure scenario).
2 if the call has failed.
```
=> fix(EOF): ext*call return values

crates/revm/src/context/evm_context.rs, crates/revm/src/journaled_state.rs
Introduced here: https://github.com/bluealloy/revm/pull/1437
Found by @holiman
Fortunately, the bug was not included in Reth or in any release.
Done a few more renames.
=> fix(revm): remove storage reset that clears is_cold flag

crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/interpreter_action.rs, crates/interpreter/src/interpreter_action/eof_create_inputs.rs, crates/interpreter/src/lib.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/evm.rs, crates/revm/src/handler/handle_types/execution.rs, crates/revm/src/handler/mainnet/execution.rs, crates/revm/src/inspector.rs
=> chore: pluralize EOFCreateInput

crates/interpreter/src/instructions/bitwise.rs
Instead of implementing it ourselves.
=> chore(interpreter): use U256::arithmetic_shr in SAR

bins/revme/src/cmd/statetest/runner.rs, crates/interpreter/src/instructions/control.rs, crates/interpreter/src/instructions/data.rs, crates/interpreter/src/interpreter.rs, crates/primitives/src/bytecode.rs, crates/revm/src/context/inner_evm_context.rs
This is the [ISSUE](https://github.com/bluealloy/revm/issues/1488)
DaniPopes: EOF structure is present inside of Bytecode, and is cloned internally in AccountInfo and other places. It would improve performance to put behind an Arc to avoid cloning the underlying memory.
cc: @rakita @DaniPopes
=> feat(EOF): Put EOF bytecode behind an Arc

crates/revm/src/db/states/bundle_state.rs
This PR addresses Issue #1519 , let me know what do you think
Originally posted by @quentinv72 in https://github.com/paradigmxyz/reth/pull/8264#discussion_r1600570168
@rakita @gakonst 
Closes #1519
=> feat: mutable access for all fields in BundleBuilder

crates/revm/src/db/states/bundle_state.rs
Related https://github.com/paradigmxyz/reth/pull/8861/files#r1641783394
=> db: add setters to `BundleBuilder` with `&mut self`

crates/interpreter/src/instructions/contract.rs
target address is address of account that calls EOFCREATE
=> fix(EOF): target needed for EOFCREATE created address

crates/interpreter/src/instructions/contract.rs
This will trigger EOFCREATE frame
=> fix(EOF): set CallOrCreate result in EOFCREATE

Cargo.lock, crates/revm/Cargo.toml, crates/revm/src/db.rs, crates/revm/src/db/alloydb.rs, crates/revm/src/db/ethersdb.rs
I also ran cargo update, all the extra dependencies come from bumping `url` to 2.5.1
Closes #1529
Closes #1530
Closes #1531 
Closes #1532
=> feat: bump alloy, re-enable alloydb

crates/precompile/src/bls12_381/utils.rs, crates/precompile/src/lib.rs, crates/primitives/src/precompile.rs, crates/revm/src/context/context_precompiles.rs, crates/revm/src/context/evm_context.rs, crates/revm/src/handler/mainnet/pre_execution.rs, crates/revm/src/optimism/handler_register.rs
`Precompiles::new().clone().into()` would first clone the static default precompiles, then collect them into a new hashmap again in `ContextPrecompiles`. This shows up as about ~3% in `Evm::transact` profiles.
Avoid both cloning and collecting by using a CoW structure internally. This requires us to remove the `Deref` and `DerefMut` implementations as the internal type will be different depending on whether we have the default static precompiles, or a custom map. This should be fine as we can still support all necessary operations without exposing the underlying map type.
=> perf: avoid cloning precompiles

crates/revm/src/db/states/account_status.rs, crates/revm/src/db/states/bundle_account.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/reverts.rs
Need it for [Remote ExEx](https://reth.rs/developers/exex/remote.html) example to be able to send Reth's [`Chain`](https://github.com/paradigmxyz/reth/blob/01d81b4dccb6231ef65b121934540b47f9721c1f/crates/evm/execution-types/src/chain.rs#L24) over the network.
=> feat(revm): derive serde for `BundleState`

crates/interpreter/src/gas.rs, crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/instructions/contract/call_helpers.rs, crates/revm/src/context/inner_evm_context.rs
Deduct code deploy gas.
remove min stipend, will double check this in discord but evmone does not have it and it is not in main EOF repo. It was part of legacy eip-7069 that is why I added it.
=> fix(eof): eofcreate code deploy gas

crates/interpreter/src/interpreter/serde.rs
The manual implementations are not easy to maintain.
=> chore: simplify Interpreter serde

crates/primitives/src/db.rs
=> chore: remove DatabaseWithDebugError

.github/workflows/ci.yml, crates/revm/src/optimism/l1block.rs
* Add new CI step to check the no_std (riscv32) build with the `optimism` feature flag enabled.
* Refactors the `cargo check` CI steps to use a feature matrix.
=> chore: Add CI build target for no-std + optimism, use matrix builds

crates/interpreter/src/host.rs, crates/interpreter/src/host/dummy.rs, crates/interpreter/src/instructions/host.rs, crates/primitives/src/db.rs, crates/primitives/src/db/components.rs, crates/primitives/src/db/components/block_hash.rs, crates/revm/src/context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/db/emptydb.rs, crates/revm/src/db/ethersdb.rs, crates/revm/src/db/in_memory_db.rs, crates/revm/src/db/states/state.rs
Change the type of the number parameter in the block_hash methods of Host and Database from U256 to u64.
Closes #1423 
\cc @rakita @DaniPopes
=> refactor: replace U256 with u64 in BLOCKHASH

Cargo.lock, bins/revme/src/cmd/statetest/models/mod.rs, bins/revme/src/cmd/statetest/runner.rs, crates/interpreter/src/gas/calc.rs, crates/primitives/Cargo.toml, crates/primitives/src/bytecode/eof.rs, crates/primitives/src/bytecode/eof/header.rs, crates/primitives/src/env.rs, crates/primitives/src/lib.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/journaled_state.rs, examples/generate_block_traces.rs
The replaces the custom `AccessListItem` definition with the `alloy` version. The alloy version uses a `B256` instead of a `U256`, which is conform the Ethereum spec.
This avoids type conversions from when interacting with revm, where currently `B256` storage indices need to be converted to `U256` values using big-Endian conversion.
I think it's worth considering changing the account storage to match this.
=> refactor: replace AccessList with alloy version

crates/interpreter/src/gas/calc.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/db/alloydb.rs, crates/revm/src/handler/mainnet/pre_execution.rs, crates/revm/src/journaled_state.rs
fix compile and small refactor on load account
=> chore: fix compile for alloydb

crates/primitives/src/result.rs
makes it possible to transform the generic db error
=> feat: add helper function to mape EVMError's Database error variant

crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/contract.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/evm.rs
From EOF spec:
`No address trimming is performed on the target_address, and if the address has more than 20 bytes the operation halts with an exceptional failure.`
=> feat(EOF): Add target address expansion checks

crates/interpreter/src/instructions/contract.rs
target and caller were incorrectly set for ExtDelegateCall
=> fix(EOF): ExtDelegateCall caller/target switch

Cargo.lock, Cargo.toml, crates/interpreter/src/gas/calc.rs, crates/interpreter/src/gas/constants.rs, crates/primitives/Cargo.toml, crates/primitives/src/env.rs, crates/primitives/src/env/eip7702.rs, crates/primitives/src/result.rs, crates/revm/Cargo.toml, crates/revm/src/context/evm_context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/handler/mainnet/post_execution.rs, crates/revm/src/handler/mainnet/pre_execution.rs, crates/revm/src/handler/mainnet/validation.rs, crates/revm/src/journaled_state.rs
Waiting for https://github.com/alloy-rs/alloy/pull/950
=> feat(Prague): Add EIP-7702

bins/revme/Cargo.toml, crates/revm/src/db/alloydb.rs, crates/revm/src/db/ethersdb.rs
=> chore: store tokio::runtime::Handle in ethers/alloyDB

crates/interpreter/src/host/dummy.rs
Return a dummy result instead of panicking.
I've also simplified `sstore`.
=> feat: support selfdestruct for dummyhost

crates/revm/src/db.rs, crates/revm/src/db/alloydb.rs, crates/revm/src/db/ethersdb.rs, crates/revm/src/db/utils.rs
Following advice from @DaniPopes, this PR introduce `HandleOrRuntime` for both `EthersDB` and `AlloyDB` to avoid creating runtime for every call. Compared to #1557, this implementation also allows synchronous code to continue using both implementation by calling `AlloyDB::with_runtime(..., ..., new_current_thread())`, which reduces break changes.
This PR shall address the concerns of @DaniPopes while keeping the compatibility.
- If we are already in a tokio runtime, like foundry, the handle will be perfectly valid, and no runtime is created.
- If we are in synchronous code, users are responsible for creating the runtime only _once_ for `with_runtime`.
Note with this PR, we could also support current thread runtime now.
=> Use HandleOrRuntime to allow alloydb/ethersdb to hold a custom runtime

crates/interpreter/src/interpreter.rs, crates/interpreter/src/interpreter/contract.rs, crates/revm/src/context/inner_evm_context.rs
It's completely possible I am missing something, but I couldn't find a good way to access the address of the account which owns the bytecode being executed while using the Inspector::step hook. It would be really convenient if the contract stored on the interpreter also contained the bytecode address like the CallInputs it is constructed from do.
=> feat: add bytecode_address from CallInputs to Contract during construction.

Cargo.lock, crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/control.rs, crates/precompile/Cargo.toml, crates/precompile/src/fatal_precompile.rs, crates/precompile/src/lib.rs, crates/primitives/src/result.rs
Throw a fatal error if `kzg` precompile is called without `c-kzg` feature enabled. This behaviour can always be overwritten with a handler builder.
Rename back `InvalidEFOpcode` to `InvalidFEOpcode`
There is 0xFE INVALID opcode https://github.com/ethereum/yellowpaper/pull/230
=> feat(Precompiles): Throw fatal error if c-kzg is disabled

crates/primitives/src/precompile.rs, crates/revm/src/builder.rs, crates/revm/src/context/context_precompiles.rs, documentation/src/crates/revm/builder.md
The comments refer to the relevant arguments as gas limit
```rust
/// Stateful precompile that is Arc over [`ContextStatefulPrecompile`] trait.
/// It takes a reference to input, gas limit and Context.
ContextStateful(ContextStatefulPrecompileArc<DB>),
```
but the source names the argument `gas_price`
```rust
pub trait ContextStatefulPrecompile<DB: Database>: Sync + Send {
fn call(
&self,
bytes: &Bytes,
gas_price: u64,
```
My understanding is that gas price is not relevant to precompiles in general, just gas limit. In which case the variable name `gas_price` is incorrect.
Thanks!
=> chore: Rename gas_price to gas_limit for precompile args

crates/revm/src/context/evm_context.rs
Current revm try to load bytecode just after depth check, but there are some conditions the code is not needed:
- insufficient balance to transfer
- call to a precompile address
As long as the code is not needed, the database provider may not have corresponding code, like in our implementation scroll-tech/stateless-block-verifier#15 use this as an optimization.
=> chore(revm): defer bytecode load

Cargo.lock, crates/interpreter/Cargo.toml, crates/precompile/Cargo.toml, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/env.rs, crates/primitives/src/kzg.rs, crates/primitives/src/kzg/env_settings.rs, crates/primitives/src/kzg/trusted_setup_points.rs, crates/primitives/src/lib.rs, crates/revm/Cargo.toml
Currently, `revm` uses `c-kzg` for KZG point evaluation. It would be useful to have a `[no_std]` endpoint for this, which [`kzg-rs`](https://github.com/0xWOLAND/kzg-rs) can be used for.
=> feat: use `kzg-rs` for kzg point evaluation

crates/revm/src/context/evm_context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/journaled_state.rs
`warm_preloaded_addresses` was used for create collision check. That made sense when it was the list of precompile addresses but with new usage, this is incorrect.
Moves creating of frame from inner context to Context.
=> chore: Refactor code, and check if precompile for create collision

crates/interpreter/src/gas/constants.rs, crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/interpreter.rs
Add static check for EXTCALL.
MIN_CALLEE_GAS check should be a light failure and callee, not on the caller.
=> fix(EOF): MIN_CALLEE_GAS light failure, static-mode check

crates/revm/src/handler/mainnet/pre_execution.rs
=> refactor: load_account -> warm_preloaded_addresses

crates/primitives/src/env.rs
Makes sure `kzg_settings` is still in `CfgEnv` even if the `kzg-rs` feature is used.
=> fix: missing kzg_settings if kzg-rs feature enabled

bins/revme/src/cmd/evmrunner.rs, bins/revme/src/cmd/statetest/runner.rs, crates/primitives/src/bytecode.rs, crates/primitives/src/bytecode/eof.rs, crates/revm/src/builder.rs
`Bytecode::new_raw` now support EOF bytecode and will panic on invalid EOF code. In most cases, the validity of EOF is not questioned as validity is checked inside EVM.
An alternative safe function `new_raw_checked` was added that returns `EofDecodeError` if an invalid EOF bytecode can happen.
`Bytecode::new_legacy` to force legacy bytecode.
=> feat(EOF): Bytecode::new_raw supports EOF, new_raw_checked added

crates/revm/src/builder.rs, crates/revm/src/handler.rs, crates/revm/src/handler/register.rs
When using `append_handler_register_box` Rust was always assigning the static lifetime to the `Box`, which is the default behaviour of Rust when a lifetime is not specified.
This change allows custom lifetimes for the box.
=> fix: allow non-static lifetime in HandleRegisterBox

crates/revm/src/context/evm_context.rs
https://github.com/bluealloy/revm/pull/1600 introduced small changes to nonce handling during eofcreate which resulted in incremented nonce being used for address calculation when `TxEnv` does not include nonce.
=> fix: correctly calculate eofcreate address

Cargo.lock, Cargo.toml, crates/primitives/Cargo.toml, crates/primitives/src/env/eip7702.rs, crates/revm/Cargo.toml
Backported the `RecoveredAuthorization` to minimize breaking changes.
Another option considered is to have: `Recovered(Vec<Option<RecoveredAuthorization>>), in place of `Recovered(Vec<RecoveredAuthorization>),` but this loses information on invalid Authorization that some hooks/handler/inspector maybe want to have.
=> chore: bump alloy deps

crates/interpreter/src/instructions/system.rs
As per the spec:
> if offset + 32 > len(returndata buffer) the result is zero-padded (same behavior as CALLDATALOAD)
Doesn't matter if 1 above or 2^255 above the length, it's always zero-padded
=> fix(eof): don't fail if offset overflows `usize` in `RETURNDATALOAD`

crates/primitives/src/bytecode.rs, crates/revm/src/context/evm_context.rs, crates/revm/src/context/inner_evm_context.rs
=> chore(EOF): Use Bytecode::new_legacy

crates/interpreter/src/interpreter/analysis.rs, crates/primitives/src/bytecode/eof.rs, crates/primitives/src/bytecode/eof/body.rs
=> perf(eof): avoid some allocations

crates/interpreter/src/interpreter.rs, crates/primitives/src/state.rs, crates/revm/src/handler/handle_types/post_execution.rs, examples/fork_ref_transact.rs, examples/generate_block_traces.rs
- chore: fix some typos
- chore: remove useless Arc::clone
=> chore: fix some typos & remove useless Arc::clone

crates/precompile/src/bn128.rs
We are currently not taking advantage of the batch pair operation from the `bn` library for the pairing check precompile.
This yields a ~27% speedup on the existing bench:
```
Crypto Precompile benchmarks/precompile bench | ecpairing precompile
time:   [2.2389 ms 2.2441 ms 2.2495 ms]
change: [-27.689% -27.469% -27.227%] (p = 0.00 < 0.05)
Performance has improved.
```
=> feat: use batch bn256 pair operation

crates/interpreter/src/interpreter/analysis.rs, crates/primitives/src/bytecode/eof/types_section.rs
Error if RETF is found in non-returning code section
Error if JUMPF is calling a section that is different container kind (CodeType) that present section.
=> feat(EOF): Add non-returning CALLF/JUMPF checks

bins/revme/src/cmd.rs, bins/revme/src/cmd/eofvalidation.rs, crates/interpreter/src/interpreter/analysis.rs
Fixing last commit and confirming this rule in EOF spec:
```
section type has 0x80 as outputs value, and is non-returning, if and only if this section contains neither RETF instructions nor JUMPF into returning (outputs <= 0x7f) sections.
* in particular, section having only JUMPFs to non-returning sections is non-returning itself.
```
=> fix(EOF): returning to non-returning jumpf, enable validation error

bins/revme/src/cmd/bytecode.rs, crates/interpreter/src/interpreter/analysis.rs
Update `revme` so that when `bytecode` is called without arguments it goes into the standard
=> Add EOF Layout Fuzz Loop to `revme bytecode`

crates/interpreter/src/instruction_result.rs
Minor updates to the `InstructionResult` docs.
Related to https://github.com/foundry-rs/foundry/issues/7463
=> docs: improve `InstructionResult` documentation

crates/precompile/src/bn128.rs, crates/precompile/src/lib.rs, crates/primitives/src/specification.rs, crates/revm/src/optimism.rs, crates/revm/src/optimism/bn128.rs, crates/revm/src/optimism/handler_register.rs
Adds new Optimism Granite hardfork definition following Fjord. This hardfork limits the input size of the bn256Pairing precompile to 112687, as can be seen in the [op-geth implementation](https://github.com/ethereum-optimism/op-geth/pull/353/files#diff-6c5afc88291802d83222598cb31cd97f35db855a1b62358c1c6379228b182850R160)
=> Add OP-Granite hardfork, limiting bn256Pairing input size

Cargo.lock
Reverts bluealloy/revm#1680
crate fails to compile
=> Revert "chore(deps): bump alloy-provider from 0.2.0 to 0.2.1"

crates/revm/src/handler/mainnet/pre_execution.rs
> 4. Verify the code of authority is either empty or already delegated.
The negation of "either empty **or** already delegated" is "not empty **and** not already delegated".
=> fix(eip7702): fix empty or eip7702 code check

crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/state.rs, crates/revm/src/db/states/transition_state.rs
Closes #1710 and closes #1709 
contains some other drive-by doc improvements
=> doc: update some docs related to state

crates/precompile/src/blake2.rs
Go-ethereum always check gas before checking the detailed flag in [1]:
```go
func RunPrecompiledContract(p PrecompiledContract, input []byte, suppliedGas uint64, logger *tracing.Hooks) (ret []byte, remainingGas uint64, err error) {
gasCost := p.RequiredGas(input)
if suppliedGas < gasCost {
return nil, 0, ErrOutOfGas
}
if logger != nil && logger.OnGasChange != nil {
logger.OnGasChange(suppliedGas, suppliedGas-gasCost, tracing.GasChangeCallPrecompiledContract)
}
suppliedGas -= gasCost
output, err := p.Run(input)
return output, suppliedGas, err
}
```
[1]https://github.com/ethereum/go-ethereum/blob/941ae33d7e0b36afc2f8551884f555d963de7c6b/core/vm/contracts.go#L190-L206
Therefore, when the final flag is invalid (neither 1 nor 0) in blake2 precompile, and the gas limit is below the minimum …
=> chore: switch gas check order in blake2 precompile

documentation/src/crates/interpreter/memory.md, documentation/src/crates/primitives/bits.md, documentation/src/crates/primitives/kzg.md
Hello
While looking through your docs I found and fixed several spelling issues.
Br, Elias.
=> docs: fix spelling issues

.github/workflows/ci.yml, Cargo.lock, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml
`kzg-rs` version 0.2.1 allows for compiling on `riscv` architecture.
=> chore: bump `kzg-rs` version

crates/primitives/src/constants.rs, crates/revm/src/context.rs, crates/revm/src/db/states/state.rs
if the artificially big number is set for the block number it will have different values on 32 and 64 systems if the number is 2^32 < N < 2^64
=> chore: cast block number to u64 and not usize

Cargo.lock, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml
- Build `g1.bin`, `g2.bin`, `roots_of_unity.bin` in `OUT_DIR`.
- Should not build binaries when building docs
=> chore: bump kzg-rs version

crates/revm/src/inspector/handler_register.rs
fix https://github.com/paradigmxyz/reth/issues/10554
If EIP-6780 is enabled and selfdestruct is called not in the same create transaction, then no `AccountDestroyed` event will be returned: 
https://github.com/bluealloy/revm/blob/cabd1d1abbe9a1c58ded7316f3f4756eaacba559/crates/revm/src/journaled_state.rs#L510-L519
but actually in that case we also need to log the selfdestruct event.
=> fix(inspector): always call selfdestruct if entry is made

crates/interpreter/src/function_stack.rs, crates/interpreter/src/instructions/arithmetic.rs, crates/precompile/src/hash.rs, crates/revm/src/context/context_precompiles.rs, crates/revm/src/db/states/account_status.rs, crates/revm/src/evm.rs
when running with `cargo check --release` with warning as below:
```
warning: elided lifetime has a name
--> crates/revm/src/context/context_precompiles.rs:98:72
|
98 |     pub fn addresses<'a>(&'a self) -> Box<dyn ExactSizeIterator<Item = &Address> + 'a> {
|                      -- lifetime `'a` declared here                    ^ this elided lifetime gets resolved as `'a`
|
= note: `#[warn(elided_named_lifetimes)]` on by default
```
=> chore: make clippy happy

bins/revme/src/cmd/statetest/runner.rs
Statetest if tracing is enabled would run on latest spec and not in one that is set in test.
=> fix: statetest json set spec_id

crates/interpreter/src/instruction_result.rs, crates/revm/src/handler/mainnet/post_execution.rs
This PR simplified the trait bound used in `SuccessOrHalt` to restrict it as little as possible.
=> refactor: simplify SuccessOrHalt trait bound

crates/revm/Cargo.toml, examples/deploy.rs, examples/uniswap_v2_usdc_swap.rs
Introduces an example about deploying raw bytecode with revm with storage operations as example, it includes:
=> feat(example): deploy bytecode from scratch

crates/primitives/src/state.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/plain_account.rs, crates/revm/src/db/states/reverts.rs
Closes #1777 by adding a non-consuming API for generating `StateChangeset`
There's some DRYing to be done.
=> feat: to_plain_state

CHANGELOG.md
release was done from `release/v44` branch
=> chore: release v44 bump main CHANGELOG

Cargo.lock, Cargo.toml, bins/revme/Cargo.toml, bins/revme/src/cmd/evmrunner.rs, bins/revme/src/cmd/statetest/runner.rs, crates/inspector/Cargo.toml, crates/inspector/src/customprinter.rs, crates/inspector/src/eip3155.rs, crates/inspector/src/gas.rs, crates/inspector/src/handler_register.rs, crates/inspector/src/inspector.rs, crates/inspector/src/lib.rs, crates/inspector/src/noop.rs, crates/optimism/Cargo.toml, crates/revm/Cargo.toml, crates/revm/src/lib.rs
cargo depgraph --no-default-features --workspace-only | dot -Tpng > graph.png
=> feat: Restructuring Part3 inspector crate

Cargo.lock, crates/specification/Cargo.toml, crates/specification/src/eip2930.rs, crates/specification/src/eip7702.rs
Re-work of #1723 , now that #1695 has been merged. 
Removes the dep on `alloy-eips` in `revm-specification` in favor of depending on `alloy-eip2930` and `alloy-7702`.
This should be a change only to the dep graph, as the types are already re-exports
=> chore: migrate off alloy-eips

crates/precompile/src/modexp.rs
Closes #1796.
Just replaces `PrecompileError` return variant.
=> fix: error type return on `modexp`'s exp overflow

crates/interpreter/src/gas/calc.rs, crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs, crates/wiring/src/result.rs
Currently reth's trace results 
Geth returns a special oog error when gasleft in sstore < 2300, https://github.com/ethereum/go-ethereum/blob/564b6161637fe7e7c28e7c10a1f1978a22861bd2/core/vm/gas_table.go#L184-L188, 
```go
func gasSStoreEIP2200(evm *EVM, contract *Contract, stack *Stack, mem *Memory, memorySize uint64) (uint64, error) {
// If we fail the minimum gas availability invariant, fail (0)
if contract.Gas <= params.SstoreSentryGasEIP2200 {
return 0, errors.New("not enough gas for reentrancy sentry")
}
```
so the trace result of reth's is differ to geth's, eg this tx: https://etherscan.io/tx/0x87a19142a638f981a923a6b76859cd4a6d443c430435a1aedf5c9cb35c955768
diff as below:
=> chore: add ReentrancySentryOOG for SSTORE

crates/interpreter/src/instruction_result.rs, crates/optimism/src/handler_register.rs, crates/revm/src/handler/mainnet/execution.rs
This allows usage of the macros in external crates without needing to include `InstructionResult` beforehand.
=> fix: make macro crate-agnostic

crates/precompile/src/lib.rs, crates/primitives/src/specification.rs
Adding a new hardfork `Holocene` to Optimism spec for supporting `Holocene` in op-reth.
https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/holocene/overview.md
Since reth depends on `9.0.2`, merging this commit to `release/v44` branch.
=> Add holocene to OP spec

Cargo.lock, crates/database/Cargo.toml, crates/database/interface/Cargo.toml, crates/database/interface/src/async_db.rs, crates/database/interface/src/lib.rs, crates/database/src/alloydb.rs, examples/block_traces/src/main.rs, examples/uniswap_get_reserves/src/main.rs, examples/uniswap_v2_usdc_swap/src/main.rs
Inspired by [AlloyDB](https://github.com/bluealloy/revm/blob/f8d8ae9520025593cb49cb5974a310d1ffbef8fc/crates/database/src/alloydb.rs), I created `DatabaseAsync` and `DatabaseAsyncRef` traits that are async versions of `Database` and `DatabaseRef`. They are accompanied by `WrapDatabaseAsync`, that handles most of the logic.
Portal network already uses almost identical implementation: [link](https://github.com/ethereum/trin/blob/721a7e297c4b4fa1c088bbb5cd98eafde6263878/trin-evm/src/async_db.rs).
_Note:_ First time contributing to this repo. Let me know if I'm doing something wrong, have to run some tests, etc.
=> feat: add support for async database

Cargo.lock, bins/revme/Cargo.toml, bins/revme/src/cmd/bench/analysis.rs, bins/revme/src/cmd/bytecode.rs, bins/revme/src/cmd/evmrunner.rs, crates/database/src/in_memory_db.rs, crates/database/src/states/bundle_account.rs, crates/database/src/states/bundle_state.rs, crates/database/src/states/cache_account.rs, crates/database/src/states/plain_account.rs, crates/database/src/states/state.rs, crates/database/src/states/transition_account.rs, crates/database/src/states/transition_state.rs, crates/interpreter/src/host/dummy.rs, crates/optimism/src/handler_register.rs, crates/primitives/Cargo.toml, crates/primitives/src/lib.rs, crates/revm/src/context/evm_context.rs, crates/revm/src/context/inner_evm_context.rs, crates/revm/src/journaled_state.rs, crates/state/src/lib.rs
The semantics of the "hashbrown" feature are the same, meaning that enabling it overrides std with hashbrown, as well as it being the default if std is not enabled.
See: https://github.com/alloy-rs/core/pull/743
=> chore(primitives): replace HashMap re-exports with alloy_primitives::map

Cargo.lock, crates/database/Cargo.toml, crates/revm/Cargo.toml, examples/block_traces/Cargo.toml, examples/block_traces/src/main.rs, examples/uniswap_get_reserves/Cargo.toml, examples/uniswap_v2_usdc_swap/Cargo.toml
bumps `alloy-provider` and other a couple other alloy deps to 0.4.2
=> chore: bump alloy to 0.4.2

crates/state/src/account_info.rs
Adds more docs for `AccountInfo` constructors and inlines the rest of its pub functions
=> chore: inline more `AccountInfo` fns and add docs

crates/interpreter/src/interpreter/stack.rs
used in https://github.com/paradigmxyz/revm-inspectors/pull/220
=> feat(interpreter): impl Clone for Stack

bins/revme/src/cmd/statetest/runner.rs, crates/precompile/src/lib.rs, crates/primitives/src/specification.rs, crates/revm/src/context/evm_context.rs, crates/revm/src/evm.rs
=> Rename PRAGUE_EOF to OSAKA

crates/bytecode/src/eof/printer.rs, crates/revm/src/builder.rs, crates/revm/src/handler.rs, crates/wiring/src/result.rs
- moves `printer` cfg flag to module level, instead of annotating every item in the module
- adds some missing imports to tests in `no_std`
- changes an impl from feature-gated `std::error::Error` to non-gated `core::error::Error`
=> Chore: some no_std cleanup

crates/precompile/src/secp256k1.rs
The same thing as https://github.com/bluealloy/revm/pull/1843 but for the `release/v50` branch
=>  perf(precompile): use secp256k1 global context for ecrecover 

crates/precompile/src/secp256k1.rs
Initializing a new `Secp256k1` instance ever ecrecover call ends up dominating execution time, because of the randomization. This now uses the global context, avoiding randomization overhead.
Samply profiles from https://share.firefox.dev/4hwBrXj
=> perf(precompile): use secp256k1 global context for ecrecover

crates/primitives/src/state.rs, crates/revm/src/db/states/bundle_state.rs, crates/revm/src/db/states/plain_account.rs, crates/revm/src/db/states/reverts.rs
Cherry picks this PR/commit to be introduced in the `v50` release. It's an useful feature we'd like to use once the next release is up along with the included version bumps :).
* feat: to_plain_state
* feat: extend to reverts
=> feat: reapply to_plain_state (#1778)

Cargo.lock, crates/interpreter/src/opcode/tables.rs, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/eip7702/authorization_list.rs, crates/revm/src/handler/handle_types/execution.rs, crates/revm/src/handler/handle_types/post_execution.rs, crates/revm/src/handler/handle_types/pre_execution.rs, crates/revm/src/handler/handle_types/validation.rs
This enum will no longer exist after https://github.com/alloy-rs/core/pull/796
Also fixed some clippy lints
=> chore: bump alloy-eip7702 and remove `Parity` re-export

crates/database/src/states/transition_account.rs
Found it in the hot path here:
=> perf(`TransitionAccount`): remove unneeded clone

Cargo.lock, crates/revm/Cargo.toml, crates/revm/src/optimism.rs, crates/revm/src/optimism/handler_register.rs, crates/revm/src/optimism/precompile.rs
=> perf: Add static Optimism precompiles for Fjord & Granite

crates/optimism/src/fast_lz.rs, crates/optimism/src/l1block.rs
Found `tx_estimated_size_fjord` in our block-building pipeline's hot path so had a look.
Apparently, it's taking a non-trivial 9% of the cake when `State::commit` takes 10% and `Evm::transact` itself only takes 38%.
This PR adds some info and constants around `tx_estimated_size_fjord`, and micro-optimizes it by removing redundant `U256` conversions. 91% of `tx_estimated_size_fjord` is still spent on `flz_compress_len` so we may need to optimize the current Rust port, or go with an Assembly binding.
=> chore: refactor `L1BlockInfo::tx_estimated_size_fjord`

crates/database/src/in_memory_db.rs
Adds a couple simple convenience functions for working with nested `CacheDb` instances. No particular motivation, just seemed like sensible things to have
=> feat: couple convenience functions for nested cache dbs

bins/revme/src/cmd/statetest/models/mod.rs, bins/revme/src/cmd/statetest/runner.rs, crates/primitives/src/env.rs, crates/primitives/src/result.rs, crates/primitives/src/utilities.rs
The only meaningful change is that the `calc_excess_blob_gas` func now takes `target_blob_gas_per_block` as input.
Check to make sure that tx blob num is smaller than the block blob num is removed, this needs to be checked on block level.
=> EIP-7742: Uncouple blob count between CL and EL

crates/interpreter/src/interpreter/ext_bytecode.rs
close https://github.com/bluealloy/revm/issues/1902
=> chore: make ExtBytecode pointer private

bins/revme/src/cmd/statetest/runner.rs, crates/handler/src/execution.rs, crates/handler/src/frame.rs, crates/optimism/src/handler/precompiles.rs, crates/precompile/src/lib.rs, crates/specification/src/hardfork.rs
=> chore: Rename PRAGUE_EOF to OSAKA

documentation/src/crates/revm/handler.md
Make CI pass, book still needs rewritting
=> chore: mdbook links check

crates/interpreter/src/interpreter.rs, crates/interpreter/src/interpreter/ext_bytecode.rs, crates/interpreter/src/interpreter/ext_bytecode/serde.rs, crates/interpreter/src/interpreter/input.rs, crates/interpreter/src/interpreter/loop_control.rs, crates/interpreter/src/interpreter/return_data.rs, crates/interpreter/src/interpreter/runtime_flags.rs
I tried to tackle https://github.com/bluealloy/revm/issues/1890
I am not sure this is correct. To my understanding the instruction_pointer is just a pointer and so i have replaced it with the program counter for serialization which i know is not the same but i also wonder what the value of that pointer is in a different context. To my understanding doing an absolute jump back to that offset should give us the correct instruction_pointer again when deserializing.
I probably need some guidance here, if this is too far from expecatiations please let me know i can also just let it go :)
In case this is correct i probably have to add a test where the instruction_pointer changes i.e a running execution. What is the best way to mock the host, do i have to implement a transaction, block etc. from …
=> implement serde for interpreter

crates/handler/src/frame.rs
=> feat: Removed create address collision check

crates/bytecode/src/bytecode.rs, crates/bytecode/src/eip7702.rs, crates/bytecode/src/eof.rs, crates/bytecode/src/eof/body.rs, crates/bytecode/src/eof/header.rs, crates/bytecode/src/eof/types_section.rs, crates/bytecode/src/legacy/analyzed.rs, crates/bytecode/src/legacy/jump_map.rs, crates/bytecode/src/legacy/raw.rs, crates/database/src/states/account_status.rs, crates/database/src/states/reverts.rs, crates/state/src/account_info.rs
=> feat(database): implement order-independent equality for Reverts

crates/optimism/src/handler/precompiles.rs, crates/optimism/src/spec.rs
Just adding `HOLOCENE` and `ISTHMUS` to `OpSpecId`.
It will be needed for https://github.com/ethereum-optimism/specs/discussions/373, and more precisely I would need it to be able to [handle Isthmus in op-reth](https://github.com/paradigmxyz/reth/blob/82af17068721ee8e6025b41279a15c55cd2a50b1/crates/optimism/evm/src/config.rs#L16).
Closes #1874
=> feat: add isthmus spec

crates/primitives/src/constants.rs
=> EIP-2935: Update HISTORY_STORAGE_ADDRESS

Cargo.lock, crates/context/interface/src/journaled_state.rs, crates/context/interface/src/result.rs, crates/context/src/context.rs, crates/context/src/journaled_state.rs, crates/database/interface/src/async_db.rs, crates/database/interface/src/empty_db.rs, crates/database/interface/src/lib.rs, crates/database/src/alloydb.rs, crates/database/src/states/state_builder.rs, crates/handler/interface/src/execution.rs, crates/handler/interface/src/frame.rs, crates/handler/src/frame.rs, crates/inspector/src/inspector.rs, crates/optimism/src/handler.rs, crates/revm/src/exec.rs, examples/database_components/Cargo.toml, examples/database_components/src/block_hash.rs, examples/database_components/src/lib.rs, examples/database_components/src/state.rs
There are few places were precompile addresses are needed, so we will copying them inside journal.
Additionally Database::Error is now requiring `std::error::Error`.
=> feat: expose precompile address in Journal, DB::Error: StdError

crates/handler/src/frame.rs, crates/interpreter/src/interpreter.rs, crates/interpreter/src/interpreter/ext_bytecode.rs, crates/interpreter/src/interpreter/ext_bytecode/serde.rs
Resolves https://github.com/bluealloy/revm/issues/1888
=> Add bytecode hash in interpreter #1888

documentation/src/crates/precompile.md, documentation/src/crates/primitives/kzg.md, documentation/src/crates/revm/builder.md
**There are 6 precompiles implemented in REVM → There are 7 precompiles implemented in REVM**
> The number of precompiles was corrected from 6 to 7, which is a factual correction as the list indeed contains 7 precompiles.
**a much more bigger scale → a much bigger scale**
> Justification: Fixed a grammatical error in the comparative form of the adjective. In English, you cannot use both "more" and the "-er" suffix simultaneously to form a comparative degree. It's correct to use either "more big" or "bigger", but not both. In this case, "a much bigger scale" is the correct form.
**It allows handle registers → It allows handler registers**
> Fixed a typo: "handle" was replaced with "handler", which is the correct technical term in this context.
**Functions from one stage are just renamed …
=> fix: Documentation Corrections and Clarifications

crates/revm/src/optimism.rs, crates/revm/src/optimism/handler_register.rs, crates/revm/src/optimism/l1block.rs
Adds the operator fee, as described in https://github.com/ethereum-optimism/design-docs/pull/81 and [this spec](https://github.com/ethereum-optimism/specs/pull/382/files).
Opeator fee is currently planned to be included in Isthmus.
=> feat: handle isthmus operator fee

crates/context/src/journaled_state.rs
I think there was a naming confusion here. Fixed it with using decr for decremented balance and incr for incremented balance.
=> Fix naming for incrementing and decrementing balance in transfer function

crates/context/src/journal_init.rs, crates/context/src/journaled_state.rs, crates/context/src/lib.rs
Resolves https://github.com/bluealloy/revm/issues/1879
=> Add helper functions that would create JournalInit from JournaledState #1879

crates/bytecode/src/eip7702.rs, crates/context/interface/src/host.rs, crates/context/interface/src/host/dummy.rs, crates/context/interface/src/journaled_state.rs, crates/context/src/context.rs, crates/context/src/journaled_state.rs, crates/handler/src/pre_execution.rs, crates/inspector/src/inspector_context.rs, crates/interpreter/src/gas/calc.rs, crates/interpreter/src/instructions/contract/call_helpers.rs, crates/interpreter/src/instructions/host.rs, crates/precompile/src/secp256k1.rs, crates/primitives/Cargo.toml, crates/specification/src/eip7702.rs, crates/statetest-types/src/test_authorization.rs
Initial commit: 
* https://github.com/bluealloy/revm/commit/d8ca097dd9b00343b59e8dd44f8e41a9d09d645d - feat: apply latest EIP-7702 changes (https://github.com/bluealloy/revm/pull/1850) (2 days ago)
* https://github.com/bluealloy/revm/commit/0c69ccd9d7c4f44354e158b243b799ad15a24054 - chore: eip7702 chainid u256 change (https://github.com/bluealloy/revm/pull/1950) (12 days ago)
ref to: https://github.com/bluealloy/revm/issues/1896
=> feat(eip7702): apply latest EIP-7702 changes, backport from v52

bins/revme/src/cmd/statetest/runner.rs, crates/context/interface/src/block/blob.rs, crates/context/interface/src/cfg.rs, crates/context/interface/src/result.rs, crates/context/src/block.rs, crates/context/src/cfg.rs, crates/handler/src/validation.rs, crates/specification/src/eip4844.rs, crates/statetest-types/src/env.rs
Adds BLOB_BASE_FEE_UPDATE_FRACTION_PRAGUE update
and bumps max blobs to 9 for Prague
Partial commit from: https://github.com/bluealloy/revm/commit/4e00f32dd562d6901c71324d068bba44a2ec9195 - EIP-7742: Uncouple blob count between CL and EL (https://github.com/bluealloy/revm/pull/1899) (3 days ago)
and this: https://github.com/bluealloy/revm/commit/12b0babcda7e7b01ee2cfa2357c25334b9c2c6bf - (origin/release/v51) feat: eip7691 fraction update (https://github.com/bluealloy/revm/pull/1900) (35 hours ago
ref: https://github.com/bluealloy/revm/issues/1896
=> feat(EIP-7840): Add blob schedule to execution client cfg

Cargo.lock, Cargo.toml, bins/revme/Cargo.toml, crates/bytecode/Cargo.toml, crates/interpreter/Cargo.toml, crates/optimism/Cargo.toml, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml, crates/revm/Cargo.toml, crates/specification/Cargo.toml, crates/statetest-types/Cargo.toml, publish.sh
align all version to the ones that are published
=> chore: align crates versions

bins/revme/src/cmd/statetest/runner.rs
closes https://github.com/bluealloy/revm/issues/1977
=> fix(revme): statetest remove redundant json output

bins/revme/src/cmd/statetest/runner.rs, bins/revme/src/main.rs
Additional lines are redirected to std output: https://github.com/bluealloy/revm/issues/1977
=> fix(revme): Statetest stop exec when print output is true

Cargo.lock, crates/precompile/Cargo.toml
Succinct recently updated to v4, which includes breaking changes to the zkvm. This bump makes kzg-rs useable in the new v4 release.
=> chore(precompiles): bump kzg.rs

Cargo.lock, Cargo.toml, examples/cheatcode_inspector/Cargo.toml, examples/cheatcode_inspector/src/main.rs
As discussed, adding an example that shows how to implement a Foundry-style Solidity test cheatcode inspector to make sure future changes account for this use-case.
=> feat(examples): add cheatcode inspector example

Cargo.lock, crates/database/Cargo.toml, crates/revm/Cargo.toml, examples/block_traces/Cargo.toml, examples/erc20_gas/Cargo.toml, examples/uniswap_get_reserves/Cargo.toml, examples/uniswap_v2_usdc_swap/Cargo.toml
The alloy ecosystem versions are fast paced, in this PR I propose an update 
to bring `revm` in line with `reth` and the current alloy version.
The motivation here is that reth is presently incompatible with the latest alloy
provider for simulation.
=> chore: bump alloy versions to match latest

crates/handler/src/validation.rs
Instance of https://github.com/bluealloy/revm/issues/1997
=> fix: deduplicate validate_initial_tx_gas API

crates/database/src/states/cache_account.rs
`pub fn account_info(&self)` lacks comment
=> chore: add comment for pub function and fix typo

crates/handler/interface/src/frame.rs, crates/handler/src/frame.rs, crates/handler/src/handler.rs, crates/inspector/src/inspector.rs, crates/inspector/src/inspector_context.rs
=> fix(Inspector): call handler functions

crates/bytecode/src/bytecode.rs, crates/bytecode/src/eof.rs, crates/bytecode/src/eof/body.rs, crates/handler/src/frame.rs, crates/inspector/src/eip3155.rs, crates/interpreter/src/interpreter/ext_bytecode.rs, crates/interpreter/src/interpreter_types.rs
Add (for eof) section and funcion depth fields, and make pc container relative instead of code section relative.
=> Add essential EIP-7756 tracing fields

crates/interpreter/src/instructions.rs
remove duplicate instructions (STOP, ADD) from instruction table
=> remove duplicate instructions

crates/primitives/src/lib.rs, crates/revm/src/context/inner_evm_context.rs
closes https://github.com/bluealloy/revm/issues/2004
=> Include EIP7702 address for extcodecopy

crates/context/interface/src/result.rs, crates/context/src/cfg.rs, crates/inspector/src/exec.rs, crates/optimism/src/api/inspect.rs, crates/optimism/src/api/into_optimism.rs, crates/optimism/src/context.rs
Adds default generics for `EvmError`, `ResultAndState`, `ExecutionResult`.
Removes CTX generic from `InspectEvm` and `InspectCommitEvm` as it's unused.
Removes `Spec: Into<SpecId>` bound from `CfgEnv` struct definition
=> chore: simplify some generics

bins/revme/src/cmd/statetest/runner.rs, crates/inspector/src/eip3155.rs
- Buffer stderr
- Allocate less
Closes https://github.com/bluealloy/revm/issues/2025.
=> perf: improve EIP-3155 tracer

crates/handler/interface/src/item_or_result.rs, crates/inspector/src/inspector.rs, crates/precompile/src/bn128.rs
frame_end is called twice in this setup.
https://github.com/bluealloy/revm/blob/03f84f3095c9c9b5cb2d216c65f0a9b1b4704826/crates/handler/src/handler.rs#L219-L245
Main execution loop will always call `frame_return_result` and `last_frame_result` so calling `frame_end` in those two places is enough
=> fix(Inspector): frame_end called multiple times

crates/inspector/src/inspector_context.rs, crates/optimism/src/l1block.rs, crates/optimism/src/transaction/abstraction.rs, examples/cheatcode_inspector/src/main.rs
We don't need a third DB generic as it's always available as `CTX::Database`
=> chore: remove unnecessary `InspectorContext` generic

crates/revm/src/db/ethersdb.rs
EthersDB::with_runtime and EthersDB::with_handle were added in v11 for reasons involving async. Unlike EthersDB::new, these two functions always fork the latest block (even when a historical block is specified). This commit fixes that.
=> fix ethersdb.rs forking

crates/revm/src/optimism/handler_register.rs, crates/revm/src/optimism/l1block.rs
This PR fixes 2 bugs:
- The refund wasn't divided by OPERATOR_FEE_SCALAR_DECIMAL
- The operator fee was badly taken into account when the input is empty. I added similar checks as L1 fee.
=> fix: operator fee not correctly called

bins/revme/src/cmd.rs, bins/revme/src/cmd/statetest/runner.rs, crates/optimism/src/handler/precompiles.rs, crates/optimism/src/spec.rs
Part of https://github.com/bluealloy/revm/issues/1896
Backports: https://github.com/bluealloy/revm/pull/2000
Fix a bug where ECOTONE, HOLOCENE and ISTHMUS was creating fjord precompiles.
And add blst prague precompiles for Isthmus
=> feat(op): Isthmus precompiles

crates/interpreter/src/gas.rs
- Replaced `overflowing_sub` with `checked_sub` for safer gas cost subtraction.  
- `overflowing_sub` required an explicit overflow check, while `checked_sub` directly prevents underflow without extra branching.  
- This avoids undefined behavior from potential underflow in `u64` arithmetic while maintaining performance.  
- While `i64` allows for a simple `< 0` check, using `i64` would require changing `self.remaining` from `u64`, which is not currently feasible.  
- If we could use `i64`, it would simplify out-of-gas checks (`remaining - cost < 0`), which is CPU-friendly.  
- However, since `self.remaining` is `u64`, `checked_sub` is the best alternative for preventing underflow while keeping performance high.  
- Some test cases may need to be updated if they assume `overflowing_sub` …
=> Check performance of gas with i64 #1884

crates/primitives/src/specification.rs, crates/revm/src/optimism/handler_register.rs, crates/revm/src/optimism/precompile.rs
Two fixes for upcoming isthmus hardfork.
=> fix(op-isthmus): missing granite precompiles and disable eof

crates/context/interface/src/cfg.rs, crates/handler/src/precompile_provider.rs, crates/revm/src/mainnet_exec_inspect.rs
* Cfg::Spec is clonable
* PrecompileProvider does not need Clone
* Evm is now generic over Precompiles. In future we could potentially do the same for Instructions.
=> chore: API cleanup

crates/optimism/src/api/builder.rs, crates/optimism/src/api/default_ctx.rs, crates/optimism/src/api/exec.rs, crates/optimism/src/handler.rs, crates/optimism/src/handler/precompiles.rs, crates/optimism/src/l1block.rs, crates/optimism/src/spec.rs
Removes `OpSpec` enum and uses `OpSpecId` directly 
Additionally derived `Default` on it
=> refactor: remove OpSpec

Cargo.lock, Cargo.toml, bins/revme/src/cmd/statetest/runner.rs, crates/context/Cargo.toml, crates/context/src/tx.rs, crates/revm/Cargo.toml, crates/revm/src/mainnet_exec_inspect.rs, crates/statetest-types/Cargo.toml, crates/statetest-types/src/test_authorization.rs, crates/statetest-types/src/transaction.rs, examples/block_traces/src/main.rs
Changes `access_list` and `authorization_list` fields of `TxEnv` to use types from alloy-eips.
I didn't touch the traits so they are still operating on tuples without locking to concrete eips types, allowing for future abstraction.
=> feat: integrate alloy-eips

crates/inspector/src/eip3155.rs
fixes https://github.com/bluealloy/revm/pull/2080/files
=> fix(tracer): Flush buffer

crates/inspector/src/inspector.rs
Bug that would crash inspectors if call returns right back from frame
=> fix: inspector when returning right away

crates/inspector/src/eip3155.rs
=> chore: remove unused generics from `TracerEip3155`

Cargo.lock, Cargo.toml, bins/revme/Cargo.toml, bins/revme/src/cmd/bench/burntpix.rs, crates/bytecode/Cargo.toml, crates/context/Cargo.toml, crates/context/interface/Cargo.toml, crates/database/Cargo.toml, crates/database/interface/Cargo.toml, crates/inspector/Cargo.toml, crates/interpreter/Cargo.toml, crates/optimism/Cargo.toml, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml, crates/revm/Cargo.toml, crates/specification/Cargo.toml, crates/state/Cargo.toml, crates/statetest-types/Cargo.toml, examples/block_traces/Cargo.toml, examples/block_traces/src/main.rs, examples/contract_deployment/Cargo.toml, examples/database_components/Cargo.toml, examples/erc20_gas/Cargo.toml, examples/uniswap_get_reserves/Cargo.toml, examples/uniswap_get_reserves/src/main.rs, examples/uniswap_v2_usdc_swap/Cargo.toml, examples/uniswap_v2_usdc_swap/src/main.rs
Required to make my life easier when updating dependencies
Cargo.lock diff is from disabling default features on alloy and removing ethers. I've tested examples still work.
Powered by cursor agent and manually checked by me
=> chore: move all dependencies to workspace

Cargo.lock, Cargo.toml, bins/revme/Cargo.toml, crates/database/src/alloydb.rs, crates/precompile/benches/bench.rs, crates/precompile/src/secp256k1/bitcoin_secp256k1.rs, examples/database_components/Cargo.toml, examples/database_components/src/lib.rs, examples/erc20_gas/Cargo.toml, examples/erc20_gas/src/main.rs, examples/uniswap_get_reserves/src/main.rs, examples/uniswap_v2_usdc_swap/Cargo.toml, examples/uniswap_v2_usdc_swap/src/main.rs
Unblocks https://github.com/paradigmxyz/reth/pull/14570
=> chore(deps): bump breaking deps

crates/handler/src/handler.rs
Right now this is defined but never called which results in tx cached values not being reset for op
=> fix: call `Handler::clear`

crates/precompile/src/secp256r1.rs
Hi! I updates the broken link in secp256r1.rs, replacing EIP-7212 with RIP-7212. The change reflects the proposal's evolution from an Ethereum Improvement Proposal (EIP) to a Rollup Improvement Proposal (RIP).
=> fix: update broken link secp256r1.rs

crates/database/src/states/bundle_account.rs, crates/database/src/states/state.rs, crates/database/src/states/state_builder.rs, crates/handler/src/frame.rs, crates/handler/src/handler.rs, crates/handler/src/precompile_provider.rs, crates/inspector/src/traits.rs, crates/optimism/src/bn128.rs, crates/optimism/src/handler/precompiles.rs, crates/precompile/src/blake2.rs, crates/precompile/src/bls12_381/g1_add.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_add.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/map_fp_to_g1.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bn128.rs, crates/precompile/src/hash.rs, crates/precompile/src/identity.rs, crates/precompile/src/interface.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/secp256r1.rs, examples/erc20_gas/src/main.rs
=> Nit: PrecompileErrors -> PrecompileError

crates/optimism/src/handler/precompiles.rs, crates/optimism/src/spec.rs
Closes https://github.com/bluealloy/revm/issues/2096
For consistency https://github.com/paradigmxyz/reth/pull/14582#discussion_r1961513101
For https://github.com/paradigmxyz/reth/pull/14582
=> Add Interop hardfork

crates/interpreter/src/gas.rs, crates/interpreter/src/instruction_result.rs
When I read the source code of revm, I find some wrong comment. So I fix them.
- fix wrong comment
- remove useless impl
=> chore: fix wrong comment & remove useless impl

bins/revme/src/cmd/bytecode.rs, bins/revme/src/cmd/eofvalidation.rs, crates/bytecode/src/bytecode.rs, crates/bytecode/src/eof.rs, crates/bytecode/src/eof/body.rs, crates/bytecode/src/eof/code_info.rs, crates/bytecode/src/eof/decode_helpers.rs, crates/bytecode/src/eof/header.rs, crates/bytecode/src/eof/verification.rs, crates/bytecode/src/legacy.rs, crates/bytecode/src/legacy/analysis.rs, crates/bytecode/src/legacy/analyzed.rs, crates/bytecode/src/legacy/jump_map.rs, crates/bytecode/src/legacy/raw.rs, crates/bytecode/src/lib.rs, crates/bytecode/src/opcode.rs, crates/bytecode/src/opcode/parse.rs, crates/context/interface/src/result.rs, crates/interpreter/src/instruction_result.rs, crates/interpreter/src/instructions/control.rs, crates/interpreter/src/interpreter/ext_bytecode.rs, crates/interpreter/src/interpreter_types.rs
EOF TypesSection renamed to CodeInfo to be more informative.
CodeType enum now has `Runtime` and `Initcode` values 
Docs for legacy and bytecode crate are updated.
=> docs: Bytecode crate

crates/interpreter/src/instructions/macros.rs
=> refactor: expose popn macros

crates/context/src/journaled_state.rs, crates/optimism/src/handler.rs
-  remove wrong `&mut`/`TODO`
- avoid useless `get_mut`
- delete empty file
=> chore: remove wrong `&mut`/`TODO`, and avoid useless `get_mut`

crates/optimism/src/handler/precompiles.rs, crates/optimism/src/spec.rs
Add OSAKA fork to OpSpecId so that EOF can be enabled from OpEvm
Additionally adds missing fork names
=> chore(op): Add osaka fork so EOF can be activated

crates/context/src/evm.rs
Closes: #2115 
Derives Debug to Evm and EvmData public api's as suggestede by @mattsse and @rakita.
Please review
=> Feat: add the debug impl for Evm and EvmData type

crates/database/interface/src/lib.rs, crates/database/interface/src/try_commit.rs
Adds a fallible version of `DatabaseCommit`. Idea came up while working [on this PR](https://github.com/init4tech/trevm/pull/85)
Basically, this would allow (e.g.) `Arc<ConcurrentState<Db>>` to be used concurrently for read-access across any number of EVMs (sharing memory cache resources), and then allow `Commit` access to the `BundleState` if and only if you have discarded all-but-one `Arc`. This would enable easier parallel simulation in rounds much easier
=> feat: TryDatabaseCommit

crates/database/CHANGELOG.md, crates/database/src/in_memory_db.rs
=> refactor(db): separate fields from `CacheDB` into `Cache`

crates/handler/src/frame.rs, crates/inspector/src/eip3155.rs, crates/inspector/src/gas.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/macros.rs, crates/interpreter/src/interpreter/loop_control.rs, crates/interpreter/src/interpreter_types.rs
This refactor allows borrowing either an immutable or mutable `Gas` for the `trait LoopControlTr`
=> refactor: add immutable gas API to LoopControl

crates/context/interface/src/transaction/alloy_types.rs
Adds support for `Vec<AccessListItem>` to use `AccessListTr`.
=> feat: implement AccessListTr for Vec

crates/context/src/cfg.rs, crates/optimism/src/api/default_ctx.rs
Introduces an API that allows construction of a `CfgEnv` with a `SpecId`. This is useful when using a `SpecId` type that doesn't implement `Default`.
The changes avoid duplication of default parameters by calling `with_spec` from `fn default`.
=> feat: add constructor with hardfork

crates/database/src/in_memory_db.rs, crates/handler/src/handler.rs, crates/inspector/src/inspector.rs, crates/optimism/src/evm.rs, crates/optimism/src/handler.rs
Fixes optimism case where deposit is experiencing a halt in execution, this case would still need to trigger minting of balance.
Added tests for deposit tx and halted deposit tx.
Additionally removed clear and end handlers and introduced `catch_error` that would clear inconsistent state or in optimism case handle deposit tx error.
=> fix(op): Handler deposit tx halt, catch_error handle

crates/database/src/in_memory_db.rs, crates/optimism/src/handler.rs
we should always use `primitives::HashMap` vs `primitives::hash_map::HashMap` as `hash_map::HashMap` might have different default hasher generic
this was changed in https://github.com/bluealloy/revm/pull/2131
=> fix: use correct HashMap import

crates/bytecode/src/legacy/analyzed.rs
as jumptable is saved to the next byte, and loaded with new length, checking exact len with bytecode can be problematic. This check was relaxed so that only bytes that are at least the size of the original length will be accepted.
=> fix: relax jumptable len check

Cargo.lock, crates/context/Cargo.toml, crates/context/interface/src/context.rs, crates/context/interface/src/journaled_state.rs, crates/context/src/cfg.rs, crates/context/src/journaled_state.rs, crates/interpreter/src/host.rs, crates/interpreter/src/instructions/block_info.rs, crates/interpreter/src/instructions/contract.rs, crates/interpreter/src/instructions/host.rs, crates/interpreter/src/instructions/tx_info.rs, crates/interpreter/src/interpreter.rs, crates/interpreter/src/lib.rs, crates/interpreter/src/table.rs, crates/specification/src/constants.rs
Standalone host traits fully decouples `ContextTr` from `Interpreter` and allows easier usage of Interpreter as a standalone component. 
Additionally, this PR does a cleanup from previous https://github.com/bluealloy/revm/pull/2112
=> feat: Standalone Host, remove default fn from context

crates/statetest-types/src/test_authorization.rs
this is a simple workaround to support both v and yParity for the test format
=> test: allow duplicate v and yparity in test files

bins/revme/src/cmd/bench/analysis.rs, bins/revme/src/cmd/bench/burntpix.rs, bins/revme/src/cmd/bench/snailtracer.rs, bins/revme/src/cmd/bench/transfer.rs, bins/revme/src/cmd/evmrunner.rs, bins/revme/src/cmd/statetest/runner.rs, crates/context/src/setters.rs, crates/handler/src/evm.rs, crates/handler/src/execution.rs, crates/handler/src/frame.rs, crates/handler/src/handler.rs, crates/handler/src/lib.rs, crates/handler/src/mainnet_builder.rs, crates/optimism/src/api/default_ctx.rs, crates/optimism/src/api/exec.rs, crates/optimism/src/evm.rs, crates/optimism/src/fast_lz.rs, crates/optimism/src/handler.rs, examples/contract_deployment/src/main.rs, examples/uniswap_get_reserves/src/main.rs, examples/uniswap_v2_usdc_swap/src/main.rs
Move EvmTr into `evm.rs`, rename `transact_previous` to `replay`
=> refactor: rename transact_previous to replay, move EvmTr traits

crates/context/src/journaled_state.rs
Prior to the activation of EIP-7702, the gas calculation for a transaction did not require the target account bytecode if an out of gas error was immediately determined. Thus, transactions failing instantly due to OOG did not necessitate bytecode availability.
Stateless witness provided via `debug_executionWitness `  like Geth won't include such bytecode causing revm reports this as an error.
=> fix: pre EIP-7702 does not need to load code

.config/zepter.yaml, .github/workflows/ci.yml, Cargo.lock, crates/bytecode/Cargo.toml, crates/context/Cargo.toml, crates/context/interface/Cargo.toml, crates/database/Cargo.toml, crates/database/interface/Cargo.toml, crates/handler/Cargo.toml, crates/inspector/Cargo.toml, crates/interpreter/Cargo.toml, crates/optimism/Cargo.toml, crates/precompile/Cargo.toml, crates/primitives/Cargo.toml, crates/revm/Cargo.toml, crates/state/Cargo.toml
Right now `std` and `serde` are not always correctly propagated. This PR fixes it and adds `zepter` CI job checking features propagation as we do in alloy and reth
=> fix: correctly propagate features

crates/handler/src/evm.rs, crates/handler/src/frame.rs, crates/handler/src/mainnet_builder.rs, crates/handler/src/precompile_provider.rs, crates/inspector/src/mainnet_inspect.rs, crates/inspector/src/traits.rs, crates/optimism/src/api/exec.rs, crates/optimism/src/evm.rs, crates/optimism/src/precompiles.rs, examples/erc20_gas/src/exec.rs
Right now `EthPrecompiles` and `OpPrecompileProvider` have a CTX generic and PhantomData. This is not neccesarry and is sometimes bad because we can't reuse the same provider object for different databases.
The PR adds `CTX` generic to `PrecompileProvider` trait instead and removes phantomdatas from those types.
Also, `OpPrecompileProvider` is renamed to `OpPrecompiles` to follow eth naming
=> refactor: remove CTX phantomdata from precompile providers

crates/handler/src/handler.rs, crates/inspector/src/inspector.rs
This removes `fn inspect_create_first_frame(` from inspector.
It renames `create_first_frame` to `first_frame_input` and `frame_init_first` to `first_frame_init`
=> feat: decouple first_frame_input in inspector

crates/database/interface/src/lib.rs, crates/inspector/src/eip3155.rs
Removed the `Copy` traits from the `WrapDatabaseRef` struct's derive attributes.
`WrapDatabaseRef` shouldn't own `Copy` traits.
=> fix: remove wrong Clone Trait in WrapDatabaseRef

bins/revme/src/cmd/evmrunner.rs, crates/inspector/src/gas.rs, crates/inspector/src/inspect.rs, crates/inspector/src/mainnet_inspect.rs, crates/optimism/src/api/default_ctx.rs, crates/optimism/src/api/exec.rs, examples/block_traces/src/main.rs, examples/cheatcode_inspector/src/main.rs
missed replay rename. found in https://github.com/bluealloy/revm/pulls
=> feat: rename inspect_previous to inspect_replay

Cargo.lock, crates/context/Cargo.toml, crates/context/interface/src/context.rs, crates/context/interface/src/lib.rs, crates/context/src/context.rs, crates/context/src/evm.rs, crates/context/src/lib.rs, crates/handler/src/evm.rs, crates/inspector/Cargo.toml, crates/inspector/src/inspect.rs, crates/inspector/src/mainnet_inspect.rs, crates/inspector/src/traits.rs, crates/optimism/src/api/exec.rs, crates/optimism/src/evm.rs
Integrate ContextSetter with EvmExecution as evm execution needs to know tx and block so we can execute multiple tx on one created evm.
Creating evm for only one tx has performance penalties.
=> feat: Add tx/block to EvmExecution trait

crates/context/interface/src/context.rs, crates/context/src/context.rs, crates/handler/src/frame.rs, crates/handler/src/handler.rs, crates/inspector/src/traits.rs, crates/interpreter/src/host.rs
Worldcoin uses a custom error inside Inspector to mark the transaction as invalid. To facilitate this use case we added `Custom(String)` error.
=> feat: add custom error to context

crates/optimism/src/evm.rs
Adds test for call to `bn128_pair` bailing early for too big inout size since granite
=> Add test for calling `bn128_pair` before and after granite

crates/optimism/src/precompiles.rs
Fixes typo in method name for constructing isthmus precompiles
=> fix(op-precompiles): fix method name typo

crates/bytecode/src/legacy/analyzed.rs, crates/bytecode/src/legacy/jump_map.rs
This fixes inconsistency with jumpmap always rounding len of bits to the last byte.
=> fix: JumpMap from_slice requires len

crates/optimism/src/evm.rs
Removes redundancy from op precompile tests
=> chore(op-test): Clean up precompile tests

crates/optimism/src/evm.rs
Adds test for checking that op tx calls correct precompile at address reserved for g1 add
=> test(op-precompiles): Add test for calling g1 add

crates/primitives/src/constants.rs
=> chore: remove blockhash windows const

crates/context/interface/src/transaction.rs, crates/context/interface/src/transaction/alloy_types.rs, crates/context/interface/src/transaction/eip2930.rs, crates/context/src/tx.rs, crates/handler/src/pre_execution.rs, crates/handler/src/validation.rs, crates/optimism/src/transaction/abstraction.rs
I wanted to use `&[AccessListItem]` inside `Transaction` but it was unable as you couldn't set a slice as the `type AccessList`. This limited the reusability of the API.
This change follows the same pattern as `type Authorization` to ensure maximum reusability. As a result, it should be possible to implement `trait Transaction` for any type of access list.
=> refactor: use AccessListItem associated type instead of AccessList

bins/revme/src/cmd/statetest.rs
ref: https://github.com/bluealloy/revm/pull/1754 replaced `structopt` with `clap`
updates deprecated #[clap(...)] attributes to their modern equivalents in clap 4.x.
logs:
```
warning: use of deprecated function `<cmd::statetest::Cmd as clap::Args>::augment_args::old_attribute`: Attribute `#[clap(...)]` has been deprecated in favor of `#[arg(...)]`
--> bins/revme/src/cmd/statetest.rs:19:7
|
19 |     #[clap(required = true, num_args = 1..)]
|       ^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated function `<cmd::statetest::Cmd as clap::Args>::augment_args::old_attribute`: Attribute `#[clap(...)]` has been deprecated in favor of `#[arg(...)]`
--> bins/revme/src/cmd/statetest.rs:22:7
|
22 |     #[clap(short = 's', long)]
|       ^^^^
warning: use of deprecated …
```
=> chore(revme): remove deprecated #[clap] attribute

crates/optimism/src/evm.rs
Add test for clalling g1 msm from op tx
=> test(op-precompiles): Add test for g1 msm

crates/precompile/src/bls12_381_const.rs
This PR adds some documentation for the BLS12-381 precompiles constants, in particular the ones related to the size of the inputs.
Currently in Draft because:
-  I have added a few TODOs related to some constants that seem to not be needed
-  I have added new lines between some constants and have not checked what is your preferred formatting rule 
- I have made an opinionated change to put all of the gas related constants together, whereas before they were interleaved with the cryptography related constants
=> chore: Add some documentation for the bls12-381 precompile constants

crates/optimism/src/evm.rs
=> test(op-precompiles): add bls12-381 g2 add and msm tests

crates/context/interface/src/result.rs, crates/handler/src/validation.rs, crates/interpreter/src/gas/calc.rs
This PR:
- adds rich error information for `InvalidTransaction::CallGasCostMoreThanGasLimit` and `InvalidTransaction::GasFloorMoreThanGasLimit`, such that we can inform the user - in the error message - about which values they should use to make their transaction valid.
- Splits off the `calculate_initial_tx_gas_for_tx` function so it can be reused
If approved, this PR should be applied after #2214, as it depends on the change made there.
=> feat: allow reuse of API for calculating initial tx gas for tx

crates/optimism/src/l1block.rs
Fixes deposit tx identifier to be the correct `0x7e` instead of `0x7f`.
=> fix: DepositTx Identifier is 126 (`0x7e`) not `0x7f`

crates/optimism/src/evm.rs
Add tests for calling bls12-381 pairing from OP tx
=> test(op-precompiles): Reuse tests for bls12-381 msm tests for pairing

.github/workflows/ethereum-tests.yml, bins/revme/src/cmd/eofvalidation.rs
Tests got broken with the newest suit, we didn't handle container kinds correctly
=> fix: correct eof kind in verification tests

crates/optimism/src/evm.rs
Add tests for map fp to g1 and map fp2 to g2
=> test(op-precompiles): Add tests for bls12-381 map fp to g

crates/precompile/src/bls12_381_const.rs
The G1/G2 scalar multiplication gas costs are specified in two different places in the EIP in two different ways.
They are equal when the first value in the discount table is equal to the MSM_MULTIPLIER. It is not the most robust way to check this invariant because you can compute the cost for G1/2_MUL in a more convoluted way. 
If a more convoluted way is chosen, then this test should start to fail.
What this means is that if we wanted to just change the cost for G1/2_MUL we would need to change the MSM_BASE_GAS_FEE. It was done this way because there is _some_ relationship between the cost for a scalar multiplication and the cost to do an MSM which is multiple scalar multiplications.
=> chore: Add invariant test for G1/G2 Scalar multiplication

crates/precompile/src/bls12_381/blst.rs
When an G1_MSM or G2_MSM is called with a single input, we can us the simpler scalar multiplication algorithm instead of the MSM algorithm.
=> chore: special case G1 and G2 scalar multiplication

crates/optimism/src/spec.rs, crates/primitives/src/hardfork.rs
This matches the way string to `SpecId` conversion is handled to [`OpSpecId`](https://github.com/bluealloy/revm/blob/main/crates/optimism/src/spec.rs#L44), causing errors when invalid hardfork names are provided.
=> refactor: make str to SpecId conversion fallible

crates/optimism/src/evm.rs, crates/precompile/src/bls12_381/g1_add.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_add.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/map_fp_to_g1.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bls12_381_const.rs, crates/precompile/src/bls12_381_utils.rs, crates/precompile/src/lib.rs
=> feat: Return Fatal error on bls precompiles if in no_std

crates/context/src/journaled_state.rs, crates/handler/src/frame.rs, crates/optimism/src/handler.rs
=> chore: remove wrong `&mut` and duplicated spec

crates/precompile/src/bn128.rs, crates/precompile/src/bn128/substrate.rs
This adds point_mul, point_add and read_scalar. They are implicitly in the public API of the bn254 curve.
=> chore: Add `g1_mul`, `g1_add` and `read_scalar` methods into substrate wrapper for bn128

crates/optimism/src/handler.rs, crates/optimism/src/transaction/abstraction.rs, crates/optimism/src/transaction/deposit.rs
Closes https://github.com/bluealloy/revm/issues/2213
=> chore(op): Remove redundant trait `DepositTransaction`

crates/optimism/src/handler.rs
Adds test coverage for error variant `OpTransactionError::HaltedDepositPostRegolith`
=> test(op-handler): Add test for halted deposit tx post regolith

crates/precompile/src/bls12_381/blst.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bn128.rs
This PR avoids doing redundant work when the computation for the pairing or MSM will result in a no-op
=> chore: add early exit for no-ops in EIP1962 and EIP2537

Cargo.lock, crates/revm/src/optimism/handler_register.rs, crates/revm/src/optimism/l1block.rs
- Fixes deposit tx identifier to be `0x7E` instead of `0x7F`.
- Fixes the operator fee calculation. h/t @leruaa 🎉 
Action tests against the golang implementation are demonstrated to pass in https://github.com/op-rs/kona/pull/1277
=> fix(optimism): Operator Fee Calculation & Deposit Identifier

.github/workflows/book.yml, bins/revme/src/cmd/statetest/runner.rs, book/src/SUMMARY.md, book/src/architecture.md, book/src/awesome.md, book/src/dev.md, book/src/testing.md, crates/context/src/journaled_state/init.rs, crates/inspector/src/gas.rs, crates/inspector/src/handler.rs, crates/inspector/src/inspect.rs, crates/inspector/src/inspector.rs, crates/inspector/src/lib.rs, crates/inspector/src/mainnet_inspect.rs, crates/inspector/src/traits.rs, crates/optimism/src/api/exec.rs, examples/custom_opcodes/src/main.rs, examples/my_evm/src/api.rs
* _previous api was not renamed until now (aka `inspect_commit_previous` to `inspect_replay_commit`)
* Added docs for Inspector crate
* book cleaned up, some things removed, architecture part improved
* fixed unknown index.html in book.
=> feat: InspectEvm fn renames, inspector docs, book cleanup

crates/precompile/benches/bench.rs
This is a quick way to add benchmark for BN_MUL. 
It takes the first point from BN_ADD, and uses the x coordinate of the second point from BN_ADD as the scalar.
=> chore: Add MUL benchmark for EIP1962

crates/optimism/src/evm.rs, crates/precompile/src/lib.rs
Adds tests from https://github.com/bluealloy/revm/pull/2231/commits/ab3f5eb2dc9d94f6f3b2fa50dc0bb85cdc8b79bc that went missing when fixing merge conflicts
=> tests(op-precompiles): Add missing g2 add tests

crates/optimism/src/precompiles.rs
Adds test for checking that op default precompiles is updated to match latest `OpSpecId`
=> test(op-precompiles): Add test for checking that op default precompiles is updated

Cargo.lock, Cargo.toml, examples/cheatcode_inspector/src/main.rs
Updates the cheatcode inspector example to work with the latest repo version.
Providing a generic `PrecompileProvider` works now for all methods. 🎉 
The only thing that doesn't work is providing a generic `InterpreterTypes`, so `EthInterpreter` is hard-coded. This is not a blocker for any projects using a pattern similar to the cheatcode inspector example afaik.
=> chore: update cheatcode inspector example

bins/revme/src/cmd/bytecode.rs
- line 54 don't check `MAX_INITCODE_SIZE`
- use `validate_raw_eof_inner` to simplify `Eof::decode`+`validate_eof_inner`
=> refactor: update EOF validation logic and improve error handling

.github/workflows/ethereum-tests.yml, .gitignore, scripts/run-tests.sh
=> feat(ci): Integrate script in ci that downloads fixtures and runs the tests

bins/revme/src/cmd/bench.rs, bins/revme/src/cmd/bench/analysis.rs, bins/revme/src/cmd/bench/burntpix.rs
Reduce burntpix iteration count to 20_000, previous value of 500_000 was unnecessarily big.
Bumped default measurement time for revme bench
=> chore: bump bench time, and reduce burntpix iterations

crates/database/interface/Cargo.toml, crates/revm/Cargo.toml
=> Propagate asyncdb feature flag from database-interface to revm 

crates/handler/src/frame.rs, crates/handler/src/precompile_provider.rs, crates/optimism/src/precompiles.rs
To provide greater support for custom precompiles, it would be useful to pass `InputsImpl` and `is_static` to `PrecompileProvider::run` instead of only a subset of the fields passed as inputs to the Interpreter. There are some use cases for custom chains that inspect the caller or should not be allowed in a static context (state-changing precompiles).
=> feat: provide more context to precompiles

bins/revme/src/cmd/statetest.rs, bins/revme/src/cmd/statetest/runner.rs
Closes: #2307
Adds the path and json existence checks.
=> Chore: add check for path and existence existence

bins/revme/benches/evm.rs, bins/revme/src/cmd/bench.rs, bins/revme/src/cmd/bench/evm_build.rs
- This PR closes https://github.com/bluealloy/revm/issues/2308 by adding a benchmark to measures the how long the EVM build takes to initialization instructions via `evm.replay()` 
- the `build_mainnet` step was left out of the benchmark as to focus on time spent to initialize instructions.  Let me know if the intention was to include the `build_mainnet` into the benchmark as well, and I'll happily add it 🤙
=> chore: add criterion benchmark for evm build

crates/optimism/src/handler.rs
Corrects the current condition for operator fee refunds in trunk. Previously the check was using a source hash heuristic that wasn't correct - what we want is to not refund the operator fee for deposit transactions.
Also adds a test for expected refund behavior for both deposit transactions and normal transactions.
note - this bug isn't present in tag v64 (v19.7.0)
=> fix(isthmus): Correctly filter refunds for deposit transactions

crates/precompile/src/bls12_381_utils.rs
Since we now use arkworks-bls12-381 for no-std, this method is no longer needed
=> chore: Remove bls12-381 no-std fallback method

crates/precompile/src/bls12_381/arkworks.rs, crates/precompile/src/bls12_381/blst.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381_const.rs
This PR:
- Renames NBITS to SCALAR_LENGTH_BITS
- removes NBITS from the msm api -- its more of an implementation detail of blst and not of the msm api
=> chore: Remove TODO for NBITS and remove NBITS from blst MSM API

crates/state/src/lib.rs
Closes - #2354
Added methods to Account:
=> feat: Account helper builder functions

crates/optimism/src/transaction/deposit.rs
Smol change for 100% coverage of _optimism/src/transaction/deposit.rs_
=> test(op-tx): Cover `DepositTransactionParts` constructor in test

crates/interpreter/src/instructions/block_info.rs
Noticed that these fns already return a U256 so there should be no need to call convert here
=> chore: remove redundant U256 conversions in instructions

crates/interpreter/src/instructions/bitwise.rs, crates/interpreter/src/instructions/system.rs
The tests in `interpreter/src/instructions/bitwise.rs` and `interpreter/src/instructions/system.rs` are uncommented and updated to fit current code.
=> chore(test): uncommented bitwise.rs and system.rs tests

crates/optimism/src/precompiles.rs, crates/precompile/src/secp256r1.rs
I corrected `EIP` to `RIP` references in precompile documentation.
=> chore: fixed `EIP` to `RIP`

Cargo.lock, Cargo.toml
https://rustsec.org/advisories/RUSTSEC-2025-0023
https://github.com/tokio-rs/tokio/pull/7232
=> bump tokio version to fix sec issue

crates/handler/src/pre_execution.rs, crates/interpreter/src/gas/calc.rs
Skip touching access list if we have legacy transaction type.
Tx type needs to dictate what fields we are using, otherwise it is a footgun
=> fix: skip account list for legacy

crates/optimism/src/precompiles.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/pairing.rs
Adds input size limitations to the BLS12-381 G1/G2 MSM and pairing precompiles. This was originally started in https://github.com/bluealloy/revm/pull/2039, but looks to have been lost.
[Specification Reference](https://specs.optimism.io/protocol/isthmus/exec-engine.html#bls-precompiles)
=> fix(op-revm): Add input size limitations to bls12-381 {G1/G2} MSM + pairing

book/src/architecture.md
Hi! I fixed broken Rust documentation links in `architecture.md` that were pointing to outdated paths in the revm-handler crate. The API traits have been reorganized but the documentation references weren't updated accordingly.
=> chore: fixed broken links in `architecture.md`

crates/handler/src/frame.rs, scripts/run-tests.sh
We should load delegate before checking EOF EXTDELEGATECALL target.
=> fix(eof): extdelegate bytecode check after eip7702 load

README.md, book/src/architecture.md, book/src/awesome.md
Hi! I updated all outdated links that were pointing to `crates/optimism` and replaced them with `crates/op-revm`. This matches the recent directory change introduced in [revm#2415](https://github.com/bluealloy/revm/pull/2415).
=> chore: fixed broken link

crates/bytecode/src/legacy/analysis.rs, crates/bytecode/src/legacy/raw.rs
Refactors bytecode analysis to handle padding internally and improve safety. Adds comprehensive test coverage for various bytecode scenarios.
- `analyze_legacy` now handles padding internally and returns both jump table and padded bytecode
- Added early return for empty bytecode
- Improved safety documentation for unsafe pointer operations
- Added extensive test suite covering edge cases and padding scenarios
Added tests for:
- Empty bytecode
- JUMPDEST positions
- PUSH operations
- Invalid opcodes
- Padding scenarios
Closes #2414
=> feat(bytecode): improve legacy bytecode padding

crates/context/src/journal/inner.rs
`x = clone` -> `x.clone_from` when clearing the journal
=> perf: clone_from precompile addresses

Cargo.lock, crates/bytecode/Cargo.toml, crates/bytecode/src/legacy/analysis.rs, crates/bytecode/src/legacy/analyzed.rs, crates/bytecode/src/legacy/jump_map.rs, crates/state/src/account_info.rs
The `Bytecode::default` jump table doesn't need to contain any data. Even if it had to, we can still cache it with a singleton as it's an Arc, and then just clone the singleton every time we need a new default jump table.
Closes https://github.com/bluealloy/revm/issues/2436.
=> perf: cache and use JumpTable::default

Cargo.lock, Cargo.toml, bins/revme/src/cmd/statetest/runner.rs, crates/context/interface/Cargo.toml, crates/context/interface/src/lib.rs, crates/context/interface/src/transaction.rs, crates/context/interface/src/transaction/alloy_types.rs, crates/context/src/tx.rs, crates/handler/src/mainnet_builder.rs, crates/op-revm/src/transaction/abstraction.rs
Added lifetime to AccessList and AuthList, this would allow us more flexibility and it should not disrupt current usecases.
AuthList is now `Vec<Either<SignedAuthorizatio,RecoveredAuthorization>>` so we can recover signed upfront before execution starts.
=> feat(tx): Add Either RecoveredAuthorization

crates/context/src/local.rs
otherwise i get this error from reth:
```
error[E0308]: mismatched types
--> /home/fgimenez/.cargo/git/checkouts/revm-0a89e51b0ec51a84/f7693cc/crates/context/src/local.rs:22:31
|
22  |             initcode_mapping: HashMap::new(),
|                               ^^^^^^^^^^^^^^ expected `HashMap<FixedBytes<32>, Initcode, RandomState>`, found `HashMap<_, _>`
|
= note: `std::hash::RandomState` and `RandomState` have similar names, but are actually distinct types
note: `std::hash::RandomState` is defined in crate `std`
--> /home/fgimenez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/hash/random.rs:36:1
|
36  | pub struct RandomState {
| ^^^^^^^^^^^^^^^^^^^^^^
note: `RandomState` is defined in crate `foldhash`
--> …
```
=> fix: use HashMap::default in LocalContext

crates/interpreter/src/interpreter.rs
The implementation adds a where clause to ensure that IW::Output implements From<InterpreterAction> for proper type conversion, allowing custom output types to be used with the interpreter while maintaining backward compatibility.
=> Replace InterpreterAction with InterpreterTypes::Output

crates/bytecode/src/opcode.rs, crates/precompile/src/bls12_381/g1_msm.rs
`const`s get duplicated at all callsites so it's possible that multiple callers (in multiple crates) end up duplicating the array.
=> chore: make OPCODE_INFO a static

crates/handler/src/pre_execution.rs
Removes the spec id validation in `apply_eip7702_auth_list`.
=> feat: remove spec id verification for `apply_eip7702_auth_list`

crates/context/interface/src/cfg.rs, crates/handler/src/frame.rs, crates/interpreter/src/interpreter_action/create_inputs.rs
In [Linera](https://github.com/linera-io/linera-protocol), we use REVM to run EVM apps.
In our usage, it would be very nice if we could add a specific Custom address besides the `Create/Create2` classic possibilities. This would simplify the code a lot.
If needed, I can feature gate this possibility.
=> Add a custom address to the CreateScheme.

crates/bytecode/src/bytecode.rs, crates/bytecode/src/iter.rs, crates/bytecode/src/lib.rs
See also `OpcodesIter` in revmc which also returns the immediate byte slice: https://github.com/paradigmxyz/revmc/blob/c3e2a3c8331032cc3875bdfce27d4247e4c7facb/crates/revmc/src/bytecode/opcode.rs#L44
=> refactor: simplify opcode iter

crates/interpreter/src/interpreter.rs, crates/interpreter/src/interpreter/return_data.rs
As per our discussion the REVM telegram group, I am refactoring REVMC to support the latest REVM API (^20). These are desirable to be public so that I do not implement some other types that implement `WIRE::ReturnData` and `WIRE::Control` traits and keep it simple and consistent. Many thanks!
ref: paradigmxyz/revmc#76
=> [chore]: make ReturnDataImpl and LoopControlImpl public

crates/op-revm/src/spec.rs
Checks that default OP spec ID is updated after OP mainnet isthmus hardfork to next hardfork
Increase test coverage of _crates/op-revm/src/spec.rs_ from 30.51% to 32.79%
=> test(op): Add test for verifying default `OpSpecId` update

crates/handler/src/system_call.rs, crates/op-revm/src/api/exec.rs
It is more natural for target address to go first
=> feat: system_call switch order of inputs, address than bytes

CHANGELOG.md, Cargo.lock, Cargo.toml, MIGRATION_GUIDE.md, crates/revm/CHANGELOG.md, crates/revm/Cargo.toml
Bumped revm to major version as dependent crates have their major number bumped
=> bump: changelog tag v70, revm v23.0.0

examples/block_traces/src/main.rs
Should we ensure traces/ directory is created before writing?
When running the examples/block_traces example, it fails with the following error if the traces/ directory does not exist:
``` bash
thread 'main' panicked at examples/block_traces/src/main.rs:98:15:
Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
=> fix(examples/block_traces): ensure traces/ directory is created before writing

crates/op-revm/src/handler.rs
Currently, `op-revm` does not invoke `mark_touch` on the `validate_against_state_and_deduct_caller`. 
Adding this call will bring the behavior in line with [bluealloy/revm v71 (see handler/src/pre_execution.rs line 174).](https://github.com/bluealloy/revm/blob/v71/crates/handler/src/pre_execution.rs#L174)
=> fix(op): mark caller account as touched

crates/op-revm/src/handler.rs
Cleanup of local context (SharedMemory buffer) should be done on error.
=> fix(op): call cleanup on local context

crates/precompile/src/kzg_point_evaluation.rs
Hi! I fixed a dead link in the comment block of the `kzg_point_evaluation.rs` test module. The original URL was outdated and has been replaced with the correct link referencing updated test data.
ref: https://github.com/ethereum/c-kzg-4844/pull/572/files#diff-3b040e087b66564bb54ec02ea442619dd00ce6d050aaaf4a0c51c28850712c3d
=> chore: fixed dead link kzg_point_evaluation.rs

crates/primitives/src/hardfork.rs
https://etherscan.io/block/22431086
https://eips.ethereum.org/EIPS/eip-7600
I am reasonably sure this is the correct block given the first 7702 tx occurs in this block: https://etherscan.io/tx/0xb623d3815c31683104e6d43841fde1219ce2e202bef1d28d6ac28f05e838d779
Though `cast find-block 1746612311 --rpc-url <MAINNET_RPC_URL>` yields: `22431084`
1746612311 -> Wed May 07 2025 10:05:11 GMT+0000
would correspond with https://etherscan.io/block/22431084
=> chore: add Prague activation timestamp

.github/workflows/ethereum-tests.yml, bins/revme/src/cmd/statetest/runner.rs
Statetest have been moved from ethereu/tests to ethereum/legacytests repo: 
https://github.com/ethereum/tests/releases/tag/v17.1
=> ci(ethtests): Change legacy statetests repo

README.md
Wrap the `img.shields.io/crates/v/revm.svg` badge in a Markdown link to the crates.io page so that clicking the badge takes users directly to [https://crates.io/crates/revm](https://crates.io/crates/revm). This improves discoverability and provides an easy shortcut to the published crate.
=> docs: make crates.io version badge clickable

crates/context/src/tx.rs
resolves #2513
Example usage:
```
let tx_env = TxEnv::builder()
.caller(some_address)
.gas_limit(1_000_000)
.gas_price(50)
.gas_priority_fee(Some(2)) // Automatically sets type to EIP-1559
.build();
```
=> feat: add builder pattern for TxEnv

bins/revme/src/cmd/statetest/runner.rs, crates/context/interface/src/cfg.rs, crates/context/interface/src/transaction.rs, crates/context/src/cfg.rs, crates/handler/src/validation.rs
Closing https://github.com/bluealloy/revm/issues/2477
Have made this parameter optional as it only checks for the transaction blob len is not more than limi. It does not affect the gas calculations.
=> feat: make blob max number optional

crates/interpreter/src/gas.rs
All fields in Gas are not public. Add `memory` and `memory_mut()` to allow access to memory fields.
=> chore: add Gas::memory and memory_mut

Cargo.lock, crates/op-revm/Cargo.toml, crates/op-revm/tests/common.rs
Remove local revm/op-revm from `dev-dependencies` so it is unblocked for publishing
=> chore: op remove circular dep

crates/op-revm/Cargo.toml, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g1_add_input_wrong_size.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g1_add_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g1_msm_input_wrong_size.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g1_msm_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g1_msm_wrong_input_layout.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g2_add_input_wrong_size.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g2_add_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g2_msm_input_wrong_size.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g2_msm_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_g2_msm_wrong_input_layout.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_map_fp2_to_g2_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_map_fp_to_g1_input_wrong_size.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_map_fp_to_g1_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_pairing_input_wrong_size.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_pairing_out_of_gas.json, crates/op-revm/tests/testdata/test_halted_tx_call_bls12_381_pairing_wrong_input_layout.json, crates/op-revm/tests/testdata/test_halted_tx_call_bn128_pair_fjord.json, crates/op-revm/tests/testdata/test_halted_tx_call_bn128_pair_granite.json, crates/op-revm/tests/testdata/test_halted_tx_call_p256verify.json, crates/op-revm/tests/testdata/test_log_inspector.json, crates/op-revm/tests/testdata/test_tx_call_p256verify.json
add `preserve_order` and regenerate testdata jsons
=> chore(test): preserve order of fields in json fixtures

.github/workflows/bench.yml
Codspeed handles runs per commit so we can allow concurrency.
=> ci: remove concurrency from bench

crates/context/src/tx.rs, crates/database/interface/src/lib.rs, crates/database/src/in_memory_db.rs
=> feat: added TxEnv::new_bench() add util function

bins/revme/src/cmd/bench/transfer.rs, crates/context/interface/src/cfg.rs, crates/context/interface/src/result.rs, crates/context/interface/src/transaction.rs, crates/context/interface/src/transaction/transaction_type.rs, crates/context/src/cfg.rs, crates/context/src/tx.rs, crates/handler/src/validation.rs
closes https://github.com/bluealloy/revm/issues/2534
=> cfg: add tx_chain_id_check fields. Optimize effective gas cost calc

crates/database/src/states/cache_account.rs, crates/database/src/states/state.rs
I just learned in #2570, that the clone here could be avoided. Since the conversion is not used somewhere else I adapted it.
=> chore: Avoid clone before converting ref BundleAccount to CacheAccount

crates/context/interface/src/block.rs, crates/context/interface/src/block/blob.rs, crates/primitives/src/eip7918.rs, crates/primitives/src/lib.rs
Needed for statetest,
excess blob gas `excess_blob_gas` requires a lot of parent block fields and is usually calculated outside of revm.
=> chore: support functions for eip7918

bins/revme/src/cmd/bench/analysis.rs, bins/revme/src/cmd/bench/burntpix.rs, bins/revme/src/cmd/bench/gas_cost_estimator.rs, bins/revme/src/cmd/bench/snailtracer.rs, bins/revme/src/cmd/bench/transfer.rs, bins/revme/src/cmd/bench/transfer_multi.rs
I noticed the clone ending up in the profiles, instead we can probably use iter_batched here
=> chore: use iter_batched for transfer bench

crates/inspector/src/inspect.rs
[ticket](https://github.com/bluealloy/revm/issues/2591#issuecomment-2949600915)
Add inspect_finalize, same pattern as inspect_tx_finalize but this time the function take the tx + inspector and return ResultAndState which contains Self::ExecutionResult (result of the tx) and Self::State (the state).
=> feat(InspectEvm): add inspect_finalize method for tx+inspector with state

crates/precompile/src/modexp.rs
Ref https://github.com/ethereum/EIPs/pull/9855
=> feat(devnet2): modexp assume minimal base/mod length of 32

.github/workflows/bench.yml
--workspace builds all the examples with optimizations on which takes quite a bit in CI unnecessarily
=> chore: build less stuff in codspeed ci

crates/bytecode/src/legacy/analysis.rs, crates/bytecode/src/legacy/analyzed.rs, crates/bytecode/src/legacy/jump_map.rs
Cache `Arc<BitVec<u8>>` raw pointer and use bit operations for 7-8x performance improvement in `JumpTable` access/lookups via `is_valid`. Fixes https://github.com/bluealloy/revm/issues/2437
Implementation    | Time per op | Ops/sec | Speedup
------------------|-------------|---------|--------
Cached Pointer    | 13.40 ns    | 74.6M   | 7.9x faster
Arc Deref         | 106.26 ns   | 9.4M    | baseline
Pattern     | Cached    | Arc       | Speedup
------------|-----------|-----------|--------
Sequential  | 16.44 ns  | 100.77 ns | 6.1x
Random      | 12.57 ns  | 98.48 ns  | 7.8x
Both sequential and random access patterns show 6-8x speedup. All tests pass with identical results
PS: I included the benchmark test so anyone can run see the result <3
=> perf: faster JumpTable bits lookup

.config/zepter.yaml, .github/workflows/release-plz.yml
Changes made:
.config/zepter.yaml
expose → exposes: fixed incorrect verb form for third-person singular (“B exposes that feature”)
it → is: corrected grammar in the phrase (“A is outside of the workspace”)
.github/workflows/release-plz.yml
dectect → detect: fixed spelling error in the word "detect"
incremneted → incremented: corrected typo in "incremented"
These changes ensure clearer documentation and prevent confusion when reading workflow comments. No functional changes to code behavior.
=> Fix minor grammar issues in comments for workflows

crates/context/src/journal.rs, crates/context/src/journal/inner.rs
`cargo bench --profile dev --benches -p revme -- --test --nocapture | rg reset_preloaded_addresses` where yes is len == len:
- yes: 1028
- no: 2141
so decent enough for essentially a free comparison
=> perf: optimize warm_preloaded_addresses reset

.github/workflows/ethereum-tests.yml, Cargo.lock, Cargo.toml, README.md, bins/revme/Cargo.toml, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/precompile/src/modexp.rs, crates/revm/Cargo.toml
Replaces the current modexp implementation with a gmp based implementation
Passes state tests:
```
Running tests in test-fixtures/stable/state_tests...
████████████████████████████████████████████████████████████████████████████████████████ 86/86Finished execution. Total CPU time: 258.077688s
All tests passed!
Running develop statetests...
warning: extern crate `aurora_engine_modexp` is unused in crate `revm_precompile`
|
= help: remove the dependency or add `use aurora_engine_modexp as _;` to the crate root
note: the lint level is defined here
--> crates/precompile/src/lib.rs:4:29
|
4 | #![cfg_attr(not(test), warn(unused_crate_dependencies))]
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^
warning: `revm-precompile` (lib) generated 1 warning
Finished `dev` profile [unoptimized + …
```
=> feat(precompile): rug/gmp-based modexp

crates/database/src/in_memory_db.rs
This change fixes the error reported [here](https://t.me/c/1543757393/5408) and resolves issue #2626.
By setting the AccountState to None, this ensures correct behavior when the previous state before calling set_existing_account was None.
=> fix: change account state to None if NotExisting on insert_account_info

crates/revm/tests/common.rs
fixes [compare_or_save_testdata](https://github.com/bluealloy/revm/blob/c66b841dca4c0f093fdb10ce4fccf1b4aa0b9995/crates/revm/tests/common.rs#L15-L18) signature when the serde feature is disabled to resolve compilation issues e.g when running `cargo test` or `cargo test --all-targets`
=> test: update compare_or_save_testdata test helper fn signature

crates/op-revm/src/result.rs
Adds a fallible conversion from an OP halt reason to an L1 halt reason.
We need this to convert an OP halt reason back to the `InstructionResult`.
Since `OpHaltReason::FailedDeposit` does not originate from an `InstructionResult`, we cannot map this to an `InstructionResult`. Instead I opted to add a fallible conversion for the halt reason types.
=> feat: add fallible conversion from OpHaltReason to HaltReason

crates/context/interface/src/lib.rs, crates/context/src/lib.rs, crates/database/interface/src/lib.rs, crates/handler/src/lib.rs, crates/state/src/lib.rs
Hi, the inner doc comment for a few `lib.rs` were probably copy-pasted from https://github.com/bluealloy/revm/blob/435153d1b3e708bf48100fd2bf73a07aa02e1f94/crates/op-revm/src/lib.rs#L1
I quickly inferred better descriptions, better suggestions welcomed.
=> docs: fix copy-pasted inner doc comments

crates/revm/Cargo.toml
Enables gmp by default on performance-modexp so we can see benches with repricing and gmp
=> chore: enable gmp by default for performance-modexp testing

crates/context/src/journal/entry.rs, crates/context/src/journal/inner.rs
---
This pull request corrects a typo in the variable and parameter name is_created_globaly, changing it to is_created_globally across the codebase for improved clarity and consistency.
---
=> fix typo: Rename is_created_globaly to is_created_globally

crates/precompile/src/modexp.rs
This implements the following change:
https://github.com/ethereum/EIPs/pull/9969
by changing the `GAS_DIVISOR` to `1` for osaka
=> feat(precompile): triple the price of modexp

book/src/SUMMARY.md, book/src/architecture.md, book/src/inspector.md, crates/inspector/src/inspector_tests.rs, crates/inspector/src/lib.rs, crates/inspector/src/traits.rs
fixing call_end not being called bug. Adding docs for inspector and tests that cover this bug.
=> fix(Inspector): call_end not called on fast return

crates/handler/src/handler.rs, crates/handler/src/post_execution.rs
Removes the unused State bound from JournalTr in Handler::Evm. This removal allows journals to use the Handler trait even if they don't return EvmState from JournalTr::finalize. A concrete example is a JournalTr implementor that maintains some custom state in addition to EvmState.
=> chore: remove State bound from JournalTr in Handler::Evm

crates/interpreter/src/interpreter/shared_memory.rs
ref https://github.com/bluealloy/revm/pull/2714
=> docs: add release sefety section for SharedMemory fn

Cargo.toml
Without this the changes from #2713 have no effect as sha3 is always enabled.
=> fix: do not enable `sha3-keccak` in workspace

crates/handler/src/pre_execution.rs, crates/op-revm/src/handler.rs, crates/revm/tests/integration.rs
The merge of `validate_tx_against_state` and `deduct_caller` done in https://github.com/bluealloy/revm/pull/2460 seems to have broken gas deduction when `disable_balance_check` is enabled. This PR adds a test for this error and proposes a possible fix.
The result is that when balance checks are disabled the effective cost is first deducted with saturation from the caller balance, and then increased if necessary to cover the transaction value.
=> fix: gas deduction with `disable_balance_check`

crates/precompile/src/bls12_381.rs, crates/precompile/src/bls12_381/arkworks.rs, crates/precompile/src/bls12_381/blst.rs, crates/precompile/src/bls12_381/g1_add.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_add.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/map_fp_to_g1.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bls12_381/utils.rs, crates/precompile/src/bls12_381_const.rs, crates/precompile/src/bn128.rs, crates/precompile/src/bn128/arkworks.rs, crates/precompile/src/bn128/substrate.rs, crates/precompile/src/kzg_point_evaluation.rs, crates/precompile/src/secp256k1.rs, crates/precompile/src/secp256r1.rs
Using revm inside of a zkVM involves patching certain cryptographic libraries using patch-crates.io -- this is quite brittle because one needs to ensure that the versions match up and long term we would like these to be patched using extern C.
One could implement extern C methods under a feature flag, however the more general strategy would be to have a pluggable architecture like https://github.com/alloy-rs/alloy/pull/2634 -- This PR is a precursor to adding the pluggable architecture since the functions that are being plugged in shouldn't rely on the types of a particular library.
=> feat: Use bytes API for underlying precompile library APIs

crates/handler/src/system_call.rs
System call tx should have fixed 30_000_000 gas. Currently it does not effect anything
=> fix: system call should have 30M gas limit

crates/context/interface/src/local.rs, crates/interpreter/src/interpreter/ext_bytecode.rs
I believe this change was made to reduce memory consumption, however the initial problem was a memory leak which was fixed. So I don't think this is necessary anymore, and it should slightly improve performance because of cache locality of the frames inside of the Vec, as well as removing an initial allocation when creating the frame.
=> perf: un-Box frames

Cargo.lock, Cargo.toml, crates/bytecode/Cargo.toml, crates/bytecode/src/legacy/jump_map.rs, crates/op-revm/Cargo.toml, crates/op-revm/src/precompiles.rs, crates/precompile/Cargo.toml, crates/precompile/src/lib.rs, crates/primitives/Cargo.toml, crates/primitives/src/lib.rs, crates/primitives/src/once_lock.rs
Same as `alloy_primitives::map` that uses `hashbrown`, here we use `once_cell::race::OnceBox` for `no_std` `OnceLock`, while preferring `std::sync::OnceLock`.
=> chore: add OnceLock re-export with no_std support

Cargo.lock, examples/custom_precompile_journal/Cargo.toml, examples/custom_precompile_journal/src/main.rs
Same format as all the others.
The name actually matters for the bench workflow to skip building.
=> chore: rename custom-precompile-journal

crates/handler/src/pre_execution.rs, crates/op-revm/src/handler.rs
closes https://github.com/bluealloy/revm/issues/2803
moving nonce bump right behind the journaling fixes this
=> fix: nonce change not reverted on invalid tx with insufficient balance

crates/op-revm/tests/testdata/test_halted_tx_call_bn254_pair_fjord.json, crates/op-revm/tests/testdata/test_halted_tx_call_bn254_pair_granite.json
Ref https://github.com/bluealloy/revm/pull/2810, https://github.com/bluealloy/revm/issues/2189
Dedups test data for renamed tests `bn128` -> `bn254`
=> test(op-revm): Update test data for renamed tests

bins/revme/benches/evm.rs, crates/inspector/src/handler.rs, crates/inspector/src/inspect.rs, crates/inspector/src/inspector_tests.rs, crates/inspector/src/lib.rs, crates/inspector/src/mainnet_inspect.rs, crates/op-revm/src/api/exec.rs, crates/op-revm/tests/integration.rs, crates/revm/src/lib.rs
Adds inspection support for system transactions to enable tracing with debug_traceTransaction and debug_traceBlock APIs.
- Added InspectSystemCallEvm trait extending InspectEvm and SystemCallEvm
- Added InspectorHandler::inspect_run_system_call method for system call inspection
- Implemented inspection support for mainnet EVM with comprehensive test coverage
- Re-exported new traits in main revm crate
Closes #2798
=> feat: add system transaction inspection support

crates/bytecode/src/bytecode.rs, crates/handler/src/frame.rs, crates/interpreter/src/interpreter/ext_bytecode.rs, crates/interpreter/src/interpreter/ext_bytecode/serde.rs
- Currently in foundry we check for None OR hash==zero to check if it's unset. Use `None` in all cases.
- Provide a helper for `get_or_insert_with()` that calculates the hash if unset.
=> chore: improve ExtBytecode hash handling

crates/precompile/bench/ecrecover.rs
simplify the ecrecover test like alloy-core signature code
https://github.com/alloy-rs/core/blob/10aed0012d59a571f35235a5f9c6ad03076bf62b/crates/primitives/src/signature/sig.rs#L160-L165
```rust
pub fn as_bytes(&self) -> [u8; 65] {
let mut sig = [0u8; 65];
sig[..32].copy_from_slice(&self.r.to_be_bytes::<32>());
sig[32..64].copy_from_slice(&self.s.to_be_bytes::<32>());
sig[64] = 27 + self.y_parity as u8;
}
```
rm unnecessary copy_from_slice and U256::from
=> chore: simplify the ecrecover test

crates/state/src/account_info.rs
https://github.com/bluealloy/revm/blob/3ad31163f9fcbcc194db3ed9ac4fc28b822f5848/crates/state/src/account_info.rs#L37-L43
As the `AccountInfo` struct manually implements PartialEq which ignores the `code` field, but derives `Ord/PartialOrd` which use the `code` field, it violates the rule in https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html: a == b if and only if `partial_cmp(a, b) == Some(Equal)`.
also can see example `struct Character` in https://doc.rust-lang.org/std/cmp/trait.Ord.html
=> fix: manally implementation PartialOrd and Ord for AccountInfo

book/src/awesome.md
Fixed 3 broken links in the `book/src/awesome.md` file to ensure all external references are working correctly.
- **Arbiter**: Updated URL from `primitivefinance/arbiter` → `harnesslabs/arbiter` (repository moved)
- **revm-by-example**: Updated URL from `Cionn3/revm-by-example` → `greekfetacheese/revm-by-example` (repository moved)  
- **Uniswap Swap Example**: Fixed incomplete description text
=> fix: Update broken links in awesome.md documentation

README.md
- **README.md**: Refactor quick links section to use cleaner markdown syntax
- Convert `[book](url)` format to `[descriptive text](url)`
- Remove duplicate URL text in telegram group link
- Improve overall link presentation and readability
- `README.md`
=> Fix link formatting and remove URL duplication in documentation

book/src/revme.md
- Converted raw URLs to proper markdown link format
- Fixed grammatical error in legacy tests section
- Improved overall documentation readability
- **Before**: Plain URLs like `https://github.com/ethereum/execution-spec-tests/releases`
- **After**: Clean markdown links like `[EEST releases](https://github.com/ethereum/execution-spec-tests/releases)`
- **Grammar fix**: "first to download" → "first download"
=> improve link formatting and fix grammar in revme.md documentation

crates/bytecode/src/bytecode.rs
Removed use core::fmt::Debug; from crates/bytecode/src/bytecode.rs since #[derive(Debug)] does not require it. No functional changes; cleans up an unused import warning.
=> chore(bytecode): remove unused Debug import

crates/interpreter/src/instruction_result.rs
- Map InstructionResult::CreateContractStartingWithEF to HaltReason::CreateContractStartingWithEF instead of CreateContractSizeLimit.
- Keeps behavior consistent with distinct halt categories and improves error reporting accuracy.
- All revm-interpreter tests pass locally.
=> fix(interpreter): correct CreateContractStartingWithEF halt mapping

crates/precompile/src/bls12_381/arkworks.rs, crates/precompile/src/bls12_381/blst.rs, crates/precompile/src/bls12_381/g1_add.rs, crates/precompile/src/bls12_381/g1_msm.rs, crates/precompile/src/bls12_381/g2_add.rs, crates/precompile/src/bls12_381/g2_msm.rs, crates/precompile/src/bls12_381/map_fp2_to_g2.rs, crates/precompile/src/bls12_381/map_fp_to_g1.rs, crates/precompile/src/bls12_381/pairing.rs, crates/precompile/src/bls12_381/utils.rs, crates/precompile/src/interface.rs, crates/precompile/src/kzg_point_evaluation/arkworks.rs, crates/precompile/src/kzg_point_evaluation/blst.rs
*Initially the goal was to make `PrecompileError` compatible with `Copy`, but this actually not possible. We can close #2906. (as not planned)*
So I just propose to extend `PrecompileError` enum as in cases where it is feasible, more specific variants should be used in place of the Other() error variant.
=> refactor(precompile): add new specific `PrecompileError` variants

crates/precompile/src/lib.rs, crates/primitives/src/hardfork.rs
=> chore: added amsterdam in spec id

crates/interpreter/src/gas/constants.rs, crates/interpreter/src/instructions/host.rs
In `go-ethereum`, the name `SelfdestructRefundGas` is used (https://github.com/ethereum/go-ethereum/blob/f3c696fa1db75d0f78ea47dd0975f6f0de6fdd84/params/protocol_params.go#L90). 
A more suitable name might be REFUND_SELFDESTRUCT. Feel free to close this.
=> chore: rename SELFDESTRUCT to SELFDESTRUCT_REFUND

crates/op-revm/src/transaction/deposit.rs
The test is named `serialize_json_deposit_tx_parts`, but it actually tests deserialization. Add a serialization test.
=> test(op-revm): add serialize DepositTransactionParts test

crates/op-revm/src/handler.rs
https://github.com/bluealloy/revm/blob/4d247890e00ad62edded3b2d0f08845bd9523063/crates/handler/src/mainnet_handler.rs#L8-L12
MainnetHandler already uses _phantom
=> chore(op-revm): rm redundant phantom

crates/interpreter/src/gas/constants.rs
Remove redundant inline comment that duplicates the doc comment above TOTAL_COST_FLOOR_PER_TOKEN constant. The doc comment already provides the same information about EIP-2028, making the inline comment unnecessary and improving code readability.
=> chore: remove duplicate comment for TOTAL_COST_FLOOR_PER_TOKEN constant

crates/inspector/src/eip3155.rs
The skip flag was never set anywhere and only read in step_end, making it dead code. Removing it simplifies the tracer, avoids confusion about unimplemented behavior, and aligns with EIP-3155 which expects an entry per operation (there’s no need to conditionally skip output).
=> chore(inspector): remove dead skip flag

.github/SECURITY.md, README.md
This makes it easier to find for users as it shows up as a `Security` tab
If you would prefer to include / change it to `security@ithaca.xyz` this is of course also a possibility
=> chore: add `SECURITY.md` 

bins/revme/src/cmd/evmrunner.rs
```markdown
Support `0x` prefix in hex input for `evmrunner` command to improve user experience.
- Strip `0x` prefix from `bytecode` and `input` parameters before hex decoding
- Aligns behavior with `bytecode` subcommand which already handles `0x` prefix correctly
- **Before:** `revme evmrunner 0x6080604052...` would fail with "Invalid bytecode"
- **After:** Both `6080604052...` and `0x6080604052...` formats work seamlessly
=> fix: support 0x prefix in evmrunner hex input

crates/op-revm/src/l1block.rs
- **Summary**: Align `operator_fee_charge` with its doc comment by returning zero for empty inputs.
- **Rationale**: The function’s comment states that deposit or empty inputs should yield zero fee; previously, only the deposit prefix (0x7E) was handled.
- **Change**: Added `input.is_empty()` to the early-return condition in `l1block.rs`.
- **Impact**: Prevents overcharging operator fees for empty inputs; behavior now matches documentation.
=> op-revm: treat empty input as zero operator fee in operator_fee_charge

crates/context/Cargo.toml, crates/context/interface/src/cfg.rs, crates/context/src/cfg.rs, crates/op-revm/src/handler.rs
An option to disable fee charges, only meaningful on `op-revm` is added, which doesn't charge additional fees, in addition from the default fee from the gas limit and gas price.
This is useful for `eth_call`s which should disable all fees.
See https://github.com/paradigmxyz/reth/issues/18470
=> Add an option to disable "fee-charge" on `op-revm`

crates/context/Cargo.toml, crates/context/interface/src/cfg.rs, crates/context/src/cfg.rs, crates/handler/src/handler.rs, crates/handler/src/validation.rs, crates/revm/Cargo.toml
Closes #2936.
Let me know if I missed something or if you want me to add a line in a CHANGELOG.
(cc @rakita)
=> feat: allow EIP-7623 to be disabled

crates/op-revm/src/constants.rs, crates/op-revm/src/handler.rs, crates/op-revm/src/l1block.rs, crates/op-revm/src/precompiles.rs, crates/op-revm/src/spec.rs
Implements the Jovian operator fee fix, as described in the [design doc](https://github.com/ethereum-optimism/design-docs/pull/299) and the [spec](https://github.com/ethereum-optimism/specs/pull/764/files).
The opeator fee fix is currently planned to be included in Jovian.
=> feat(op-revm): implement jovian operator fee fix

crates/precompile/src/interface.rs, crates/primitives/src/once_lock.rs
Found here: https://github.com/bluealloy/revm/pull/2986
=> fix: racecondition return on install_crypto fn

crates/bytecode/src/opcode.rs
- MLOAD only reads from memory; it does not write to it. Including it in OpCode::modifies_memory misclassifies read-only behavior as memory-modifying.
- Memory expansion (zero-filling) during reads is an allocation side effect, not a semantic write by the opcode itself. This aligns with interpreter implementations and EVM references.
- Updated the test to expect false for MLOAD, kept MSTORE as modifying, and ADD as non-modifying.
- This improves correctness for analyzers/inspectors relying on opcode classification and keeps consistency with other read-only ops (e.g., KECCAK256, RETURN) that also expand memory but aren’t flagged as modifying.
=> fix(bytecode): exclude MLOAD from modifies_memory and update test

crates/op-revm/src/constants.rs, crates/op-revm/src/handler.rs, crates/op-revm/src/l1block.rs, crates/op-revm/src/precompiles.rs, crates/op-revm/src/spec.rs
Incorporates the [DA footprint block limit](https://github.com/ethereum-optimism/design-docs/pull/317) changes in op-revm.
Progress towards https://github.com/op-rs/kona/issues/2830
=> feat(jovian): add da footprint block limit to l1 block info.

crates/context/interface/src/local.rs, crates/context/interface/src/result.rs, crates/context/src/local.rs, crates/ee-tests/src/op_revm_tests.rs, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_g1_add_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_g1_msm_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_g1_msm_wrong_input_layout.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_g2_add_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_g2_msm_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_g2_msm_wrong_input_layout.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_map_fp2_to_g2_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_map_fp_to_g1_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_pairing_input_wrong_size.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bls12_381_pairing_wrong_input_layout.json, crates/ee-tests/tests/op_revm_testdata/test_halted_tx_call_bn254_pair_granite.json, crates/handler/src/post_execution.rs, crates/handler/src/precompile_provider.rs, crates/inspector/src/eip3155.rs, crates/interpreter/src/instruction_result.rs, examples/custom_precompile_journal/src/precompile_provider.rs
This PR enhances precompile error reporting and closes #2898.
Attempt to implement a mechanism that records potential precompile error in context if depth == 0, in order to bubble it up in output as Bytes. Idea proposed by Rakita https://github.com/bluealloy/revm/pull/2905#pullrequestreview-3155479883.
=> Feature: Support bubbling up Precompile error messages 

crates/database/interface/src/lib.rs
Replace duplicate BENCH_TARGET_BALANCE and BENCH_CALLER_BALANCE constants with a shared COMMON_TEST_BALANCE constant to improve maintainability.
Both constants had identical values: U256::from_limbs([10_000_000_000_000_000, 0, 0, 0])
This change:
- Eliminates code duplication
- Makes balance changes easier to maintain 
- Preserves all existing functionality
- Only affects test/benchmark constants
=> refactor(database): extract duplicate test balance constants

crates/inspector/src/gas.rs
Remove two no-op calls to interp.bytecode.pc() and interp.bytecode.opcode() in StackInspector::step_end test.
These getters are side-effect free; values are already captured in step(). Keeping them was misleading and unnecessary.
=> fix(inspector): remove redundant pc()/opcode() calls in step_end

crates/primitives/src/once_lock.rs
Ensured the no_std OnceLock::get_or_init now boxes values internally so it no longer requires T: Into<Box<T>>.
This brings the API in line with std::sync::OnceLock and restores compatibility for all consumer types.
=> fix: Align no_std OnceLock semantics with std

crates/precompile/src/modexp.rs
Now sure how it passed CI, triggered here https://github.com/bluealloy/revm/actions/runs/18142956802/job/51638064865?pr=3029
=> chore: typo imputs

crates/context/interface/src/context.rs, crates/context/src/context.rs
Adds `tx_block_cfg_journal_mut` that is used in refactoring PR https://github.com/bluealloy/revm/pull/2991
Additionally move impl of `tx_journal_mut` and `tx_local_mut` to default impl as it can use all and all_mut functions
=> chore: add default impl for tx_local_mut and tx_journal_mut

crates/interpreter/src/instructions/host.rs
This change removes a duplicate stack length check before calling popn::<N>() in the LOG instruction and uses halt_underflow() in the None arm for consistency. The explicit len() < N guard is unnecessary because popn::<N>() already performs an underflow-safe check and returns None when insufficient items are present. Keeping both checks adds duplication without improving safety and can confuse future maintenance.
=> fix(interpreter): remove redundant stack underflow check in LOG instruction

crates/context/interface/src/transaction.rs, crates/handler/src/pre_execution.rs, crates/op-revm/src/handler.rs, examples/erc20_gas/src/handler.rs
Helper function for `ensure_enough_balance` for Transaction that compares balance with max amount that tx could spend.
Extracted from https://github.com/bluealloy/revm/pull/2991
=> chore: add ensure_enough_balance helper

crates/context/interface/src/block/blob.rs
- Remove the redundant if denominator == 0 { return 0; } in fake_exponential.
- The function already asserts denominator != 0, so the branch is never executed.
- The denominator originates from protocol constants (BLOB_BASE_FEE_UPDATE_FRACTION_*) and config fallback, both guaranteed non-zero.
- Keeping the check was contradictory (assert panics vs returning 0) and introduced dead code
=> fix(context): remove unreachable zero-denominator check in fake_exponential

crates/interpreter/src/interpreter/stack.rs, crates/interpreter/src/interpreter_types.rs
`StackTr` allows all kinds of operations on `Stack` but actually getting the stack data.
I need this data to make a full after-step snapshot of the EVM state: https://github.com/sergey-melnychuk/solenoid/blob/6faf25a94763d237424c406d248fdb9f50829b43/evm-tracer/src/lib.rs#L272
=> chore: expose stack data

CHANGELOG.md, Cargo.lock, Cargo.toml, bins/revme/CHANGELOG.md, bins/revme/Cargo.toml, crates/context/CHANGELOG.md, crates/context/Cargo.toml, crates/context/interface/CHANGELOG.md, crates/context/interface/Cargo.toml, crates/handler/CHANGELOG.md, crates/handler/Cargo.toml, crates/inspector/CHANGELOG.md, crates/inspector/Cargo.toml, crates/interpreter/CHANGELOG.md, crates/interpreter/Cargo.toml, crates/op-revm/CHANGELOG.md, crates/op-revm/Cargo.toml, crates/revm/CHANGELOG.md, crates/revm/Cargo.toml, crates/statetest-types/CHANGELOG.md, crates/statetest-types/Cargo.toml
This PR aligns crates.io versions.
Code for v87 release can be found in `release/v87` branch
=> chore: changelog update for v87

crates/interpreter/src/instructions/block_info.rs, crates/interpreter/src/instructions/tx_info.rs
- Replace U256::from(context.host.block_number()) with context.host.block_number() in block_info.rs.
- Replace U256::from(context.host.effective_gas_price()) with context.host.effective_gas_price() in tx_info.rs.
- Aligns with Host methods already returning U256 and matches style of adjacent instructions.
=> fix: remove redundant U256::from on Host getters in instructions

crates/op-revm/src/handler.rs
Replace expect() with a graceful error in validate_against_state_and_deduct_caller for non-deposit transactions when enveloped_tx is missing. This unifies behavior with reward_beneficiary, avoids process panics on malformed/external inputs (OpTxTr trait boundary), and aligns with the builder’s contract where missing enveloped bytes are a validation error, not an unreachable state.
=> fix(op-revm): return error instead of panic when enveloped_tx is missing

crates/database/src/states/bundle_state.rs, crates/interpreter/src/interpreter/ext_bytecode.rs
Removes two unused deprecated methods that were marked for removal but never actually used in the codebase.
- **`crates/database/src/states/bundle_state.rs`**: Removed `into_plain_state()` method
- Method was deprecated with message "Use `to_plain_state` instead"
- Confirmed unused after searching entire codebase
- **`crates/interpreter/src/interpreter/ext_bytecode.rs`**: Removed `regenerate_hash()` method  
- Method was deprecated with message "use `get_or_calculate_hash` or `calculate_hash` instead"
- Confirmed unused after searching entire codebase
=> refactor: remove unused deprecated methods
