bluealloy/revm

bins/revm-ethereum-tests/src/runner.rs
bins/revm-test/src/main.rs
crates/revm/src/db/in_memory_db.rs
crates/revm/src/evm_impl.rs
crates/revm/src/instructions/arithmetic.rs
crates/revm/src/instructions/gas/calc.rs
crates/revm/src/instructions/i256.rs
crates/revm/src/instructions/system.rs
crates/revm/src/machine/machine.rs
crates/revm/src/machine/stack.rs
crates/revm/src/models.rs
crates/revm/src/subroutine.rs

fix some clippy lints, clippy still complains about things like mod inception and unusual default impl though

fix(clippy): fix some clippy lints

---

.github/workflows/ci.yml
bins/revme/src/debugger/ctrl/cli.rs
bins/revme/src/debugger/ctrl/history.rs
crates/revm/src/db/web3db.rs
crates/revm/src/instructions/system.rs
crates/revm_precompiles/src/secp256k1.rs

Adds GHA CI (w/ caching etc.) and fixes fmt/lints

Add Continuous Integration

---

.github/workflows/ethereum-tests.yml

Clones https://github.com/ethereum/tests and runs `revme statetest` on it :smiley: 
Fixes #2

Run ethereum/tests in CI

---

Cargo.lock
crates/revm/Cargo.toml

as title, removes some dep requirements

chore: turn off default features for zkp-u256

---

crates/revm/src/models.rs
crates/revm/src/specification.rs

Add PartialEq and Eq on some selected types, this allows us to compare `BlockEnv`

feat: add some PartialEq derives

---

.github/workflows/ci.yml

cargo clippy/fmt to nightly

---

crates/revm/src/db/in_memory_db.rs

adds getters to gain access to the underlying Database

feat: add getters for cachedb

---

bins/revme/src/statetest/merkle_trie.rs
bins/revme/src/statetest/models/mod.rs
crates/revm/src/interpreter/memory.rs
crates/revm/src/subroutine.rs

chore(clippy): make clippy happy

---

bins/revme/src/statetest/models/mod.rs
bins/revme/src/statetest/models/spec.rs

* add default for difficulty
* add Merge variant
to pass: https://github.com/ethereum/tests/commit/a5731683234cd39c6c2ebf7a133991cadf27bdbb

test: update statetest model to pass merge tests

---

bins/revme/src/statetest/runner.rs
crates/revm/src/db/in_memory_db.rs
crates/revmjs/src/lib.rs

make field pub, use Enum default :D

Make CacheDB fields pub

---

bins/revme/src/statetest/runner.rs
crates/revm/src/evm_impl.rs

Correctly handle high nonce tests, this is not possible to happen on mainnet or any of testnets.

Handle HighNonce tests

---

crates/revm/src/evm_impl.rs

It seems that #175 introduced a `panic` when finalizing a transaction; which occurs at least in some Foundry tests. This PR restores the old behavior as before #175 (although we might want to use a `saturating_add`?)

fix(revm): Fix balance overflow in `finalize`

---

crates/revm/src/evm_impl.rs

Cf. https://github.com/bluealloy/revm/pull/182#issuecomment-1222553791

fix: Use `saturating_add` instead of `checked_add` in `finalize`

---

crates/revm/src/evm_impl.rs
crates/revm/src/gas.rs
crates/revm/src/gas/calc.rs
crates/revm/src/gas/constants.rs

This reverts commit 0eca30767511e9d202017766d1523e95db0cf9b4.

Revert "refactor(revm): use u64 for gas refund counter (#180)"

---

crates/revm/src/lib.rs

chore: export JournaledState

---

crates/revm/src/evm_impl.rs

fix: return out of gas code for precompiled contracts

---

crates/revm/Cargo.toml
crates/revm/src/evm_impl.rs
crates/revm/src/models.rs

feat: allow eip3607 to be toggled off

---

Cargo.lock
crates/revm/Cargo.toml
crates/revm/src/common.rs
crates/revm/src/db/in_memory_db.rs
crates/revm/src/evm_impl.rs
crates/revm/src/instructions/system.rs
crates/revm/src/interpreter/bytecode.rs
crates/revm/src/lib.rs

refactor keccak hashing to one place

feat(refactor): make keccak in one place.

---

Cargo.lock
crates/revm/Cargo.toml

Removes the unused `parking_lot` dependency

Remove unused parking_lot dependency

---

bins/revme/src/statetest/runner.rs

Fix: typos

---

crates/revm/Cargo.toml
crates/revm/src/evm_impl.rs
crates/revm/src/models.rs

Resolution for this PR: https://github.com/bluealloy/revm/pull/264

disable gas refunds with env flag

---

CHANGELOG.md
Cargo.lock
bins/revme/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml

bump on main, release branch is found on release/v18

Bump revm to v2.3.0

---

crates/revm/src/db/in_memory_db.rs

one line change that makes load_account fn public

make load_account pub

---

crates/revm/src/db/in_memory_db.rs

chore: add Eq to AccountState

---

Cargo.lock
LICENSE
bins/revme/LICENSE
crates/interpreter/Cargo.toml
crates/interpreter/LICENSE
crates/interpreter/src/host/dummy_host.rs
crates/interpreter/src/instructions/host.rs
crates/interpreter/src/instructions/i256.rs
crates/interpreter/src/interpreter.rs
crates/interpreter/src/interpreter/analysis.rs
crates/interpreter/src/interpreter/contract.rs
crates/precompiles/Cargo.toml
crates/precompiles/LICENSE
crates/precompiles/src/bn128.rs
crates/precompiles/src/lib.rs
crates/precompiles/src/modexp.rs
crates/primitives/Cargo.toml
crates/primitives/LICENSE
crates/primitives/src/lib.rs
crates/revm/Cargo.toml
crates/revm/LICENSE
crates/revm/src/db/in_memory_db.rs
crates/revm/src/evm_impl.rs
crates/revm/src/inspector.rs
crates/revm/src/inspector/customprinter.rs
crates/revm/src/inspector/gas.rs
crates/revm/src/journaled_state.rs

Bytes and hashmap moves to primitives, other crates are using that one. ruint same thing

chore: Cleaning up imports

---

Cargo.lock
README.md
crates/interpreter/src/instructions.rs
crates/interpreter/src/instructions/host.rs
crates/primitives/src/bytecode.rs
crates/primitives/src/bytecode/jump_table.rs
crates/primitives/src/lib.rs
crates/primitives/src/log.rs
crates/primitives/src/precompile.rs
crates/primitives/src/result.rs
crates/primitives/src/utilities.rs
crates/revm/src/inspector/gas.rs
crates/revm/src/journaled_state.rs
crates/revm/src/lib.rs

need some work, todo write this.

add no_std to primitives

---

crates/revm/src/evm.rs

add new EVM init function that provides an Env

feat: add EVM::with_env

---

LICENSE

Add copyright start year

---

crates/revm/src/journaled_state.rs

smol typo in JournalEntry variant

chore: fix typo StorageChange

---

crates/primitives/src/env.rs

Update readme doc of `perf_analyse_created_bytecodes`

---

crates/interpreter/src/instructions/opcode.rs
crates/interpreter/src/lib.rs

chore: add display impl for OpCode

---

crates/interpreter/src/instruction_result.rs
crates/primitives/src/result.rs
crates/revm/src/evm_impl.rs

Add internals results to halt, can be useful for inspector.

feat: Add all internals results to Halt

---

crates/primitives/src/result.rs

adds helper function to access output bytes

feat: add Output::into_data

---

README.md

Arbiter is an interface over revm for risk modeling and economic fuzzing in DeFi. It's efforts would not be possible without revm. The project is young but we are moving quickly and gaining interest and momentum.

Update README.md - Add arbiter

---

crates/primitives/src/result.rs

Add helper type to consume the logs vec

chore: add into_logs

---

CHANGELOG.md
Cargo.lock
bins/revm-test/Cargo.toml
bins/revme/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml

Release v23, revm v3.2.0

---

crates/revm/src/evm_impl.rs
crates/revm/src/journaled_state.rs

This PR consolidated few checks into one and allows us fewer hashmap lookups.
Previously we fetched created account three times from the Map for `create_contract`, nonce increment and for balance transfer, not it is only one hashmap get.

perf: Create account checkpoint

---

crates/primitives/src/lib.rs

Yeah, do not worth a PR merge for itself, just for signaling to fix this in another more usefull commit.

chore: fix typo

---

.github/workflows/ci.yml
.github/workflows/ethereum-tests.yml

feat: Run CI on release branches

---

.github/workflows/ci.yml
.github/workflows/ethereum-tests.yml

it is not `releases` but `release`

chore: fix previous commit

---

crates/interpreter/src/interpreter/memory.rs

add helper function to extract the memory data

feat: add Memory::into_data

---

crates/interpreter/src/instruction_result.rs
crates/interpreter/src/instructions.rs
crates/revm/src/inspector/gas.rs

I believe this should close #335 as an invalid opcode should consume all the remaining gas

consume all gas on invalid opcode

---

crates/revm/src/db/in_memory_db.rs

splitting this line into three :). it looks very long on my laptop. will close if the former is prefered

chore: split comment

---

crates/interpreter/src/lib.rs
crates/precompile/src/lib.rs
crates/revm/src/lib.rs

This will fix the search functionality at the docs.rs

fix(doc): Inline documentation of re-exports

---

.github/workflows/ci.yml
.github/workflows/ethereum-tests.yml

And replace with the unmaintained `actions-rs/toolchain` with [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).

ci: update jobs to latest versions

---

crates/interpreter/src/instructions/host.rs
crates/primitives/src/env.rs
crates/revm/src/evm_impl.rs

Essentially re-adding https://github.com/bluealloy/revm/commit/dd4a13c418e5dd0ab89dfb91d0c89a17806b2f47 , but updated to use in relevant places.

feat: introduce initcode size limit check taking config into account

---

crates/revm/src/evm_impl.rs

Moves https://github.com/bluealloy/revm/pull/504 to main

chore: move precompiles to EVMData for inspector access

---

bins/revme/src/statetest/runner.rs
crates/precompile/src/lib.rs
crates/precompile/src/modexp.rs
crates/primitives/Cargo.toml
crates/primitives/src/bytecode.rs
crates/primitives/src/lib.rs
crates/primitives/src/specification.rs
crates/revm/src/evm.rs
crates/revm/src/journaled_state.rs
crates/revm/src/lib.rs
examples/fork_ref_transact.rs

Split off from #558
And some other minor clean-ups

chore: avoid unnecessary allocations

---

crates/revm/src/db/states/bundle_state.rs

chore: fix test build, use new types

---

.github/workflows/ci.yml
.github/workflows/ethereum-tests.yml

<https://github.com/bluealloy/revm/actions/runs/5906319325/job/16022101044>

ci: add timeout to all jobs

---

crates/primitives/src/state.rs
crates/revm/src/db/states/bundle_state.rs

Minor stylistic changes to `BundleState`. 
@rakita I'm not opinionated, you can pick and choose which ones you like (if any).

style: bundle state

---

crates/interpreter/Cargo.toml
crates/interpreter/src/interpreter.rs
crates/primitives/Cargo.toml
crates/revm/src/db/states/bundle_state.rs

Split off from #582
Note that ruint >1.10 is needed for main #582 changes.

chore: misc improvements

---

crates/interpreter/src/gas.rs
crates/interpreter/src/gas/calc.rs
crates/interpreter/src/instructions/macros.rs

Split off from #582
More docs and inline trivial functions.

chore(interpreter): improve gas calculations

---

crates/revm/src/db/states/bundle_state.rs

* Consume bundle state entirely upon taking the plain state
* Create additional function for splitting plain state and reverts

chore(state): bundle state split

---

crates/revm/src/db/states/bundle_account.rs

Dropping the storage was a bug as it should have been saved inside the `Revert`.
Storage was drained for `Destroyed`, `DestroyedAgain` and for `DestroyedChanged` it depends on the Transition wipe flag if we are going to move present storage to the `Revert` or not.

fix(state): drop storage only for DestroyedChanged

---

crates/revm/src/db/states/bundle_state.rs

Add the ability to toggle reverts collection in `BundleState`.

feat(state): ability to disable reverts collection in bundle state

---

crates/revm/src/db/states/state.rs

Revert the change from #657 that introduced a regression.

fix(state): state transition regression

---

crates/revm/src/db/states/bundle_state.rs

adds `BundleState::revert_latest` for convenience if you want to revert 1 single transition
moves revert logic from `revert` to `revert_latest` and replace the while loop

feat: add BundleState::revert_latest

---

crates/revm/src/db/states/transition_account.rs
crates/revm/src/db/states/transition_state.rs

This derives `Eq` and `PartialEq` for `TransitionState` and `TransitionAccount`

chore: impl Eq, PartialEq for TransitionState

---

.github/workflows/book.yml

fix: build documentation book

---

crates/primitives/src/env.rs

Just adds derives for `PartialEq` and `Eq` for the `Env` type

feat: derive PartialEq, Eq for Env

---

crates/revm/src/db.rs
crates/revm/src/db/states.rs

chore: expose StateDBBox

---

crates/primitives/src/result.rs

I'm that guy, opening a pull request for a doc typo.

chore: Small doc comment fix

---

crates/revm/src/db/states.rs

make `BundleBuilder` publicly available

---

crates/precompile/src/modexp.rs

modexp gas check

---

CHANGELOG.md
Cargo.lock
bins/revme/Cargo.toml
crates/interpreter/CHANGELOG.md
crates/interpreter/Cargo.toml
crates/precompile/CHANGELOG.md
crates/precompile/Cargo.toml
crates/primitives/CHANGELOG.md
crates/primitives/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml

bump v26 revm v3.5.0

---

crates/revm/src/journaled_state.rs

moves impl JournalState and improves docs for account fn

chore: reorder JournalState impl

---

crates/primitives/src/state.rs

Adds a few simple unit tests to validate empty account checks.

chore(primitives): Empty Account Tests

---

crates/revm/src/db/states/bundle_state.rs

Related to https://github.com/paradigmxyz/reth/pull/4647#discussion_r1354409735

getter for `states` field of `BundleBuilder`

---

crates/primitives/src/state.rs

adds a new helper function to Account to iterate over all changed storage slots

feat: add changed storage slots iter

---

crates/revm/src/inspector.rs
crates/revm/src/inspector/customprinter.rs
crates/revm/src/inspector/eip3155.rs
crates/revm/src/inspector/gas.rs
crates/revm/src/inspector/instruction.rs

Alternative implementation of #800

refactor: remove `step` and `step_end` return result

---

crates/interpreter/src/gas.rs
crates/revm/src/evm_impl.rs
crates/revm/src/handler.rs
crates/revm/src/handler/mainnet.rs
crates/revm/src/handler/optimism.rs

Make main return handle.
Slight refactor on refund gas for handles.
PR depends on outcome of this: https://github.com/bluealloy/revm/issues/807

chore: refactor main return to handle

---

crates/primitives/Cargo.toml

only used behind c-kzg feature

chore(deps): make derive-more optional

---

crates/revm/src/db/states/state.rs

Allow fine-grained control over State by making `State::apply_transition` pub.

chore(state): make `State::apply_transition` pub

---

crates/primitives/src/lib.rs
crates/revm/src/db/states/transition_account.rs

Add function to compute balance delta on `TransitionAccount`.

feat: transition account balance delta

---

crates/revm/src/db/states/account_status.rs
crates/revm/src/db/states/cache_account.rs

Make `AccounStatus` transition on selfdestruct consistent.

chore(state): consistent selfdestruct status transition

---

Cargo.lock
crates/precompile/Cargo.toml
crates/primitives/Cargo.toml

chore: bump c-kzg to v0.4.0

---

crates/primitives/src/env.rs
crates/primitives/src/result.rs

Checking if it solves lint error

cargo fmt and removed extra newlines

---

Cargo.lock
crates/primitives/Cargo.toml

Remove some duplicate dependencies

chore(deps): run `cargo update`, bump alloy-primitives

---

Cargo.lock
crates/primitives/Cargo.toml

Will need to be backported to `reth_freeze` branch too.

chore(deps): alloy 0.6

---

Cargo.lock
crates/primitives/Cargo.toml

merged on `main` here: https://github.com/bluealloy/revm/pull/963

bump alloy-primitives in reth_freeze

---

bins/revme/src/cmd/statetest.rs
bins/revme/src/cmd/statetest/models/mod.rs
bins/revme/src/cmd/statetest/runner.rs
bins/revme/src/main.rs
crates/primitives/src/env.rs

Closes first round of requirements for revm to be included in goevmlab fuzzer:
https://github.com/holiman/goevmlab/issues/113#issuecomment-1869548738

feat(revme): make it runnable by goevmlab

---

crates/revm/src/inspector.rs

docs: update create docs

---

crates/revm/src/inspector.rs

docs: update call end docs

---

crates/revm/src/db/states/bundle_account.rs
crates/revm/src/db/states/bundle_state.rs

Backport of #1010 to reth_freeze

fix(State): Preserve original values on delete revert (#1010)

---

examples/generate_block_traces.rs

chore: make clippy happy

---

crates/primitives/src/state.rs

Add some docs to describe what the previous or original means.

docs: add some docs to StorageSlot

---

crates/primitives/src/env.rs
crates/revm/src/handler/handle_types/pre_execution.rs
crates/revm/src/handler/mainnet.rs
crates/revm/src/handler/mainnet/execution.rs
crates/revm/src/handler/mainnet/pre_execution.rs
crates/revm/src/optimism.rs
crates/revm/src/optimism/handler_register.rs

Move op specific l1 load to its own function

refactor(op): Move op l1 block load to op handler

---

crates/revm/src/builder.rs

this fixes a critical issue where the given env got lost

fix: properly set context env

---

crates/revm/src/handler.rs

fix: modify cfg spec_id (#1095)

---

CHANGELOG.md

bump: tag v29 revm v6.0.0

---

crates/revm/src/inspector/eip3155.rs

Use structs instead of `serde_json::json!` to encode JSON.

chore: improve EIP-3155 implementation

---

crates/revm/src/handler/mainnet/post_execution.rs

Closes https://github.com/bluealloy/revm/issues/1154

 include return flag inside panic

---

crates/revm/src/db/states/state.rs

chore: fix wonky test

---

CHANGELOG.md

v33 is in TODO and represents unreleased Revm v6.2

bump: v34 tag

---

Cargo.lock
bins/revm-test/Cargo.toml

chore(deps): bump other alloy deps 0.7.0

---

publish.sh

chore: simple publish script

---

publish.sh

chore: fix publish revm-precompile

---

.github/dependabot.yml

getting 5+ notifications from this daily :)
once a week should be sufficient

chore: weekly dependabot

---

bins/revme/src/cmd/statetest/runner.rs

fixes: https://github.com/bluealloy/revm/issues/1265

fix(revme): Print one json outcome in statetest

---

crates/precompile/src/lib.rs

Fixes https://github.com/bluealloy/revm/pull/1389#discussion_r1596404046

fix(precompile): inherit Prague precompiles from Cancun

---

crates/primitives/src/bytecode.rs
crates/revm/src/handler/mainnet/pre_execution.rs

Small utility function that returns, padded bytes for analyzed bytecode and raw EOF bytes for EOF.

feat: Add bytes to Bytecode

---

CHANGELOG.md

chore: main CHANGELOG, tag v36

---

crates/interpreter/src/gas.rs

Closes https://github.com/bluealloy/revm/issues/1408

docs: point to gas! in Gas::record_cost

---

examples/fork_ref_transact.rs

Updates the `fork_ref_transact` example to use `alloy` instead of `ethers` for interfacing with ABIs

chore: Update fork_ref_transact to use alloy instead of ethers

---

crates/precompile/Cargo.toml
crates/precompile/src/lib.rs

Closes https://github.com/paradigmxyz/reth/issues/8210

chore(deps): allow multiple versions of secp256k1

---

README.md

Would you please add my project to the list.  Thanks for the great work on revm!

Add Simular to used-by list

---

crates/primitives/src/result.rs
crates/revm/src/optimism/handler_register.rs

refactor: group optimism invalid txn errors

---

crates/revm/src/inspector.rs
crates/revm/src/inspector/gas.rs
crates/revm/src/inspector/handler_register.rs

Adds a way to alter execution result depending on log data.

feat: pass interpreter into `Inspector::log`

---

crates/primitives/src/specification.rs

Maybe it is PraGue? :D

---

crates/interpreter/src/interpreter/analysis.rs

Found here: https://github.com/ipsilon/eof/issues/146#issuecomment-2248999555
Bug was introduced few commits before https://github.com/bluealloy/revm/pull/1648

fix(EOF): Validate code access in stack

---

bins/revme/src/cmd/bytecode.rs

Show validation output after EOF bytecode gets decoded

feat(EOF): Add EOF validation in revme bytecode cmd

---

.github/workflows/ethereum-tests.yml
bins/revme/src/cmd/eofvalidation.rs
bins/revme/src/cmd/statetest/runner.rs

This PR runs valid EOF tests from ethereum/tests suite

feat(EOF): Run EOF tests from eth/tests

---

crates/revm/src/context/evm_context.rs

h/t @onbjerg 
Load and set delegated code on call. This _might_ not be entirely correct wrt gas tracking but it fixes a critical bug that causes panics during EIP-7702 transaction execution.

fix(eip7702): set delegated code on call

---

Cargo.lock
crates/primitives/Cargo.toml
crates/primitives/src/eip7702/authorization_list.rs
crates/primitives/src/lib.rs
crates/primitives/src/state.rs
crates/revm/src/context/evm_context.rs
crates/revm/src/context/inner_evm_context.rs
crates/revm/src/db/in_memory_db.rs
crates/revm/src/db/states/bundle_account.rs
crates/revm/src/db/states/bundle_state.rs
crates/revm/src/db/states/cache_account.rs
crates/revm/src/db/states/plain_account.rs
crates/revm/src/db/states/state.rs
crates/revm/src/db/states/transition_account.rs
crates/revm/src/db/states/transition_state.rs
crates/revm/src/journaled_state.rs
crates/revm/src/optimism/handler_register.rs

chore(primitives): replace HashMap re-exports with alloy_primitives::map #1805

---

crates/database/src/states/cache_account.rs

Found it in the hot path here:

perf(`CacheAccount`): remove unneeded clone

---

crates/revm/src/db/states/cache_account.rs
crates/revm/src/db/states/transition_account.rs

[v50] perf: remove unneeded clones

---

README.md

Going through examples i noticed readme section seems outdated here. Updated it! Let me know if you need any changes. thx

Update README.md examples section

---

crates/interpreter/src/instructions/macros.rs

chore: use MemoryOOG

---

crates/precompile/src/lib.rs
crates/primitives/src/specification.rs

As discussed in https://github.com/bluealloy/revm/pull/1938#issuecomment-2560983097, adding Isthmus in v51

feat: add Isthmus spec

---

Cargo.lock
crates/primitives/Cargo.toml
crates/revm/src/evm.rs
crates/revm/src/handler/mainnet/pre_execution.rs

chore: eip7702 chainid u256 change

---

CHANGELOG.md
Cargo.lock
bins/revm-test/CHANGELOG.md
bins/revm-test/Cargo.toml
bins/revme/CHANGELOG.md
bins/revme/Cargo.toml
crates/interpreter/CHANGELOG.md
crates/interpreter/Cargo.toml
crates/precompile/CHANGELOG.md
crates/precompile/Cargo.toml
crates/primitives/CHANGELOG.md
crates/primitives/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml

chore: bump for v51, revm v19.0.0 version

---

CHANGELOG.md
Cargo.lock
bins/revme/src/cmd/statetest/models/eip7702.rs
crates/interpreter/Cargo.toml
crates/precompile/Cargo.toml
crates/primitives/CHANGELOG.md
crates/primitives/Cargo.toml
crates/primitives/src/eip7702.rs
crates/primitives/src/eip7702/authorization_list.rs
crates/primitives/src/lib.rs

Bump alloy/core and use `PrimitiveSignature`

bump: alloy core and use PrimitiveSignature

---

crates/revm/src/optimism/precompile.rs

fix(op): isthmus compilation

---

LICENSE
bins/revme/LICENSE
crates/bytecode/LICENSE
crates/database/LICENSE
crates/database/interface/LICENSE
crates/inspector/LICENSE
crates/interpreter/LICENSE
crates/optimism/LICENSE
crates/precompile/LICENSE
crates/primitives/LICENSE
crates/revm/LICENSE
crates/specification/LICENSE
crates/state/LICENSE
crates/statetest-types/LICENSE

Ref https://github.com/bluealloy/revm/pull/2051

chore: Bump licence year to 2025

---

crates/context/src/evm.rs
crates/handler/src/handler.rs
crates/optimism/src/evm.rs
crates/revm/src/exec_inspect.rs

chore: Add helpers with_inspector with_precompile

---

crates/handler/src/inspector.rs
crates/interpreter/src/interpreter.rs

This should allow to simplify some code

chore: add default generics for `InterpreterTypes`

---

Cargo.lock
Cargo.toml
crates/handler/src/validation.rs
crates/interpreter/Cargo.toml
crates/optimism/src/handler.rs
crates/optimism/src/l1block.rs
crates/precompile/Cargo.toml
crates/primitives/Cargo.toml
crates/revm/Cargo.toml

Backport of https://github.com/bluealloy/revm/pull/1967
Part of https://github.com/bluealloy/revm/issues/1896

chore: backport op l1 fetch perf

---

crates/precompile/src/bn128.rs

refactor: simplify bn128::run_pair

---

.github/workflows/ci.yml
Cargo.lock
README.md
book/src/dev.md
crates/optimism/Cargo.toml
publish.sh

chore: rename `revm-optimism` create to `op-revm`

---

crates/precompile/Cargo.toml
crates/revm/Cargo.toml

fix(precompiles): add portable flag for bls

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bins/revme/CHANGELOG.md
bins/revme/Cargo.toml
crates/handler/CHANGELOG.md
crates/handler/Cargo.toml
crates/inspector/CHANGELOG.md
crates/inspector/Cargo.toml
crates/interpreter/CHANGELOG.md
crates/interpreter/Cargo.toml
crates/optimism/CHANGELOG.md
crates/optimism/Cargo.toml
crates/precompile/CHANGELOG.md
crates/precompile/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml
crates/statetest-types/CHANGELOG.md
crates/statetest-types/Cargo.toml

bump: tag v60, revm v20.0.0-alpha.3

---

crates/optimism/src/precompiles.rs

fix(op) enable proper precompiles p256

---

Cargo.lock
crates/optimism/Cargo.toml
crates/optimism/src/evm.rs
crates/optimism/src/precompiles.rs

Add tests for checking fjord precompile activation

---

crates/database/src/states/bundle_state.rs
crates/optimism/src/spec.rs

simplify UT for OpSpecId compatibility

refactor: simplify single UT for OpSpecId compatibility.

---

crates/context/src/journaled_state.rs
crates/interpreter/src/instructions/utility.rs
crates/interpreter/src/interpreter/stack.rs

chore: fix clippy

---

crates/optimism/src/l1block.rs

Ports #2257 over to the trunk operator fee impl.

chore(op-revm): Operator Fee Fixes

---

crates/database/src/in_memory_db.rs
crates/interpreter/src/instructions/i256.rs
crates/primitives/src/eip4844.rs

chore: make number more readable

---

.github/workflows/ethereum-tests.yml

Revert removed eth/tests https://github.com/bluealloy/revm/pull/2301

fix(ci): Still run statetests from eth/tests repo

---

crates/bytecode/src/eof.rs

move Eof::new to first place && add doc for some pub functions

refactor: move Eof::new to first place && add doc for some pub functions

---

crates/bytecode/src/eof.rs

fix typo: change valitate to validate

fix: fix typo

---

crates/bytecode/src/eip7702.rs
crates/bytecode/src/eof.rs
crates/database/interface/src/empty_db.rs
crates/database/src/in_memory_db.rs
crates/handler/src/validation.rs
crates/interpreter/src/instructions/data.rs
crates/interpreter/src/instructions/utility.rs
crates/optimism/src/constants.rs
crates/precompile/src/utilities.rs
crates/primitives/src/constants.rs

support in: https://github.com/alloy-rs/core/releases/tag/v0.8.18

chore: add 0x prefix to b256! and address! calls

---

crates/revm/Cargo.toml

Reorder revm deps in Cargo.toml align to revm/src/lib.rs order

feat: Reorder revm deps in Cargo.toml

---

crates/handler/src/api.rs
crates/handler/src/evm.rs
crates/handler/src/handler.rs
crates/handler/src/lib.rs
crates/handler/src/system_call.rs
crates/inspector/src/inspect.rs
crates/interpreter/src/gas/calc.rs
crates/optimism/src/api/exec.rs
crates/optimism/src/transaction/abstraction.rs
crates/revm/src/lib.rs
crates/state/src/account_info.rs
examples/my_evm/README.md

closes #2260 
`run_system_call` added to handler and new traits with `transact_system_call` and `transact_system_call_commit` are added. Book updated.
This PR moves some traits around.

feat: support for system call

---

crates/interpreter/src/instructions/stack.rs
crates/interpreter/src/interpreter.rs
crates/optimism/src/precompiles.rs

Added tests for dupn(), swapn() and exchange() functions related to implementation of EVM opcode.

feat(tests): Add dupn, swapn and exhange tests

---

crates/state/src/account_info.rs

Closes https://github.com/bluealloy/revm/issues/2353

chore(state): Add `AccountInfo` builder util methods

---

crates/optimism/src/evm.rs

Ref https://github.com/bluealloy/revm/issues/2189 
Adds test for verifying correct liking of OP evm to inspector

test(op-inspector): Add test for inspecting logs

---

crates/context/src/tx.rs

chore: set gas_priority_fee to None in TxEnv

---

crates/context/interface/src/cfg.rs
crates/context/src/cfg.rs
crates/handler/src/validation.rs

chore: make blob params u64

---

book/src/awesome.md

https://bluealloy.github.io/revm/awesome.html

docs: Fixed formating in page `awesome`

---

crates/inspector/src/eip3155.rs

EOF create was placing trace summaries at the beginning of the trace, and not at the end.

Fix the ordering of eofcreate frame traces

---

crates/optimism/src/precompiles.rs

feat: add tests for max input size op bls precompiles

---

Cargo.lock
Cargo.toml
crates/primitives/Cargo.toml
crates/primitives/src/hardfork.rs

chore: replaced SpecId enumn with num_enum

---

crates/state/src/account_info.rs

Closes https://github.com/bluealloy/revm/issues/2418

chore: add AccountInfo setters

---

crates/context/src/journal/inner.rs
crates/inspector/src/handler.rs
crates/inspector/src/inspector.rs
examples/cheatcode_inspector/src/main.rs

Flatten journal entries to one Vec

perf(journal): flatten journal

---

crates/op-revm/src/precompiles.rs

Similar functionality to `EthPrecompiles`

feat: add precompiles getter to OpPrecompiles

---

crates/context/src/journal/inner.rs

Commented https://github.com/bluealloy/revm/pull/2440#discussion_r2054650951

chore: remove default capacity on journal reverts

---

crates/bytecode/src/utils.rs
crates/interpreter/src/interpreter/ext_bytecode.rs
crates/interpreter/src/interpreter_types.rs

Casting unsigned to signed of the same size is free

chore: simplify reading signed integers

---

crates/inspector/src/gas.rs
crates/interpreter/src/interpreter/return_data.rs
crates/interpreter/src/interpreter/shared_memory.rs
crates/interpreter/src/interpreter_types.rs

fix(inspector): fix call return with Some

---

README.md
book/src/architecture.md
book/src/contact.md
book/src/release_procedure.md
book/src/revme.md

docs: copy edit The Book

---

book/src/revme.md
crates/bytecode/src/eof/verification.rs
crates/context/src/journal/inner.rs
crates/precompile/src/bls12_381/g1_add.rs
crates/precompile/src/bls12_381/g2_add.rs
crates/revm/CHANGELOG.md
examples/erc20_gas/src/exec.rs
examples/erc20_gas/src/handler.rs
examples/my_evm/README.md

aggregate https://github.com/bluealloy/revm/pull/2472 https://github.com/bluealloy/revm/pull/2471 https://github.com/bluealloy/revm/pull/2428

chore: typos

---

crates/handler/src/frame.rs
crates/interpreter/src/interpreter.rs
crates/interpreter/src/interpreter/input.rs
crates/interpreter/src/interpreter_types.rs

Field is required for the foundry project

chore: Add Bytecode address to Interpreter

---

bins/revme/src/cmd/statetest/runner.rs
crates/context/interface/src/result.rs
crates/context/interface/src/transaction.rs
crates/context/src/tx.rs
crates/handler/src/frame.rs
crates/handler/src/handler.rs
crates/handler/src/validation.rs
crates/interpreter/src/gas/calc.rs
crates/interpreter/src/instructions/contract.rs
crates/op-revm/src/evm.rs
crates/op-revm/src/transaction/abstraction.rs
crates/primitives/src/hardfork.rs
scripts/run-tests.sh

The last decision from ACD was to remove EOF from the Osaka hardfork.

feat(Osaka): disable EOF

---

crates/handler/src/frame_data.rs
crates/handler/src/handler.rs
crates/op-revm/src/handler.rs

Add clones to frame and make `last_frame_result` a mut

chore: Add clones to FrameData

---

Cargo.lock
Cargo.toml

chore: bump c-kzg v2.1.1

---

crates/op-revm/src/transaction/error.rs

test(op): Add test coverage to `OpTransactionError`

---

crates/handler/src/pre_execution.rs
crates/op-revm/src/handler.rs
examples/erc20_gas/src/handler.rs

Nonce should be incremented for deposit contract, this was not true previously

fix(op): bump nonce on deposit

---

crates/interpreter/src/interpreter_action/call_inputs.rs

feat: added CallInput::bytes<CTX>(ctx: &CTX) -> Bytes {} function

---

crates/context/src/journal/inner.rs

feat: make Journal::set_code to be EIP-7702 zero address bytecode aware

---

crates/context/interface/src/transaction/transaction_type.rs
crates/context/src/tx.rs
crates/handler/src/handler.rs
crates/handler/src/validation.rs
crates/statetest-types/src/transaction.rs

Add logic to fill missing filelds with default values on `TxEnvBuilder::build_fill` and check missing fields on `TxEnvBuilder::build` function

chore: add TxEnvBuilder::build_fill

---

bins/revme/src/cmd/statetest/runner.rs
crates/context/interface/src/block/blob.rs
crates/context/src/block.rs
crates/context/src/cfg.rs

Closes https://github.com/bluealloy/revm/issues/2515

feat: Config blob basefee fraction

---

crates/context/src/block.rs

chore: add dot to trigger ci

---

crates/context/interface/src/block/blob.rs
crates/database/interface/Cargo.toml
crates/database/interface/src/async_db.rs
crates/database/interface/src/empty_db.rs
crates/database/interface/src/lib.rs
crates/database/interface/src/try_commit.rs
crates/handler/src/mainnet_handler.rs
crates/op-revm/Cargo.toml
crates/op-revm/src/api.rs
crates/op-revm/src/api/builder.rs
crates/op-revm/src/api/default_ctx.rs
crates/op-revm/src/api/exec.rs
crates/op-revm/src/constants.rs
crates/op-revm/src/evm.rs
crates/op-revm/src/fast_lz.rs
crates/op-revm/src/handler.rs
crates/op-revm/src/l1block.rs
crates/op-revm/src/precompiles.rs
crates/op-revm/src/result.rs
crates/op-revm/src/spec.rs
crates/op-revm/src/transaction.rs
crates/op-revm/src/transaction/abstraction.rs
crates/op-revm/src/transaction/deposit.rs
crates/op-revm/src/transaction/error.rs
crates/op-revm/tests/common.rs
crates/op-revm/tests/integration.rs

Added docs to database-interface and op-revm
Simplify `L1Block::data_gas` impl (change covered by tests)

chore(docs): add lints to database-interface and op-revm crates

---

crates/context/interface/src/cfg.rs
crates/context/interface/src/result.rs
crates/context/src/cfg.rs
crates/context/src/tx.rs
crates/handler/src/system_call.rs
crates/handler/src/validation.rs
crates/op-revm/tests/integration.rs
crates/primitives/src/eip7825.rs
crates/primitives/src/lib.rs

ref https://github.com/bluealloy/revm/issues/2567

feat(Osaka): EIP-7825 tx limit cap

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bins/revme/CHANGELOG.md
bins/revme/Cargo.toml
crates/context/CHANGELOG.md
crates/context/Cargo.toml
crates/handler/CHANGELOG.md
crates/handler/Cargo.toml
crates/inspector/CHANGELOG.md
crates/inspector/Cargo.toml
crates/op-revm/CHANGELOG.md
crates/op-revm/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml
crates/statetest-types/CHANGELOG.md
crates/statetest-types/Cargo.toml

Released from branch `release/v75`

bump: tag v75 revm v24.0.1 (#2563)

---

crates/context/Cargo.toml
crates/context/interface/src/cfg.rs
crates/context/src/cfg.rs
crates/handler/src/validation.rs

closes https://github.com/bluealloy/revm/issues/2585

feat: add optional priority fee check configuration

---

crates/interpreter/src/interpreter/ext_bytecode.rs
crates/interpreter/src/interpreter_types.rs

feat: added instruction_result fn in LoopControl trait 

---

crates/op-revm/Cargo.toml
crates/precompile/Cargo.toml
crates/precompile/src/lib.rs
crates/revm/Cargo.toml

https://github.com/ethereum/EIPs/pull/9833

feat: enable P256 in Osaka

---

crates/bytecode/src/opcode.rs
crates/interpreter/src/instructions.rs
crates/interpreter/src/instructions/bitwise.rs
crates/interpreter/src/interpreter.rs

This is a copy of https://github.com/bluealloy/revm/pull/2598 but rebased on top of fusaka/devnet2

feat: add clz

---

crates/bytecode/src/opcode.rs
crates/interpreter/src/instructions.rs
crates/interpreter/src/instructions/bitwise.rs
crates/interpreter/src/interpreter.rs

Fixes https://github.com/bluealloy/revm/issues/2600

feat: add clz opcode

---

crates/bytecode/src/legacy/jump_map.rs

Additional test to cover two bytes index of jumptable

chore(tests): test for jumptable

---

crates/op-revm/src/handler.rs

test(op/handler): verify caller account is touched by zero value transfer

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/context/CHANGELOG.md
crates/context/Cargo.toml
crates/handler/CHANGELOG.md
crates/handler/Cargo.toml
crates/inspector/CHANGELOG.md
crates/inspector/Cargo.toml
crates/op-revm/CHANGELOG.md
crates/op-revm/Cargo.toml
crates/revm/CHANGELOG.md
crates/revm/Cargo.toml

bump: v80 revm v27.0.1

---

crates/precompile/src/lib.rs
crates/precompile/src/secp256r1.rs

Update the gas cost for `P256VERIFY` precompile.

feat(precompile): update p256 verify osaka gas cost

---

crates/op-revm/tests/testdata/test_halted_deposit_tx.json
crates/primitives/src/eip7825.rs

Update EIP-7825 constant. Ref https://github.com/ethereum/EIPs/pull/9986

feat(osaka): update EIP-7825 constant

---

bins/revme/Cargo.toml

fix bench regression from https://github.com/bluealloy/revm/pull/2767

chore: back to better map

---

CHANGELOG.md
MIGRATION_GUIDE.md

chore: bump v83 revm v27.1.0

---

crates/interpreter/src/instruction_result.rs

Makes `Result<(), InstructionResult>::Ok(())` equal 0. 0 as a value is cheaper on certain architectures to return from a function and/or to branch off of (e.g. `if is_ok() { ... }`).
Same for `Option<InstructionResult>::None`, `ControlFlow`, etc.

chore: start InstructionResult at 1

---

crates/op-revm/src/precompiles.rs
crates/precompile/src/blake2.rs
crates/precompile/src/bls12_381.rs
crates/precompile/src/bls12_381/g1_add.rs
crates/precompile/src/bls12_381/g1_msm.rs
crates/precompile/src/bls12_381/g2_add.rs
crates/precompile/src/bls12_381/g2_msm.rs
crates/precompile/src/bls12_381/map_fp2_to_g2.rs
crates/precompile/src/bls12_381/map_fp_to_g1.rs
crates/precompile/src/bls12_381/pairing.rs
crates/precompile/src/bn128.rs
crates/precompile/src/hash.rs
crates/precompile/src/identity.rs
crates/precompile/src/kzg_point_evaluation.rs
crates/precompile/src/lib.rs
crates/precompile/src/modexp.rs
crates/precompile/src/secp256k1.rs
crates/precompile/src/secp256r1.rs

Add unique identifier for precompiles.

feat: precompile id

---

bins/revme/src/cmd/bench/snailtracer.rs

chore(benches): rename anaysis-inspector to snailtracer-inspect

---

crates/primitives/src/eip170.rs
crates/primitives/src/eip3860.rs
crates/primitives/src/eip4844.rs
crates/primitives/src/eip7702.rs
crates/primitives/src/eip7823.rs
crates/primitives/src/eip7825.rs
crates/primitives/src/eip7907.rs
crates/primitives/src/eip7918.rs
crates/primitives/src/lib.rs

Docs: improve primitives crate documentation and consistency
- Expand lib.rs crate-level documentation with detailed feature overview
- Enhance type alias documentation for StorageKey and StorageValue
- Standardize EIP file documentation headers with consistent format
- Fix TODO comment in eip7907.rs with proper EIP description
- Unify all EIP modules with descriptive titles and brief explanations

docs: improve primitives crate documentation and consistency

---

crates/interpreter/src/instructions/macros.rs
crates/interpreter/src/interpreter.rs

Specialize halt to make code very slightly smaller

chore: specialize halt, making instruction code very slightly smaller

---

crates/precompile/src/modexp.rs

Found here: https://discord.com/channels/595666850260713488/1402573131692118118/1403383621720739902
cc @rkrasiuk have make a commit to `fusaka-devnet-3` branch https://github.com/bluealloy/revm/commit/07a68a3f9b79224ad839e50889ef77039da511ad

fix(osaka): do base/mod zero check after gas calc

---

crates/state/src/lib.rs

ref https://github.com/bluealloy/revm/pull/1805

chore: use primitives::HashMap default

---

crates/statetest-types/src/env.rs
crates/statetest-types/src/test_unit.rs

It looks like these fields are not used inside tests.

test: remove parent blob gas used and excess

---

crates/interpreter/src/gas/constants.rs

2 comments for EIP-2930 consts

docs: comments on EIP-2929/2930 constants

---

CLAUDE.md

fix(CLAUDE.md): typo in `cargo nextest` command

---

bins/revme/src/cmd/blockchaintest.rs

fix(revme): Insert block hashes in State

---

crates/inspector/src/traits.rs

Detached `EthFrame` from `InspectorEvmTr` and allows custom EthFrames to be inspected.
Split from https://github.com/bluealloy/revm/pull/3009

feat: detach EthFrame from InspectorEvmTr

---

README.md

add boundless in Major block builders

add boundless
